// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor._DocPerformanceMonitor. Do not edit; put additions in Inv_DocPerformanceMonitor.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class Inv_DocPerformanceMonitor
    {
        #region Internal properties
        internal Inventor._DocPerformanceMonitor Internal_DocPerformanceMonitor { get; set; }

        #endregion

        #region Private constructors
        private Inv_DocPerformanceMonitor(Inv_DocPerformanceMonitor inv_DocPerformanceMonitor)
        {
            Internal_DocPerformanceMonitor = inv_DocPerformanceMonitor.Internal_DocPerformanceMonitor;
        }

        private Inv_DocPerformanceMonitor(Inventor._DocPerformanceMonitor inv_DocPerformanceMonitor)
        {
            Internal_DocPerformanceMonitor = inv_DocPerformanceMonitor;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor._DocPerformanceMonitor _DocPerformanceMonitorInstance
        {
            get { return Internal_DocPerformanceMonitor; }
            set { Internal_DocPerformanceMonitor = value; }
        }

        #endregion

        #region Public static constructors
        public static Inv_DocPerformanceMonitor ByInv_DocPerformanceMonitor(Inv_DocPerformanceMonitor inv_DocPerformanceMonitor)
        {
            return inv_DocPerformanceMonitor == null ? null : new Inv_DocPerformanceMonitor(inv_DocPerformanceMonitor);
        }

        [SupressImportIntoVM]
        public static Inv_DocPerformanceMonitor ByInv_DocPerformanceMonitor(Inventor._DocPerformanceMonitor inv_DocPerformanceMonitor)
        {
            return inv_DocPerformanceMonitor == null ? null : new Inv_DocPerformanceMonitor(inv_DocPerformanceMonitor);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
