// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.AttributeManager. Do not edit; put additions in InvAttributeManager.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvAttributeManager
    {
        #region Internal properties
        internal Inventor.AttributeManager InternalAttributeManager { get; set; }

        internal object InternalParent
        {
            get { return AttributeManagerInstance.Parent; }
        }

        internal string InternalRevisionId
        {
            get { return AttributeManagerInstance.RevisionId; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)AttributeManagerInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvAttributeManager(InvAttributeManager invAttributeManager)
        {
            InternalAttributeManager = invAttributeManager.InternalAttributeManager;
        }

        private InvAttributeManager(Inventor.AttributeManager invAttributeManager)
        {
            InternalAttributeManager = invAttributeManager;
        }
        #endregion

        #region Private methods
        // skipped: FindAttributeSets(): returns Inventor.AttributeSetsEnumerator, not wrapped
        // skipped: FindAttributes(): returns Inventor.AttributesEnumerator, not wrapped
        private InvObjectCollection InternalFindObjects(string attributeSetName, string attributeName, object attributeValue)
        {
            return InvObjectCollection.ByInvObjectCollection(AttributeManagerInstance.FindObjects(attributeSetName, attributeName, attributeValue));
        }

        private InvObjectCollection InternalFindObjectsByPattern(string xPath)
        {
            return InvObjectCollection.ByInvObjectCollection(AttributeManagerInstance.FindObjectsByPattern(xPath));
        }

        // skipped: OpenAttributeSets(): returns Inventor.AttributeSetsEnumerator, not wrapped
        private void InternalPurgeAttributeSets(string attributeSetName, bool preview, out object previewResult)
        {
            AttributeManagerInstance.PurgeAttributeSets(attributeSetName, preview, out previewResult);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.AttributeManager AttributeManagerInstance
        {
            get { return InternalAttributeManager; }
            set { InternalAttributeManager = value; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public string RevisionId
        {
            get { return InternalRevisionId; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvAttributeManager ByInvAttributeManager(InvAttributeManager invAttributeManager)
        {
            return invAttributeManager == null ? null : new InvAttributeManager(invAttributeManager);
        }

        [SupressImportIntoVM]
        public static InvAttributeManager ByInvAttributeManager(Inventor.AttributeManager invAttributeManager)
        {
            return invAttributeManager == null ? null : new InvAttributeManager(invAttributeManager);
        }
        #endregion

        #region Public methods
        public InvObjectCollection FindObjects(string attributeSetName, string attributeName, object attributeValue)
        {
            return InternalFindObjects(attributeSetName, attributeName, attributeValue);
        }

        public InvObjectCollection FindObjectsByPattern(string xPath)
        {
            return InternalFindObjectsByPattern(xPath);
        }

        public void PurgeAttributeSets(string attributeSetName, bool preview, out object previewResult)
        {
            InternalPurgeAttributeSets(attributeSetName, preview, out previewResult);
        }

        #endregion
    }
}
