// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.AssemblyWorkPlaneDef. Do not edit; put additions in InvAssemblyWorkPlaneDef.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvAssemblyWorkPlaneDef
    {
        #region Internal properties
        internal Inventor.AssemblyWorkPlaneDef InternalAssemblyWorkPlaneDef { get; set; }

        internal object InternalApplication
        {
            get { return AssemblyWorkPlaneDefInstance.Application; }
        }

        // skipped: Constraints: Inventor.AssemblyConstraintsEnumerator is not wrapped
        internal InvPoint InternalOriginPoint
        {
            get { return InvPoint.ByInvPoint(AssemblyWorkPlaneDefInstance.OriginPoint); }
        }

        internal InvWorkPlane InternalParent
        {
            get { return InvWorkPlane.ByInvWorkPlane(AssemblyWorkPlaneDefInstance.Parent); }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)AssemblyWorkPlaneDefInstance.Type; }
        }

        internal InvUnitVector InternalXAxis
        {
            get { return InvUnitVector.ByInvUnitVector(AssemblyWorkPlaneDefInstance.XAxis); }
        }

        internal InvUnitVector InternalYAxis
        {
            get { return InvUnitVector.ByInvUnitVector(AssemblyWorkPlaneDefInstance.YAxis); }
        }

        #endregion

        #region Private constructors
        private InvAssemblyWorkPlaneDef(InvAssemblyWorkPlaneDef invAssemblyWorkPlaneDef)
        {
            InternalAssemblyWorkPlaneDef = invAssemblyWorkPlaneDef.InternalAssemblyWorkPlaneDef;
        }

        private InvAssemblyWorkPlaneDef(Inventor.AssemblyWorkPlaneDef invAssemblyWorkPlaneDef)
        {
            InternalAssemblyWorkPlaneDef = invAssemblyWorkPlaneDef;
        }
        #endregion

        #region Private methods
        // skipped: GetData(): parameter OriginPoint is a ref/out Inventor.Point
        private void InternalPutData(InvPoint originPoint, InvUnitVector xAxis, InvUnitVector yAxis)
        {
            AssemblyWorkPlaneDefInstance.PutData(originPoint?.PointInstance, xAxis?.UnitVectorInstance, yAxis?.UnitVectorInstance);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.AssemblyWorkPlaneDef AssemblyWorkPlaneDefInstance
        {
            get { return InternalAssemblyWorkPlaneDef; }
            set { InternalAssemblyWorkPlaneDef = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public InvPoint OriginPoint
        {
            get { return InternalOriginPoint; }
        }

        public InvWorkPlane Parent
        {
            get { return InternalParent; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public InvUnitVector XAxis
        {
            get { return InternalXAxis; }
        }

        public InvUnitVector YAxis
        {
            get { return InternalYAxis; }
        }

        #endregion

        #region Public static constructors
        public static InvAssemblyWorkPlaneDef ByInvAssemblyWorkPlaneDef(InvAssemblyWorkPlaneDef invAssemblyWorkPlaneDef)
        {
            return invAssemblyWorkPlaneDef == null ? null : new InvAssemblyWorkPlaneDef(invAssemblyWorkPlaneDef);
        }

        [SupressImportIntoVM]
        public static InvAssemblyWorkPlaneDef ByInvAssemblyWorkPlaneDef(Inventor.AssemblyWorkPlaneDef invAssemblyWorkPlaneDef)
        {
            return invAssemblyWorkPlaneDef == null ? null : new InvAssemblyWorkPlaneDef(invAssemblyWorkPlaneDef);
        }
        #endregion

        #region Public methods
        public void PutData(InvPoint originPoint, InvUnitVector xAxis, InvUnitVector yAxis)
        {
            InternalPutData(originPoint, xAxis, yAxis);
        }

        #endregion
    }
}
