// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.AssemblyWorkPointDef. Do not edit; put additions in InvAssemblyWorkPointDef.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvAssemblyWorkPointDef
    {
        #region Internal properties
        internal Inventor.AssemblyWorkPointDef InternalAssemblyWorkPointDef { get; set; }

        internal object InternalApplication
        {
            get { return AssemblyWorkPointDefInstance.Application; }
        }

        // skipped: Constraints: Inventor.AssemblyConstraintsEnumerator is not wrapped
        internal InvWorkPoint InternalParent
        {
            get { return InvWorkPoint.ByInvWorkPoint(AssemblyWorkPointDefInstance.Parent); }
        }

        internal InvPoint InternalPoint
        {
            get { return InvPoint.ByInvPoint(AssemblyWorkPointDefInstance.Point); }
            set { AssemblyWorkPointDefInstance.Point = value?.PointInstance; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)AssemblyWorkPointDefInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvAssemblyWorkPointDef(InvAssemblyWorkPointDef invAssemblyWorkPointDef)
        {
            InternalAssemblyWorkPointDef = invAssemblyWorkPointDef.InternalAssemblyWorkPointDef;
        }

        private InvAssemblyWorkPointDef(Inventor.AssemblyWorkPointDef invAssemblyWorkPointDef)
        {
            InternalAssemblyWorkPointDef = invAssemblyWorkPointDef;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.AssemblyWorkPointDef AssemblyWorkPointDefInstance
        {
            get { return InternalAssemblyWorkPointDef; }
            set { InternalAssemblyWorkPointDef = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public InvWorkPoint Parent
        {
            get { return InternalParent; }
        }

        public InvPoint Point
        {
            get { return InternalPoint; }
            set { InternalPoint = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvAssemblyWorkPointDef ByInvAssemblyWorkPointDef(InvAssemblyWorkPointDef invAssemblyWorkPointDef)
        {
            return invAssemblyWorkPointDef == null ? null : new InvAssemblyWorkPointDef(invAssemblyWorkPointDef);
        }

        [SupressImportIntoVM]
        public static InvAssemblyWorkPointDef ByInvAssemblyWorkPointDef(Inventor.AssemblyWorkPointDef invAssemblyWorkPointDef)
        {
            return invAssemblyWorkPointDef == null ? null : new InvAssemblyWorkPointDef(invAssemblyWorkPointDef);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
