// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.AssemblyComponentDefinitions. Do not edit; put additions in InvAssemblyComponentDefinitions.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvAssemblyComponentDefinitions
    {
        #region Internal properties
        internal Inventor.AssemblyComponentDefinitions InternalAssemblyComponentDefinitions { get; set; }

        internal object InternalApplication
        {
            get { return AssemblyComponentDefinitionsInstance.Application; }
        }

        internal int InternalCount
        {
            get { return AssemblyComponentDefinitionsInstance.Count; }
        }

        internal InvAssemblyComponentDefinition InternalItem(int index)
        {
            return InvAssemblyComponentDefinition.ByInvAssemblyComponentDefinition(AssemblyComponentDefinitionsInstance[index]);
        }

        // skipped: Parent: Inventor._AssemblyDocument is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)AssemblyComponentDefinitionsInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvAssemblyComponentDefinitions(InvAssemblyComponentDefinitions invAssemblyComponentDefinitions)
        {
            InternalAssemblyComponentDefinitions = invAssemblyComponentDefinitions.InternalAssemblyComponentDefinitions;
        }

        private InvAssemblyComponentDefinitions(Inventor.AssemblyComponentDefinitions invAssemblyComponentDefinitions)
        {
            InternalAssemblyComponentDefinitions = invAssemblyComponentDefinitions;
        }
        #endregion

        #region Private methods
        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.AssemblyComponentDefinitions AssemblyComponentDefinitionsInstance
        {
            get { return InternalAssemblyComponentDefinitions; }
            set { InternalAssemblyComponentDefinitions = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvAssemblyComponentDefinition Item(int index)
        {
            return InternalItem(index);
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvAssemblyComponentDefinitions ByInvAssemblyComponentDefinitions(InvAssemblyComponentDefinitions invAssemblyComponentDefinitions)
        {
            return invAssemblyComponentDefinitions == null ? null : new InvAssemblyComponentDefinitions(invAssemblyComponentDefinitions);
        }

        [SupressImportIntoVM]
        public static InvAssemblyComponentDefinitions ByInvAssemblyComponentDefinitions(Inventor.AssemblyComponentDefinitions invAssemblyComponentDefinitions)
        {
            return invAssemblyComponentDefinitions == null ? null : new InvAssemblyComponentDefinitions(invAssemblyComponentDefinitions);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
