// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Assets. Do not edit; put additions in InvAssets.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvAssets
    {
        #region Internal properties
        internal Inventor.Assets InternalAssets { get; set; }

        internal object InternalApplication
        {
            get { return AssetsInstance.Application; }
        }

        internal int InternalCount
        {
            get { return AssetsInstance.Count; }
        }

        internal InvAsset InternalItem(object index)
        {
            return InvAsset.ByInvAsset(AssetsInstance[index]);
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)AssetsInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvAssets(InvAssets invAssets)
        {
            InternalAssets = invAssets.InternalAssets;
        }

        private InvAssets(Inventor.Assets invAssets)
        {
            InternalAssets = invAssets;
        }
        #endregion

        #region Private methods
        // skipped: Add(): parameter AssetType is Inventor.AssetTypeEnum, not wrapped
        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Assets AssetsInstance
        {
            get { return InternalAssets; }
            set { InternalAssets = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvAsset Item(object index)
        {
            return InternalItem(index);
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvAssets ByInvAssets(InvAssets invAssets)
        {
            return invAssets == null ? null : new InvAssets(invAssets);
        }

        [SupressImportIntoVM]
        public static InvAssets ByInvAssets(Inventor.Assets invAssets)
        {
            return invAssets == null ? null : new InvAssets(invAssets);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
