// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ActionTypeEnum. Do not edit; put additions in InvActionTypeEnum.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public enum InvActionTypeEnum
    {
        kActivationAction = Inventor.ActionTypeEnum.kActivationAction,
        kAllActions = Inventor.ActionTypeEnum.kAllActions,
        kDeleteAction = Inventor.ActionTypeEnum.kDeleteAction,
        kMoveAction = Inventor.ActionTypeEnum.kMoveAction,
        kNoAction = Inventor.ActionTypeEnum.kNoAction,
        kReorderAction = Inventor.ActionTypeEnum.kReorderAction,
        kRestructureAction = Inventor.ActionTypeEnum.kRestructureAction
    }
}
