// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Application. Do not edit; put additions in InvApplication.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvApplication
    {
        #region Internal properties
        internal Inventor.Application InternalApplication { get; set; }

        internal string InternalADPDeviceId
        {
            get { return ApplicationInstance.ADPDeviceId; }
        }

        internal string InternalADPSessionId
        {
            get { return ApplicationInstance.ADPSessionId; }
        }

        // skipped: ActiveAppearanceLibrary: Inventor.AssetLibrary is not wrapped
        // skipped: ActiveColorScheme: Inventor.ColorScheme is not wrapped
        // skipped: ActiveDocument: Inventor._Document is not wrapped
        internal InvDocumentTypeEnum InternalActiveDocumentType
        {
            get { return (InvDocumentTypeEnum)ApplicationInstance.ActiveDocumentType; }
        }

        // skipped: ActiveEditDocument: Inventor._Document is not wrapped
        internal object InternalActiveEditObject
        {
            get { return ApplicationInstance.ActiveEditObject; }
        }

        internal InvEnvironment InternalActiveEnvironment
        {
            get { return InvEnvironment.ByInvEnvironment(ApplicationInstance.ActiveEnvironment); }
        }

        // skipped: ActiveMaterialLibrary: Inventor.AssetLibrary is not wrapped
        // skipped: ActiveView: Inventor.View is not wrapped
        // skipped: ActiveViewFrame: Inventor.ViewFrame is not wrapped
        // skipped: ActiveWebView: Inventor.WebView is not wrapped
        internal string InternalAllUsersAppDataPath
        {
            get { return ApplicationInstance.AllUsersAppDataPath; }
        }

        internal bool InternalAllowDataCollectionForAnalyticsPrograms
        {
            get { return ApplicationInstance.AllowDataCollectionForAnalyticsPrograms; }
        }

        // skipped: ApplicationAddIns: Inventor.ApplicationAddIns is not wrapped
        // skipped: ApplicationEvents: Inventor.ApplicationEvents is not wrapped
        // skipped: AssemblyEvents: Inventor.AssemblyEvents is not wrapped
        // skipped: AssemblyOptions: Inventor.AssemblyOptions is not wrapped
        // skipped: AssetLibraries: Inventor.AssetLibraries is not wrapped
        internal string[] InternalAvailableComparisonVersions
        {
            get { return ApplicationInstance.AvailableComparisonVersions; }
        }

        // skipped: CameraEvents: Inventor.CameraEvents is not wrapped
        internal bool InternalCameraRollMode3Dx
        {
            get { return ApplicationInstance.CameraRollMode3Dx; }
            set { ApplicationInstance.CameraRollMode3Dx = value; }
        }

        internal string InternalCaption
        {
            get { return ApplicationInstance.Caption; }
            set { ApplicationInstance.Caption = value; }
        }

        // skipped: ChangeManager: Inventor.ChangeManager is not wrapped
        // skipped: ClientOperationEvents: Inventor.ClientOperationEvents is not wrapped
        // skipped: ClientResourceMaps: Inventor.ClientResourceMaps is not wrapped
        // skipped: ColorSchemes: Inventor.ColorSchemes is not wrapped
        // skipped: CommandManager: Inventor.CommandManager is not wrapped
        internal string InternalComparisonVersion
        {
            get { return ApplicationInstance.ComparisonVersion; }
            set { ApplicationInstance.ComparisonVersion = value; }
        }

        // skipped: ContentCenter: Inventor.ContentCenter is not wrapped
        // skipped: ContentCenterOptions: Inventor.ContentCenterOptions is not wrapped
        internal string InternalCurrentUserAppDataPath
        {
            get { return ApplicationInstance.CurrentUserAppDataPath; }
        }

        // skipped: DarkSiteLevel: Inventor.DarkSiteLevelEnum is not wrapped
        // skipped: DesignProjectManager: Inventor.DesignProjectManager is not wrapped
        // skipped: DisplayOptions: Inventor.DisplayOptions is not wrapped
        internal InvDocuments InternalDocuments
        {
            get { return InvDocuments.ByInvDocuments(ApplicationInstance.Documents); }
        }

        // skipped: DrawingOptions: Inventor.DrawingOptions is not wrapped
        // skipped: EnvironmentBaseCollection: Inventor.EnvironmentBaseCollection is not wrapped
        // skipped: Environments: Inventor.Environments is not wrapped
        // skipped: ErrorManager: Inventor.ErrorManager is not wrapped
        internal InvAssetsEnumerator InternalFavoriteAssets
        {
            get { return InvAssetsEnumerator.ByInvAssetsEnumerator(ApplicationInstance.FavoriteAssets); }
        }

        // skipped: FileAccessEvents: Inventor.FileAccessEvents is not wrapped
        // skipped: FileLocations: Inventor.FileLocations is not wrapped
        // skipped: FileManager: Inventor.FileManager is not wrapped
        // skipped: FileOptions: Inventor.FileOptions is not wrapped
        // skipped: FileUIEvents: Inventor.FileUIEvents is not wrapped
        internal bool InternalFlythroughMode3Dx
        {
            get { return ApplicationInstance.FlythroughMode3Dx; }
            set { ApplicationInstance.FlythroughMode3Dx = value; }
        }

        // skipped: GeneralOptions: Inventor.GeneralOptions is not wrapped
        // skipped: HardwareOptions: Inventor.HardwareOptions is not wrapped
        internal int InternalHeight
        {
            get { return ApplicationInstance.Height; }
            set { ApplicationInstance.Height = value; }
        }

        // skipped: HelpManager: Inventor.HelpManager is not wrapped
        internal string InternalInstallPath
        {
            get { return ApplicationInstance.InstallPath; }
        }

        internal bool InternalIsCIPEnabled
        {
            get { return ApplicationInstance.IsCIPEnabled; }
        }

        internal bool InternalIsIn3dPrintMode
        {
            get { return ApplicationInstance.IsIn3dPrintMode; }
        }

        internal string InternalLanguageCode
        {
            get { return ApplicationInstance.LanguageCode; }
        }

        internal string InternalLanguageName
        {
            get { return ApplicationInstance.LanguageName; }
        }

        // skipped: LanguageTools: Inventor.LanguageTools is not wrapped
        internal int InternalLeft
        {
            get { return ApplicationInstance.Left; }
            set { ApplicationInstance.Left = value; }
        }

        // skipped: LicenseManager: Inventor.LicenseManager is not wrapped
        internal int InternalLocale
        {
            get { return ApplicationInstance.Locale; }
        }

        internal bool InternalLoggedIn
        {
            get { return ApplicationInstance.LoggedIn; }
        }

        internal string InternalLoginUserId
        {
            get { return ApplicationInstance.LoginUserId; }
        }

        internal string InternalLoginUserName
        {
            get { return ApplicationInstance.LoginUserName; }
        }

        internal bool InternalMRUDisplay
        {
            get { return ApplicationInstance.MRUDisplay; }
            set { ApplicationInstance.MRUDisplay = value; }
        }

        internal bool InternalMRUEnabled
        {
            get { return ApplicationInstance.MRUEnabled; }
            set { ApplicationInstance.MRUEnabled = value; }
        }

        internal int InternalMainFrameHWND
        {
            get { return ApplicationInstance.MainFrameHWND; }
        }

        // skipped: MaterialDisplayUnits: Inventor.MaterialDisplayUnitsEnum is not wrapped
        // skipped: MeasureTools: Inventor.MeasureTools is not wrapped
        // skipped: ModelStateEvents: Inventor.ModelStateEvents is not wrapped
        // skipped: ModelingEvents: Inventor.ModelingEvents is not wrapped
        // skipped: NotebookOptions: Inventor.NotebookOptions is not wrapped
        internal bool InternalOpenDocumentsDisplay
        {
            get { return ApplicationInstance.OpenDocumentsDisplay; }
            set { ApplicationInstance.OpenDocumentsDisplay = value; }
        }

        // skipped: PartOptions: Inventor.PartOptions is not wrapped
        // skipped: Preferences: Inventor.ObjectsEnumeratorByVariant is not wrapped
        // skipped: PresentationOptions: Inventor.PresentationOptions is not wrapped
        // skipped: PromptsOptions: Inventor.PromptsOptions is not wrapped
        internal bool InternalReady
        {
            get { return ApplicationInstance.Ready; }
        }

        // skipped: ReferenceKeyEvents: Inventor.ReferenceKeyEvents is not wrapped
        // skipped: RepresentationEvents: Inventor.RepresentationEvents is not wrapped
        // skipped: SaveOptions: Inventor.SaveOptions is not wrapped
        internal bool InternalScreenUpdating
        {
            get { return ApplicationInstance.ScreenUpdating; }
            set { ApplicationInstance.ScreenUpdating = value; }
        }

        internal bool InternalSilentOperation
        {
            get { return ApplicationInstance.SilentOperation; }
            set { ApplicationInstance.SilentOperation = value; }
        }

        // skipped: Sketch3DOptions: Inventor.Sketch3DOptions is not wrapped
        // skipped: SketchEvents: Inventor.SketchEvents is not wrapped
        // skipped: SketchOptions: Inventor.SketchOptions is not wrapped
        internal InvSoftwareVersion InternalSoftwareVersion
        {
            get { return InvSoftwareVersion.ByInvSoftwareVersion(ApplicationInstance.SoftwareVersion); }
        }

        internal string InternalStatusBarText
        {
            get { return ApplicationInstance.StatusBarText; }
            set { ApplicationInstance.StatusBarText = value; }
        }

        // skipped: StyleEvents: Inventor.StyleEvents is not wrapped
        // skipped: StylesManager: Inventor.StylesManager is not wrapped
        // skipped: SubscriptionStatus: Inventor.StatusEnum is not wrapped
        internal bool InternalSupportsFileManagement
        {
            get { return ApplicationInstance.SupportsFileManagement; }
            set { ApplicationInstance.SupportsFileManagement = value; }
        }

        // skipped: TestManager: Inventor.TestManager is not wrapped
        // skipped: ThemeManager: Inventor.ThemeManager is not wrapped
        internal int InternalTop
        {
            get { return ApplicationInstance.Top; }
            set { ApplicationInstance.Top = value; }
        }

        // skipped: TransactionManager: Inventor.TransactionManager is not wrapped
        // skipped: TransientBRep: Inventor.TransientBRep is not wrapped
        internal InvTransientGeometry InternalTransientGeometry
        {
            get { return InvTransientGeometry.ByInvTransientGeometry(ApplicationInstance.TransientGeometry); }
        }

        // skipped: TransientObjects: Inventor.TransientObjects is not wrapped
        // skipped: TutorialsManager: Inventor.TutorialsManager is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ApplicationInstance.Type; }
        }

        internal InvUnitsOfMeasure InternalUnitsOfMeasure
        {
            get { return InvUnitsOfMeasure.ByInvUnitsOfMeasure(ApplicationInstance.UnitsOfMeasure); }
        }

        // skipped: UserInterfaceManager: Inventor.UserInterfaceManager is not wrapped
        internal string InternalUserName
        {
            get { return ApplicationInstance.UserName; }
            set { ApplicationInstance.UserName = value; }
        }

        // skipped: VBAProjects: Inventor.InventorVBAProjects is not wrapped
        internal object InternalVBE
        {
            get { return ApplicationInstance.VBE; }
        }

        // skipped: ViewFrames: Inventor.ViewFramesEnumerator is not wrapped
        // skipped: Views: Inventor.ViewsEnumerator is not wrapped
        internal bool InternalVisible
        {
            get { return ApplicationInstance.Visible; }
            set { ApplicationInstance.Visible = value; }
        }

        // skipped: WebBrowserDialogs: Inventor.WebBrowserDialogs is not wrapped
        // skipped: WebViews: Inventor.WebViews is not wrapped
        internal int InternalWidth
        {
            get { return ApplicationInstance.Width; }
            set { ApplicationInstance.Width = value; }
        }

        // skipped: WindowState: Inventor.WindowsSizeEnum is not wrapped
        // skipped: iFeatureOptions: Inventor.iFeatureOptions is not wrapped
        // skipped: iLogicOptions: Inventor.iLogicOptions is not wrapped
        #endregion

        #region Private constructors
        private InvApplication(InvApplication invApplication)
        {
            InternalApplication = invApplication.InternalApplication;
        }

        private InvApplication(Inventor.Application invApplication)
        {
            InternalApplication = invApplication;
        }
        #endregion

        #region Private methods
        private void InternalConstructInternalNameAndRevisionId(string internalNameToken, string revisionIdToken, out string internalName, out string revisionId)
        {
            ApplicationInstance.ConstructInternalNameAndRevisionId(internalNameToken, revisionIdToken, out internalName, out revisionId);
        }

        // skipped: CreateFactoryTableDialog(): returns Inventor.FactoryTableDialog, not wrapped
        // skipped: CreateFileDialog(): parameter Dialog is Inventor.FileDialog, not wrapped
        private void InternalCreateInternalName(string name, string number, string custom, out string internalName)
        {
            ApplicationInstance.CreateInternalName(name, number, custom, out internalName);
        }

        // skipped: CreateProgressBar(): returns Inventor.ProgressBar, not wrapped
        private void InternalExportApplicationOptions(string fullFileName)
        {
            ApplicationInstance.ExportApplicationOptions(fullFileName);
        }

        private void InternalGetAppFrameExtents(out int top, out int left, out int height, out int width)
        {
            ApplicationInstance.GetAppFrameExtents(out top, out left, out height, out width);
        }

        private object InternalGetInterfaceObject(string progIDorCLSID)
        {
            return ApplicationInstance.GetInterfaceObject(progIDorCLSID);
        }

        private object InternalGetInterfaceObject32(string progIDorCLSID)
        {
            return ApplicationInstance.GetInterfaceObject32(progIDorCLSID);
        }

        private void InternalGetMDIClientAreaExtents(out int top, out int left, out int height, out int width)
        {
            ApplicationInstance.GetMDIClientAreaExtents(out top, out left, out height, out width);
        }

        private string InternalGetMaterialXFromAsset(InvAsset asset, object converterOptions)
        {
            return ApplicationInstance.GetMaterialXFromAsset(asset?.AssetInstance, converterOptions);
        }

        // skipped: GetPluginLicenseManager(): returns Inventor.PluginLicenseManager, not wrapped
        // skipped: GetPluginLicenseManager2(): returns Inventor.PluginLicenseManager, not wrapped
        // skipped: GetSubscriptionEnablerStatus(): returns Inventor.StatusEnum, not wrapped
        // skipped: GetTemplateFile(): parameter SystemOfMeasure is Inventor.SystemOfMeasureEnum, not wrapped
        private void InternalImportApplicationOptions(string fullFileName)
        {
            ApplicationInstance.ImportApplicationOptions(fullFileName);
        }

        private string InternalLicenseChallenge()
        {
            return ApplicationInstance.LicenseChallenge();
        }

        private void InternalLicenseResponse(string response)
        {
            ApplicationInstance.LicenseResponse(response);
        }

        private void InternalLoadRealDWGInfrastructure()
        {
            ApplicationInstance.LoadRealDWGInfrastructure();
        }

        private bool InternalLogin()
        {
            return ApplicationInstance.Login();
        }

        private void InternalMove(ref int top, ref int left, ref int height, ref int width)
        {
            ApplicationInstance.Move(ref top, ref left, ref height, ref width);
        }

        private void InternalQuit()
        {
            ApplicationInstance.Quit();
        }

        private void InternalRefreshRibbonForComparison()
        {
            ApplicationInstance.RefreshRibbonForComparison();
        }

        private void InternalReserveLicense(string clientId)
        {
            ApplicationInstance.ReserveLicense(clientId);
        }

        private void InternalShowMyHomeWindow(object contentTypeOrURL)
        {
            ApplicationInstance.ShowMyHomeWindow(contentTypeOrURL);
        }

        private void InternalUnreserveLicense(string clientId)
        {
            ApplicationInstance.UnreserveLicense(clientId);
        }

        private void InternalUseAutoCADRelatedSettings()
        {
            ApplicationInstance.UseAutoCADRelatedSettings();
        }

        private void InternalUseInventorSettings()
        {
            ApplicationInstance.UseInventorSettings();
        }

        private void InternalWriteCIPWaypoint(string waypointData)
        {
            ApplicationInstance.WriteCIPWaypoint(waypointData);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Application ApplicationInstance
        {
            get { return InternalApplication; }
            set { InternalApplication = value; }
        }

        public string ADPDeviceId
        {
            get { return InternalADPDeviceId; }
        }

        public string ADPSessionId
        {
            get { return InternalADPSessionId; }
        }

        public InvDocumentTypeEnum ActiveDocumentType
        {
            get { return InternalActiveDocumentType; }
        }

        public object ActiveEditObject
        {
            get { return InternalActiveEditObject; }
        }

        public InvEnvironment ActiveEnvironment
        {
            get { return InternalActiveEnvironment; }
        }

        public string AllUsersAppDataPath
        {
            get { return InternalAllUsersAppDataPath; }
        }

        public bool AllowDataCollectionForAnalyticsPrograms
        {
            get { return InternalAllowDataCollectionForAnalyticsPrograms; }
        }

        public string[] AvailableComparisonVersions
        {
            get { return InternalAvailableComparisonVersions; }
        }

        public bool CameraRollMode3Dx
        {
            get { return InternalCameraRollMode3Dx; }
            set { InternalCameraRollMode3Dx = value; }
        }

        public string Caption
        {
            get { return InternalCaption; }
            set { InternalCaption = value; }
        }

        public string ComparisonVersion
        {
            get { return InternalComparisonVersion; }
            set { InternalComparisonVersion = value; }
        }

        public string CurrentUserAppDataPath
        {
            get { return InternalCurrentUserAppDataPath; }
        }

        public InvDocuments Documents
        {
            get { return InternalDocuments; }
        }

        public InvAssetsEnumerator FavoriteAssets
        {
            get { return InternalFavoriteAssets; }
        }

        public bool FlythroughMode3Dx
        {
            get { return InternalFlythroughMode3Dx; }
            set { InternalFlythroughMode3Dx = value; }
        }

        public int Height
        {
            get { return InternalHeight; }
            set { InternalHeight = value; }
        }

        public string InstallPath
        {
            get { return InternalInstallPath; }
        }

        public bool IsCIPEnabled
        {
            get { return InternalIsCIPEnabled; }
        }

        public bool IsIn3dPrintMode
        {
            get { return InternalIsIn3dPrintMode; }
        }

        public string LanguageCode
        {
            get { return InternalLanguageCode; }
        }

        public string LanguageName
        {
            get { return InternalLanguageName; }
        }

        public int Left
        {
            get { return InternalLeft; }
            set { InternalLeft = value; }
        }

        public int Locale
        {
            get { return InternalLocale; }
        }

        public bool LoggedIn
        {
            get { return InternalLoggedIn; }
        }

        public string LoginUserId
        {
            get { return InternalLoginUserId; }
        }

        public string LoginUserName
        {
            get { return InternalLoginUserName; }
        }

        public bool MRUDisplay
        {
            get { return InternalMRUDisplay; }
            set { InternalMRUDisplay = value; }
        }

        public bool MRUEnabled
        {
            get { return InternalMRUEnabled; }
            set { InternalMRUEnabled = value; }
        }

        public int MainFrameHWND
        {
            get { return InternalMainFrameHWND; }
        }

        public bool OpenDocumentsDisplay
        {
            get { return InternalOpenDocumentsDisplay; }
            set { InternalOpenDocumentsDisplay = value; }
        }

        public bool Ready
        {
            get { return InternalReady; }
        }

        public bool ScreenUpdating
        {
            get { return InternalScreenUpdating; }
            set { InternalScreenUpdating = value; }
        }

        public bool SilentOperation
        {
            get { return InternalSilentOperation; }
            set { InternalSilentOperation = value; }
        }

        public InvSoftwareVersion SoftwareVersion
        {
            get { return InternalSoftwareVersion; }
        }

        public string StatusBarText
        {
            get { return InternalStatusBarText; }
            set { InternalStatusBarText = value; }
        }

        public bool SupportsFileManagement
        {
            get { return InternalSupportsFileManagement; }
            set { InternalSupportsFileManagement = value; }
        }

        public int Top
        {
            get { return InternalTop; }
            set { InternalTop = value; }
        }

        public InvTransientGeometry TransientGeometry
        {
            get { return InternalTransientGeometry; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public InvUnitsOfMeasure UnitsOfMeasure
        {
            get { return InternalUnitsOfMeasure; }
        }

        public string UserName
        {
            get { return InternalUserName; }
            set { InternalUserName = value; }
        }

        public object VBE
        {
            get { return InternalVBE; }
        }

        public bool Visible
        {
            get { return InternalVisible; }
            set { InternalVisible = value; }
        }

        public int Width
        {
            get { return InternalWidth; }
            set { InternalWidth = value; }
        }

        #endregion

        #region Public static constructors
        public static InvApplication ByInvApplication(InvApplication invApplication)
        {
            return invApplication == null ? null : new InvApplication(invApplication);
        }

        [SupressImportIntoVM]
        public static InvApplication ByInvApplication(Inventor.Application invApplication)
        {
            return invApplication == null ? null : new InvApplication(invApplication);
        }
        #endregion

        #region Public methods
        public void ConstructInternalNameAndRevisionId(string internalNameToken, string revisionIdToken, out string internalName, out string revisionId)
        {
            InternalConstructInternalNameAndRevisionId(internalNameToken, revisionIdToken, out internalName, out revisionId);
        }

        public void CreateInternalName(string name, string number, string custom, out string internalName)
        {
            InternalCreateInternalName(name, number, custom, out internalName);
        }

        public void ExportApplicationOptions(string fullFileName)
        {
            InternalExportApplicationOptions(fullFileName);
        }

        public void GetAppFrameExtents(out int top, out int left, out int height, out int width)
        {
            InternalGetAppFrameExtents(out top, out left, out height, out width);
        }

        public object GetInterfaceObject(string progIDorCLSID)
        {
            return InternalGetInterfaceObject(progIDorCLSID);
        }

        public object GetInterfaceObject32(string progIDorCLSID)
        {
            return InternalGetInterfaceObject32(progIDorCLSID);
        }

        public void GetMDIClientAreaExtents(out int top, out int left, out int height, out int width)
        {
            InternalGetMDIClientAreaExtents(out top, out left, out height, out width);
        }

        public string GetMaterialXFromAsset(InvAsset asset, object converterOptions)
        {
            return InternalGetMaterialXFromAsset(asset, converterOptions);
        }

        public void ImportApplicationOptions(string fullFileName)
        {
            InternalImportApplicationOptions(fullFileName);
        }

        public string LicenseChallenge()
        {
            return InternalLicenseChallenge();
        }

        public void LicenseResponse(string response)
        {
            InternalLicenseResponse(response);
        }

        public void LoadRealDWGInfrastructure()
        {
            InternalLoadRealDWGInfrastructure();
        }

        public bool Login()
        {
            return InternalLogin();
        }

        public void Move(ref int top, ref int left, ref int height, ref int width)
        {
            InternalMove(ref top, ref left, ref height, ref width);
        }

        public void Quit()
        {
            InternalQuit();
        }

        public void RefreshRibbonForComparison()
        {
            InternalRefreshRibbonForComparison();
        }

        public void ReserveLicense(string clientId)
        {
            InternalReserveLicense(clientId);
        }

        public void ShowMyHomeWindow(object contentTypeOrURL)
        {
            InternalShowMyHomeWindow(contentTypeOrURL);
        }

        public void UnreserveLicense(string clientId)
        {
            InternalUnreserveLicense(clientId);
        }

        public void UseAutoCADRelatedSettings()
        {
            InternalUseAutoCADRelatedSettings();
        }

        public void UseInventorSettings()
        {
            InternalUseInventorSettings();
        }

        public void WriteCIPWaypoint(string waypointData)
        {
            InternalWriteCIPWaypoint(waypointData);
        }

        #endregion
    }
}
