// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.AssetsEnumerator. Do not edit; put additions in InvAssetsEnumerator.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvAssetsEnumerator
    {
        #region Internal properties
        internal Inventor.AssetsEnumerator InternalAssetsEnumerator { get; set; }

        internal object InternalApplication
        {
            get { return AssetsEnumeratorInstance.Application; }
        }

        internal int InternalCount
        {
            get { return AssetsEnumeratorInstance.Count; }
        }

        internal InvAsset InternalItem(object index)
        {
            return InvAsset.ByInvAsset(AssetsEnumeratorInstance[index]);
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)AssetsEnumeratorInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvAssetsEnumerator(InvAssetsEnumerator invAssetsEnumerator)
        {
            InternalAssetsEnumerator = invAssetsEnumerator.InternalAssetsEnumerator;
        }

        private InvAssetsEnumerator(Inventor.AssetsEnumerator invAssetsEnumerator)
        {
            InternalAssetsEnumerator = invAssetsEnumerator;
        }
        #endregion

        #region Private methods
        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.AssetsEnumerator AssetsEnumeratorInstance
        {
            get { return InternalAssetsEnumerator; }
            set { InternalAssetsEnumerator = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvAsset Item(object index)
        {
            return InternalItem(index);
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvAssetsEnumerator ByInvAssetsEnumerator(InvAssetsEnumerator invAssetsEnumerator)
        {
            return invAssetsEnumerator == null ? null : new InvAssetsEnumerator(invAssetsEnumerator);
        }

        [SupressImportIntoVM]
        public static InvAssetsEnumerator ByInvAssetsEnumerator(Inventor.AssetsEnumerator invAssetsEnumerator)
        {
            return invAssetsEnumerator == null ? null : new InvAssetsEnumerator(invAssetsEnumerator);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
