// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.AssemblyComponentDefinition. Do not edit; put additions in InvAssemblyComponentDefinition.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvAssemblyComponentDefinition
    {
        #region Internal properties
        internal Inventor.AssemblyComponentDefinition InternalAssemblyComponentDefinition { get; set; }

        internal InvComponentOccurrence InternalActiveOccurrence
        {
            get { return InvComponentOccurrence.ByInvComponentOccurrence(AssemblyComponentDefinitionInstance.ActiveOccurrence); }
        }

        internal string InternalActivePositionalState
        {
            get { return AssemblyComponentDefinitionInstance.ActivePositionalState; }
            set { AssemblyComponentDefinitionInstance.ActivePositionalState = value; }
        }

        internal InvObjectsEnumerator InternalAppearanceOverridesObjects
        {
            get { return InvObjectsEnumerator.ByInvObjectsEnumerator(AssemblyComponentDefinitionInstance.AppearanceOverridesObjects); }
        }

        internal object InternalApplication
        {
            get { return AssemblyComponentDefinitionInstance.Application; }
        }

        // skipped: AssemblyEvents: Inventor.AssemblyEvents is not wrapped
        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(AssemblyComponentDefinitionInstance.AttributeSets); }
        }

        // skipped: BIMComponent: Inventor.BIMComponent is not wrapped
        // skipped: BOM: Inventor.BOM is not wrapped
        // skipped: BOMQuantity: Inventor.BOMQuantity is not wrapped
        internal InvBOMStructureEnum InternalBOMStructure
        {
            get { return (InvBOMStructureEnum)AssemblyComponentDefinitionInstance.BOMStructure; }
            set { AssemblyComponentDefinitionInstance.BOMStructure = (Inventor.BOMStructureEnum)value; }
        }

        // skipped: ClientGraphicsCollection: Inventor.ClientGraphicsCollection is not wrapped
        // skipped: Constraints: Inventor.AssemblyConstraints is not wrapped
        // skipped: DataIO: Inventor.DataIO is not wrapped
        internal InvMaterial InternalDefaultMaterial
        {
            get { return InvMaterial.ByInvMaterial(AssemblyComponentDefinitionInstance.DefaultMaterial); }
            set { AssemblyComponentDefinitionInstance.DefaultMaterial = value?.MaterialInstance; }
        }

        internal InvAsset InternalDefaultVirtualComponentMaterial
        {
            get { return InvAsset.ByInvAsset(AssemblyComponentDefinitionInstance.DefaultVirtualComponentMaterial); }
            set { AssemblyComponentDefinitionInstance.DefaultVirtualComponentMaterial = value?.AssetInstance; }
        }

        internal object InternalDocument
        {
            get { return AssemblyComponentDefinitionInstance.Document; }
        }

        // skipped: FactoryDocument: Inventor._Document is not wrapped
        // skipped: Features: Inventor.Features is not wrapped
        internal bool InternalHasDesignProblems
        {
            get { return AssemblyComponentDefinitionInstance.HasDesignProblems; }
        }

        // skipped: ImmediateReferencedDefinitions: Inventor.ComponentDefinitionReferences is not wrapped
        // skipped: ImportedComponents: Inventor.ImportedComponents is not wrapped
        internal bool InternalIsContentMember
        {
            get { return AssemblyComponentDefinitionInstance.IsContentMember; }
        }

        internal bool InternalIsModelStateFactory
        {
            get { return AssemblyComponentDefinitionInstance.IsModelStateFactory; }
        }

        internal bool InternalIsModelStateMember
        {
            get { return AssemblyComponentDefinitionInstance.IsModelStateMember; }
        }

        internal bool InternalIsiAssemblyFactory
        {
            get { return AssemblyComponentDefinitionInstance.IsiAssemblyFactory; }
        }

        internal bool InternalIsiAssemblyMember
        {
            get { return AssemblyComponentDefinitionInstance.IsiAssemblyMember; }
        }

        // skipped: Joints: Inventor.AssemblyJoints is not wrapped
        // skipped: MassProperties: Inventor.MassProperties is not wrapped
        internal string InternalMaster
        {
            get { return AssemblyComponentDefinitionInstance.Master; }
        }

        internal bool InternalMasterActive
        {
            get { return AssemblyComponentDefinitionInstance.MasterActive; }
        }

        // skipped: ModelAnnotations: Inventor.ModelAnnotations is not wrapped
        internal string InternalModelGeometryVersion
        {
            get { return AssemblyComponentDefinitionInstance.ModelGeometryVersion; }
        }

        // skipped: ModelStates: Inventor.ModelStates is not wrapped
        // skipped: OccurrencePatterns: Inventor.OccurrencePatterns is not wrapped
        internal InvComponentOccurrences InternalOccurrences
        {
            get { return InvComponentOccurrences.ByInvComponentOccurrences(AssemblyComponentDefinitionInstance.Occurrences); }
        }

        internal InvOrientedBox InternalOrientedMinimumRangeBox
        {
            get { return InvOrientedBox.ByInvOrientedBox(AssemblyComponentDefinitionInstance.OrientedMinimumRangeBox); }
        }

        internal InvParameters InternalParameters
        {
            get { return InvParameters.ByInvParameters(AssemblyComponentDefinitionInstance.Parameters); }
        }

        // skipped: Parent: Inventor._AssemblyDocument is not wrapped
        // skipped: PointClouds: Inventor.PointClouds is not wrapped
        internal InvBox InternalPreciseRangeBox
        {
            get { return InvBox.ByInvBox(AssemblyComponentDefinitionInstance.PreciseRangeBox); }
        }

        internal InvBox InternalRangeBox
        {
            get { return InvBox.ByInvBox(AssemblyComponentDefinitionInstance.RangeBox); }
        }

        // skipped: RepresentationsManager: Inventor.RepresentationsManager is not wrapped
        // skipped: RevitExports: Inventor.RevitExports is not wrapped
        // skipped: SimulationManager: Inventor.SimulationManager is not wrapped
        // skipped: Sketches: Inventor.PlanarSketches is not wrapped
        internal bool InternalSubstituteUpdateModelGeometriesOnly
        {
            get { return AssemblyComponentDefinitionInstance.SubstituteUpdateModelGeometriesOnly; }
            set { AssemblyComponentDefinitionInstance.SubstituteUpdateModelGeometriesOnly = value; }
        }

        internal InvSurfaceBodies InternalSurfaceBodies
        {
            get { return InvSurfaceBodies.ByInvSurfaceBodies(AssemblyComponentDefinitionInstance.SurfaceBodies); }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)AssemblyComponentDefinitionInstance.Type; }
        }

        // skipped: UserCoordinateSystems: Inventor.UserCoordinateSystems is not wrapped
        internal InvWorkAxes InternalWorkAxes
        {
            get { return InvWorkAxes.ByInvWorkAxes(AssemblyComponentDefinitionInstance.WorkAxes); }
        }

        internal InvWorkPlanes InternalWorkPlanes
        {
            get { return InvWorkPlanes.ByInvWorkPlanes(AssemblyComponentDefinitionInstance.WorkPlanes); }
        }

        internal InvWorkPoints InternalWorkPoints
        {
            get { return InvWorkPoints.ByInvWorkPoints(AssemblyComponentDefinitionInstance.WorkPoints); }
        }

        // skipped: WorkPointsEnumerator: Inventor.WorkPointsEnumerator is not wrapped
        // skipped: iAssemblyFactory: Inventor.iAssemblyFactory is not wrapped
        // skipped: iAssemblyMember: Inventor.iAssemblyMember is not wrapped
        // skipped: iMateDefinitions: Inventor.iMateDefinitions is not wrapped
        // skipped: iMateResults: Inventor.iMateResults is not wrapped
        #endregion

        #region Private constructors
        private InvAssemblyComponentDefinition(InvAssemblyComponentDefinition invAssemblyComponentDefinition)
        {
            InternalAssemblyComponentDefinition = invAssemblyComponentDefinition.InternalAssemblyComponentDefinition;
        }

        private InvAssemblyComponentDefinition(Inventor.AssemblyComponentDefinition invAssemblyComponentDefinition)
        {
            InternalAssemblyComponentDefinition = invAssemblyComponentDefinition;
        }
        #endregion

        #region Private methods
        private object InternalAdjustProxyContext(object objectProxy)
        {
            return AssemblyComponentDefinitionInstance.AdjustProxyContext(objectProxy);
        }

        // skipped: AnalyzeInterference(): returns Inventor.InterferenceResults, not wrapped
        private void InternalClearAppearanceOverrides(object appearanceOverrideObjects)
        {
            AssemblyComponentDefinitionInstance.ClearAppearanceOverrides(appearanceOverrideObjects);
        }

        // skipped: CreateFactory(): returns Inventor.iAssemblyFactory, not wrapped
        // skipped: CreateGeometryIntent(): returns Inventor.GeometryIntent, not wrapped
        // skipped: CreateVisibleOccurrenceFinder(): returns Inventor.VisibleOccurrenceFinder, not wrapped
        private void InternalDeleteObjects(InvObjectCollection objects)
        {
            AssemblyComponentDefinitionInstance.DeleteObjects(objects?.ObjectCollectionInstance);
        }

        private void InternalExportObjects(InvObjectCollection objects)
        {
            AssemblyComponentDefinitionInstance.ExportObjects(objects?.ObjectCollectionInstance);
        }

        // skipped: FindUsingPoint(): parameter ObjectTypes is Inventor.SelectionFilterEnum[], not wrapped
        // skipped: FindUsingRay(): parameter FoundEntities is a ref/out Inventor.ObjectsEnumerator
        // skipped: FindUsingVector(): parameter ObjectTypes is Inventor.SelectionFilterEnum[], not wrapped
        private void InternalGetEndOfFeaturesPosition(out object after, out object before)
        {
            AssemblyComponentDefinitionInstance.GetEndOfFeaturesPosition(out after, out before);
        }

        private void InternalGetPositionalStates(ref string[] positionalStates)
        {
            AssemblyComponentDefinitionInstance.GetPositionalStates(ref positionalStates);
        }

        // skipped: GetUnusedGeometries(): parameter UnusedGeometries is a ref/out Inventor.ObjectCollection
        private void InternalHideAllRelationships()
        {
            AssemblyComponentDefinitionInstance.HideAllRelationships();
        }

        private void InternalPurgeUnusedGeometries(object unusedGeometries)
        {
            AssemblyComponentDefinitionInstance.PurgeUnusedGeometries(unusedGeometries);
        }

        private void InternalRepositionObject(object targetObject, bool before, object startObject, object endObject)
        {
            AssemblyComponentDefinitionInstance.RepositionObject(targetObject, before, startObject, endObject);
        }

        // skipped: RigidBodyAnalysis(): returns Inventor.RigidBodyResults, not wrapped
        private void InternalSetEndOfFeaturesToTopOrBottom(bool setToTop)
        {
            AssemblyComponentDefinitionInstance.SetEndOfFeaturesToTopOrBottom(setToTop);
        }

        private void InternalSetOccurrencesProperty(InvObjectCollection pOccurrences, string propertyName, object value)
        {
            AssemblyComponentDefinitionInstance.SetOccurrencesProperty(pOccurrences?.ObjectCollectionInstance, propertyName, value);
        }

        private void InternalSuppressFeatures(InvObjectCollection features)
        {
            AssemblyComponentDefinitionInstance.SuppressFeatures(features?.ObjectCollectionInstance);
        }

        private void InternalTransformOccurrences(InvObjectCollection occurrences, InvObjectCollection transforms, bool ignoreConstraints)
        {
            AssemblyComponentDefinitionInstance.TransformOccurrences(occurrences?.ObjectCollectionInstance, transforms?.ObjectCollectionInstance, ignoreConstraints);
        }

        private void InternalUnsuppressFeatures(InvObjectCollection features)
        {
            AssemblyComponentDefinitionInstance.UnsuppressFeatures(features?.ObjectCollectionInstance);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.AssemblyComponentDefinition AssemblyComponentDefinitionInstance
        {
            get { return InternalAssemblyComponentDefinition; }
            set { InternalAssemblyComponentDefinition = value; }
        }

        public InvComponentOccurrence ActiveOccurrence
        {
            get { return InternalActiveOccurrence; }
        }

        public string ActivePositionalState
        {
            get { return InternalActivePositionalState; }
            set { InternalActivePositionalState = value; }
        }

        public InvObjectsEnumerator AppearanceOverridesObjects
        {
            get { return InternalAppearanceOverridesObjects; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public InvBOMStructureEnum BOMStructure
        {
            get { return InternalBOMStructure; }
            set { InternalBOMStructure = value; }
        }

        public InvMaterial DefaultMaterial
        {
            get { return InternalDefaultMaterial; }
            set { InternalDefaultMaterial = value; }
        }

        public InvAsset DefaultVirtualComponentMaterial
        {
            get { return InternalDefaultVirtualComponentMaterial; }
            set { InternalDefaultVirtualComponentMaterial = value; }
        }

        public object Document
        {
            get { return InternalDocument; }
        }

        public bool HasDesignProblems
        {
            get { return InternalHasDesignProblems; }
        }

        public bool IsContentMember
        {
            get { return InternalIsContentMember; }
        }

        public bool IsModelStateFactory
        {
            get { return InternalIsModelStateFactory; }
        }

        public bool IsModelStateMember
        {
            get { return InternalIsModelStateMember; }
        }

        public bool IsiAssemblyFactory
        {
            get { return InternalIsiAssemblyFactory; }
        }

        public bool IsiAssemblyMember
        {
            get { return InternalIsiAssemblyMember; }
        }

        public string Master
        {
            get { return InternalMaster; }
        }

        public bool MasterActive
        {
            get { return InternalMasterActive; }
        }

        public string ModelGeometryVersion
        {
            get { return InternalModelGeometryVersion; }
        }

        public InvComponentOccurrences Occurrences
        {
            get { return InternalOccurrences; }
        }

        public InvOrientedBox OrientedMinimumRangeBox
        {
            get { return InternalOrientedMinimumRangeBox; }
        }

        public InvParameters Parameters
        {
            get { return InternalParameters; }
        }

        public InvBox PreciseRangeBox
        {
            get { return InternalPreciseRangeBox; }
        }

        public InvBox RangeBox
        {
            get { return InternalRangeBox; }
        }

        public bool SubstituteUpdateModelGeometriesOnly
        {
            get { return InternalSubstituteUpdateModelGeometriesOnly; }
            set { InternalSubstituteUpdateModelGeometriesOnly = value; }
        }

        public InvSurfaceBodies SurfaceBodies
        {
            get { return InternalSurfaceBodies; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public InvWorkAxes WorkAxes
        {
            get { return InternalWorkAxes; }
        }

        public InvWorkPlanes WorkPlanes
        {
            get { return InternalWorkPlanes; }
        }

        public InvWorkPoints WorkPoints
        {
            get { return InternalWorkPoints; }
        }

        #endregion

        #region Public static constructors
        public static InvAssemblyComponentDefinition ByInvAssemblyComponentDefinition(InvAssemblyComponentDefinition invAssemblyComponentDefinition)
        {
            return invAssemblyComponentDefinition == null ? null : new InvAssemblyComponentDefinition(invAssemblyComponentDefinition);
        }

        [SupressImportIntoVM]
        public static InvAssemblyComponentDefinition ByInvAssemblyComponentDefinition(Inventor.AssemblyComponentDefinition invAssemblyComponentDefinition)
        {
            return invAssemblyComponentDefinition == null ? null : new InvAssemblyComponentDefinition(invAssemblyComponentDefinition);
        }
        #endregion

        #region Public methods
        public object AdjustProxyContext(object objectProxy)
        {
            return InternalAdjustProxyContext(objectProxy);
        }

        public void ClearAppearanceOverrides(object appearanceOverrideObjects)
        {
            InternalClearAppearanceOverrides(appearanceOverrideObjects);
        }

        public void DeleteObjects(InvObjectCollection objects)
        {
            InternalDeleteObjects(objects);
        }

        public void ExportObjects(InvObjectCollection objects)
        {
            InternalExportObjects(objects);
        }

        public void GetEndOfFeaturesPosition(out object after, out object before)
        {
            InternalGetEndOfFeaturesPosition(out after, out before);
        }

        public void GetPositionalStates(ref string[] positionalStates)
        {
            InternalGetPositionalStates(ref positionalStates);
        }

        public void HideAllRelationships()
        {
            InternalHideAllRelationships();
        }

        public void PurgeUnusedGeometries(object unusedGeometries)
        {
            InternalPurgeUnusedGeometries(unusedGeometries);
        }

        public void RepositionObject(object targetObject, bool before, object startObject, object endObject)
        {
            InternalRepositionObject(targetObject, before, startObject, endObject);
        }

        public void SetEndOfFeaturesToTopOrBottom(bool setToTop)
        {
            InternalSetEndOfFeaturesToTopOrBottom(setToTop);
        }

        public void SetOccurrencesProperty(InvObjectCollection pOccurrences, string propertyName, object value)
        {
            InternalSetOccurrencesProperty(pOccurrences, propertyName, value);
        }

        public void SuppressFeatures(InvObjectCollection features)
        {
            InternalSuppressFeatures(features);
        }

        public void TransformOccurrences(InvObjectCollection occurrences, InvObjectCollection transforms, bool ignoreConstraints)
        {
            InternalTransformOccurrences(occurrences, transforms, ignoreConstraints);
        }

        public void UnsuppressFeatures(InvObjectCollection features)
        {
            InternalUnsuppressFeatures(features);
        }

        #endregion
    }
}
