// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.BOMStructureEnum. Do not edit; put additions in InvBOMStructureEnum.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public enum InvBOMStructureEnum
    {
        kDefaultBOMStructure = Inventor.BOMStructureEnum.kDefaultBOMStructure,
        kInseparableBOMStructure = Inventor.BOMStructureEnum.kInseparableBOMStructure,
        kNormalBOMStructure = Inventor.BOMStructureEnum.kNormalBOMStructure,
        kPhantomBOMStructure = Inventor.BOMStructureEnum.kPhantomBOMStructure,
        kPurchasedBOMStructure = Inventor.BOMStructureEnum.kPurchasedBOMStructure,
        kReferenceBOMStructure = Inventor.BOMStructureEnum.kReferenceBOMStructure,
        kVariesBOMStructure = Inventor.BOMStructureEnum.kVariesBOMStructure
    }
}
