// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ComponentOccurrence. Do not edit; put additions in InvComponentOccurrence.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvComponentOccurrence
    {
        #region Internal properties
        internal Inventor.ComponentOccurrence InternalComponentOccurrence { get; set; }

        internal string InternalActiveDesignViewRepresentation
        {
            get { return ComponentOccurrenceInstance.ActiveDesignViewRepresentation; }
        }

        internal string InternalActiveLevelOfDetailRepresentation
        {
            get { return ComponentOccurrenceInstance.ActiveLevelOfDetailRepresentation; }
        }

        internal string InternalActiveModelState
        {
            get { return ComponentOccurrenceInstance.ActiveModelState; }
            set { ComponentOccurrenceInstance.ActiveModelState = value; }
        }

        internal string InternalActivePositionalRepresentation
        {
            get { return ComponentOccurrenceInstance.ActivePositionalRepresentation; }
            set { ComponentOccurrenceInstance.ActivePositionalRepresentation = value; }
        }

        internal string InternalActivePositionalState
        {
            get { return ComponentOccurrenceInstance.ActivePositionalState; }
            set { ComponentOccurrenceInstance.ActivePositionalState = value; }
        }

        internal bool InternalAdaptive
        {
            get { return ComponentOccurrenceInstance.Adaptive; }
            set { ComponentOccurrenceInstance.Adaptive = value; }
        }

        internal InvAsset InternalAppearance
        {
            get { return InvAsset.ByInvAsset(ComponentOccurrenceInstance.Appearance); }
            set { ComponentOccurrenceInstance.Appearance = value?.AssetInstance; }
        }

        // skipped: AppearanceSourceType: Inventor.AppearanceSourceTypeEnum is not wrapped
        internal object InternalApplication
        {
            get { return ComponentOccurrenceInstance.Application; }
        }

        internal string InternalAssociativeForeignFilename
        {
            get { return ComponentOccurrenceInstance.AssociativeForeignFilename; }
        }

        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(ComponentOccurrenceInstance.AttributeSets); }
        }

        internal InvBOMStructureEnum InternalBOMStructure
        {
            get { return (InvBOMStructureEnum)ComponentOccurrenceInstance.BOMStructure; }
            set { ComponentOccurrenceInstance.BOMStructure = (Inventor.BOMStructureEnum)value; }
        }

        // skipped: Constraints: Inventor.AssemblyConstraintsEnumerator is not wrapped
        internal bool InternalContactSet
        {
            get { return ComponentOccurrenceInstance.ContactSet; }
            set { ComponentOccurrenceInstance.ContactSet = value; }
        }

        internal InvComponentDefinition InternalContextDefinition
        {
            get { return InvComponentDefinition.ByInvComponentDefinition(ComponentOccurrenceInstance.ContextDefinition); }
        }

        internal bool InternalCustomAdaptive
        {
            get { return ComponentOccurrenceInstance.CustomAdaptive; }
            set { ComponentOccurrenceInstance.CustomAdaptive = value; }
        }

        internal InvComponentDefinition InternalDefinition
        {
            get { return InvComponentDefinition.ByInvComponentDefinition(ComponentOccurrenceInstance.Definition); }
        }

        internal InvDocumentTypeEnum InternalDefinitionDocumentType
        {
            get { return (InvDocumentTypeEnum)ComponentOccurrenceInstance.DefinitionDocumentType; }
        }

        // skipped: DefinitionReference: Inventor.ComponentDefinitionReference is not wrapped
        internal InvActionTypeEnum InternalDisabledActionTypes
        {
            get { return (InvActionTypeEnum)ComponentOccurrenceInstance.DisabledActionTypes; }
            set { ComponentOccurrenceInstance.DisabledActionTypes = (Inventor.ActionTypeEnum)value; }
        }

        internal bool InternalEdited
        {
            get { return ComponentOccurrenceInstance.Edited; }
        }

        internal bool InternalEnabled
        {
            get { return ComponentOccurrenceInstance.Enabled; }
            set { ComponentOccurrenceInstance.Enabled = value; }
        }

        internal bool InternalExcluded
        {
            get { return ComponentOccurrenceInstance.Excluded; }
            set { ComponentOccurrenceInstance.Excluded = value; }
        }

        internal bool InternalFlexible
        {
            get { return ComponentOccurrenceInstance.Flexible; }
            set { ComponentOccurrenceInstance.Flexible = value; }
        }

        internal bool InternalGrounded
        {
            get { return ComponentOccurrenceInstance.Grounded; }
            set { ComponentOccurrenceInstance.Grounded = value; }
        }

        internal bool InternalHasAssociativeImportedComponent
        {
            get { return ComponentOccurrenceInstance.HasAssociativeImportedComponent; }
        }

        internal bool InternalHasBodyOverride
        {
            get { return ComponentOccurrenceInstance.HasBodyOverride; }
        }

        // skipped: ImportedComponent: Inventor.ImportedComponent is not wrapped
        internal object InternalInterchangeableComponents
        {
            get { return ComponentOccurrenceInstance.InterchangeableComponents; }
            set { ComponentOccurrenceInstance.InterchangeableComponents = value; }
        }

        internal bool InternalIsAssociativeToDesignViewRepresentation
        {
            get { return ComponentOccurrenceInstance.IsAssociativeToDesignViewRepresentation; }
            set { ComponentOccurrenceInstance.IsAssociativeToDesignViewRepresentation = value; }
        }

        internal bool InternalIsAssociativelyImported
        {
            get { return ComponentOccurrenceInstance.IsAssociativelyImported; }
        }

        internal bool InternalIsMirrorPatternMirroredOccurrence
        {
            get { return ComponentOccurrenceInstance.IsMirrorPatternMirroredOccurrence; }
        }

        internal bool InternalIsMirrorPatternReusedOccurrence
        {
            get { return ComponentOccurrenceInstance.IsMirrorPatternReusedOccurrence; }
        }

        internal bool InternalIsMirrorPatternSourceOccurrence
        {
            get { return ComponentOccurrenceInstance.IsMirrorPatternSourceOccurrence; }
        }

        internal bool InternalIsMirrorPatternTargetOccurrence
        {
            get { return ComponentOccurrenceInstance.IsMirrorPatternTargetOccurrence; }
        }

        internal bool InternalIsPatternElement
        {
            get { return ComponentOccurrenceInstance.IsPatternElement; }
        }

        internal bool InternalIsSubstituteOccurrence
        {
            get { return ComponentOccurrenceInstance.IsSubstituteOccurrence; }
        }

        internal bool InternalIsiAssemblyMember
        {
            get { return ComponentOccurrenceInstance.IsiAssemblyMember; }
        }

        internal bool InternalIsiPartMember
        {
            get { return ComponentOccurrenceInstance.IsiPartMember; }
        }

        // skipped: Joints: Inventor.AssemblyJointsEnumerator is not wrapped
        internal bool InternalLocalAdaptive
        {
            get { return ComponentOccurrenceInstance.LocalAdaptive; }
            set { ComponentOccurrenceInstance.LocalAdaptive = value; }
        }

        // skipped: MassProperties: Inventor.MassProperties is not wrapped
        internal string InternalName
        {
            get { return ComponentOccurrenceInstance.Name; }
            set { ComponentOccurrenceInstance.Name = value; }
        }

        internal InvComponentOccurrencesEnumerator InternalOccurrencePath
        {
            get { return InvComponentOccurrencesEnumerator.ByInvComponentOccurrencesEnumerator(ComponentOccurrenceInstance.OccurrencePath); }
        }

        internal InvPropertySets InternalOccurrencePropertySets
        {
            get { return InvPropertySets.ByInvPropertySets(ComponentOccurrenceInstance.OccurrencePropertySets); }
        }

        internal bool InternalOccurrencePropertySetsEnabled
        {
            get { return ComponentOccurrenceInstance.OccurrencePropertySetsEnabled; }
            set { ComponentOccurrenceInstance.OccurrencePropertySetsEnabled = value; }
        }

        internal InvOrientedBox InternalOrientedMinimumRangeBox
        {
            get { return InvOrientedBox.ByInvOrientedBox(ComponentOccurrenceInstance.OrientedMinimumRangeBox); }
        }

        internal double InternalOverrideOpacity
        {
            get { return ComponentOccurrenceInstance.OverrideOpacity; }
            set { ComponentOccurrenceInstance.OverrideOpacity = value; }
        }

        internal InvAssemblyComponentDefinition InternalParent
        {
            get { return InvAssemblyComponentDefinition.ByInvAssemblyComponentDefinition(ComponentOccurrenceInstance.Parent); }
        }

        internal InvComponentOccurrence InternalParentOccurrence
        {
            get { return InvComponentOccurrence.ByInvComponentOccurrence(ComponentOccurrenceInstance.ParentOccurrence); }
        }

        // skipped: PatternElement: Inventor.OccurrencePatternElement is not wrapped
        internal InvBox InternalPreciseRangeBox
        {
            get { return InvBox.ByInvBox(ComponentOccurrenceInstance.PreciseRangeBox); }
        }

        internal InvBox InternalRangeBox
        {
            get { return InvBox.ByInvBox(ComponentOccurrenceInstance.RangeBox); }
        }

        internal bool InternalReference
        {
            get { return ComponentOccurrenceInstance.Reference; }
            set { ComponentOccurrenceInstance.Reference = value; }
        }

        // skipped: ReferencedDocumentDescriptor: Inventor.DocumentDescriptor is not wrapped
        // skipped: ReferencedFileDescriptor: Inventor.ReferencedFileDescriptor is not wrapped
        internal InvRenderStyle InternalRenderStyle
        {
            get { return InvRenderStyle.ByInvRenderStyle(ComponentOccurrenceInstance.RenderStyle); }
            set { ComponentOccurrenceInstance.RenderStyle = value?.RenderStyleInstance; }
        }

        internal bool InternalShowDegreesOfFreedom
        {
            get { return ComponentOccurrenceInstance.ShowDegreesOfFreedom; }
            set { ComponentOccurrenceInstance.ShowDegreesOfFreedom = value; }
        }

        internal InvComponentOccurrencesEnumerator InternalSubOccurrences
        {
            get { return InvComponentOccurrencesEnumerator.ByInvComponentOccurrencesEnumerator(ComponentOccurrenceInstance.SubOccurrences); }
        }

        internal bool InternalSuppressed
        {
            get { return ComponentOccurrenceInstance.Suppressed; }
        }

        internal InvSurfaceBodies InternalSurfaceBodies
        {
            get { return InvSurfaceBodies.ByInvSurfaceBodies(ComponentOccurrenceInstance.SurfaceBodies); }
        }

        internal InvMatrix InternalTransformation
        {
            get { return InvMatrix.ByInvMatrix(ComponentOccurrenceInstance.Transformation); }
            set { ComponentOccurrenceInstance.Transformation = value?.MatrixInstance; }
        }

        internal bool InternalTransparent
        {
            get { return ComponentOccurrenceInstance.Transparent; }
            set { ComponentOccurrenceInstance.Transparent = value; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ComponentOccurrenceInstance.Type; }
        }

        internal bool InternalVisible
        {
            get { return ComponentOccurrenceInstance.Visible; }
            set { ComponentOccurrenceInstance.Visible = value; }
        }

        // skipped: iMateDefinitions: Inventor.iMateDefinitionsEnumerator is not wrapped
        #endregion

        #region Private constructors
        private InvComponentOccurrence(InvComponentOccurrence invComponentOccurrence)
        {
            InternalComponentOccurrence = invComponentOccurrence.InternalComponentOccurrence;
        }

        private InvComponentOccurrence(Inventor.ComponentOccurrence invComponentOccurrence)
        {
            InternalComponentOccurrence = invComponentOccurrence;
        }
        #endregion

        #region Private methods
        private void InternalChangeRowOfiAssemblyMember(object newRow, object options)
        {
            ComponentOccurrenceInstance.ChangeRowOfiAssemblyMember(newRow, options);
        }

        private void InternalChangeRowOfiPartMember(object newRow, object customInput)
        {
            ComponentOccurrenceInstance.ChangeRowOfiPartMember(newRow, customInput);
        }

        private void InternalCreateGeometryProxy(object geometry, out object result)
        {
            ComponentOccurrenceInstance.CreateGeometryProxy(geometry, out result);
        }

        private void InternalDelete()
        {
            ComponentOccurrenceInstance.Delete();
        }

        private void InternalDelete2(bool skipDocumentSave)
        {
            ComponentOccurrenceInstance.Delete2(skipDocumentSave);
        }

        private void InternalEdit()
        {
            ComponentOccurrenceInstance.Edit();
        }

        // skipped: ExitEdit(): parameter ExitTo is Inventor.ExitTypeEnum, not wrapped
        // skipped: GetDegreesOfFreedom(): parameter TranslationDegreesVectors is a ref/out Inventor.ObjectsEnumerator
        // skipped: GetDisplayMode(): returns Inventor.DisplayModeEnum, not wrapped
        private void InternalGetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            ComponentOccurrenceInstance.GetReferenceKey(ref referenceKey, keyContext);
        }

        // skipped: GetRenderStyle(): parameter StyleSourceType is Inventor.StyleSourceTypeEnum, not wrapped
        private void InternalReplace(string fileName, bool replaceAll)
        {
            ComponentOccurrenceInstance.Replace(fileName, replaceAll);
        }

        private void InternalReplace2(string fileName, bool replaceAll, object saveEdits, object keepAdaptivity)
        {
            ComponentOccurrenceInstance.Replace2(fileName, replaceAll, saveEdits, keepAdaptivity);
        }

        private void InternalSetDesignViewRepresentation(string representation, string reserved, bool associative)
        {
            ComponentOccurrenceInstance.SetDesignViewRepresentation(representation, reserved, associative);
        }

        // skipped: SetDisplayMode(): parameter DisplayModeSourceType is Inventor.DisplayModeSourceTypeEnum, not wrapped
        private void InternalSetLevelOfDetailRepresentation(string representation, bool skipDocumentSave)
        {
            ComponentOccurrenceInstance.SetLevelOfDetailRepresentation(representation, skipDocumentSave);
        }

        // skipped: SetRenderStyle(): parameter StyleSourceType is Inventor.StyleSourceTypeEnum, not wrapped
        private void InternalSetTransformWithoutConstraints(InvMatrix matrix)
        {
            ComponentOccurrenceInstance.SetTransformWithoutConstraints(matrix?.MatrixInstance);
        }

        private void InternalShowRelationships()
        {
            ComponentOccurrenceInstance.ShowRelationships();
        }

        private void InternalSuppress(bool skipDocumentSave)
        {
            ComponentOccurrenceInstance.Suppress(skipDocumentSave);
        }

        private void InternalUnsuppress()
        {
            ComponentOccurrenceInstance.Unsuppress();
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ComponentOccurrence ComponentOccurrenceInstance
        {
            get { return InternalComponentOccurrence; }
            set { InternalComponentOccurrence = value; }
        }

        public string ActiveDesignViewRepresentation
        {
            get { return InternalActiveDesignViewRepresentation; }
        }

        public string ActiveLevelOfDetailRepresentation
        {
            get { return InternalActiveLevelOfDetailRepresentation; }
        }

        public string ActiveModelState
        {
            get { return InternalActiveModelState; }
            set { InternalActiveModelState = value; }
        }

        public string ActivePositionalRepresentation
        {
            get { return InternalActivePositionalRepresentation; }
            set { InternalActivePositionalRepresentation = value; }
        }

        public string ActivePositionalState
        {
            get { return InternalActivePositionalState; }
            set { InternalActivePositionalState = value; }
        }

        public bool Adaptive
        {
            get { return InternalAdaptive; }
            set { InternalAdaptive = value; }
        }

        public InvAsset Appearance
        {
            get { return InternalAppearance; }
            set { InternalAppearance = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public string AssociativeForeignFilename
        {
            get { return InternalAssociativeForeignFilename; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public InvBOMStructureEnum BOMStructure
        {
            get { return InternalBOMStructure; }
            set { InternalBOMStructure = value; }
        }

        public bool ContactSet
        {
            get { return InternalContactSet; }
            set { InternalContactSet = value; }
        }

        public InvComponentDefinition ContextDefinition
        {
            get { return InternalContextDefinition; }
        }

        public bool CustomAdaptive
        {
            get { return InternalCustomAdaptive; }
            set { InternalCustomAdaptive = value; }
        }

        public InvComponentDefinition Definition
        {
            get { return InternalDefinition; }
        }

        public InvDocumentTypeEnum DefinitionDocumentType
        {
            get { return InternalDefinitionDocumentType; }
        }

        public InvActionTypeEnum DisabledActionTypes
        {
            get { return InternalDisabledActionTypes; }
            set { InternalDisabledActionTypes = value; }
        }

        public bool Edited
        {
            get { return InternalEdited; }
        }

        public bool Enabled
        {
            get { return InternalEnabled; }
            set { InternalEnabled = value; }
        }

        public bool Excluded
        {
            get { return InternalExcluded; }
            set { InternalExcluded = value; }
        }

        public bool Flexible
        {
            get { return InternalFlexible; }
            set { InternalFlexible = value; }
        }

        public bool Grounded
        {
            get { return InternalGrounded; }
            set { InternalGrounded = value; }
        }

        public bool HasAssociativeImportedComponent
        {
            get { return InternalHasAssociativeImportedComponent; }
        }

        public bool HasBodyOverride
        {
            get { return InternalHasBodyOverride; }
        }

        public object InterchangeableComponents
        {
            get { return InternalInterchangeableComponents; }
            set { InternalInterchangeableComponents = value; }
        }

        public bool IsAssociativeToDesignViewRepresentation
        {
            get { return InternalIsAssociativeToDesignViewRepresentation; }
            set { InternalIsAssociativeToDesignViewRepresentation = value; }
        }

        public bool IsAssociativelyImported
        {
            get { return InternalIsAssociativelyImported; }
        }

        public bool IsMirrorPatternMirroredOccurrence
        {
            get { return InternalIsMirrorPatternMirroredOccurrence; }
        }

        public bool IsMirrorPatternReusedOccurrence
        {
            get { return InternalIsMirrorPatternReusedOccurrence; }
        }

        public bool IsMirrorPatternSourceOccurrence
        {
            get { return InternalIsMirrorPatternSourceOccurrence; }
        }

        public bool IsMirrorPatternTargetOccurrence
        {
            get { return InternalIsMirrorPatternTargetOccurrence; }
        }

        public bool IsPatternElement
        {
            get { return InternalIsPatternElement; }
        }

        public bool IsSubstituteOccurrence
        {
            get { return InternalIsSubstituteOccurrence; }
        }

        public bool IsiAssemblyMember
        {
            get { return InternalIsiAssemblyMember; }
        }

        public bool IsiPartMember
        {
            get { return InternalIsiPartMember; }
        }

        public bool LocalAdaptive
        {
            get { return InternalLocalAdaptive; }
            set { InternalLocalAdaptive = value; }
        }

        public string Name
        {
            get { return InternalName; }
            set { InternalName = value; }
        }

        public InvComponentOccurrencesEnumerator OccurrencePath
        {
            get { return InternalOccurrencePath; }
        }

        public InvPropertySets OccurrencePropertySets
        {
            get { return InternalOccurrencePropertySets; }
        }

        public bool OccurrencePropertySetsEnabled
        {
            get { return InternalOccurrencePropertySetsEnabled; }
            set { InternalOccurrencePropertySetsEnabled = value; }
        }

        public InvOrientedBox OrientedMinimumRangeBox
        {
            get { return InternalOrientedMinimumRangeBox; }
        }

        public double OverrideOpacity
        {
            get { return InternalOverrideOpacity; }
            set { InternalOverrideOpacity = value; }
        }

        public InvAssemblyComponentDefinition Parent
        {
            get { return InternalParent; }
        }

        public InvComponentOccurrence ParentOccurrence
        {
            get { return InternalParentOccurrence; }
        }

        public InvBox PreciseRangeBox
        {
            get { return InternalPreciseRangeBox; }
        }

        public InvBox RangeBox
        {
            get { return InternalRangeBox; }
        }

        public bool Reference
        {
            get { return InternalReference; }
            set { InternalReference = value; }
        }

        public InvRenderStyle RenderStyle
        {
            get { return InternalRenderStyle; }
            set { InternalRenderStyle = value; }
        }

        public bool ShowDegreesOfFreedom
        {
            get { return InternalShowDegreesOfFreedom; }
            set { InternalShowDegreesOfFreedom = value; }
        }

        public InvComponentOccurrencesEnumerator SubOccurrences
        {
            get { return InternalSubOccurrences; }
        }

        public bool Suppressed
        {
            get { return InternalSuppressed; }
        }

        public InvSurfaceBodies SurfaceBodies
        {
            get { return InternalSurfaceBodies; }
        }

        public InvMatrix Transformation
        {
            get { return InternalTransformation; }
            set { InternalTransformation = value; }
        }

        public bool Transparent
        {
            get { return InternalTransparent; }
            set { InternalTransparent = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public bool Visible
        {
            get { return InternalVisible; }
            set { InternalVisible = value; }
        }

        #endregion

        #region Public static constructors
        public static InvComponentOccurrence ByInvComponentOccurrence(InvComponentOccurrence invComponentOccurrence)
        {
            return invComponentOccurrence == null ? null : new InvComponentOccurrence(invComponentOccurrence);
        }

        [SupressImportIntoVM]
        public static InvComponentOccurrence ByInvComponentOccurrence(Inventor.ComponentOccurrence invComponentOccurrence)
        {
            return invComponentOccurrence == null ? null : new InvComponentOccurrence(invComponentOccurrence);
        }
        #endregion

        #region Public methods
        public void ChangeRowOfiAssemblyMember(object newRow, object options)
        {
            InternalChangeRowOfiAssemblyMember(newRow, options);
        }

        public void ChangeRowOfiPartMember(object newRow, object customInput)
        {
            InternalChangeRowOfiPartMember(newRow, customInput);
        }

        public void CreateGeometryProxy(object geometry, out object result)
        {
            InternalCreateGeometryProxy(geometry, out result);
        }

        public void Delete()
        {
            InternalDelete();
        }

        public void Delete2(bool skipDocumentSave)
        {
            InternalDelete2(skipDocumentSave);
        }

        public void Edit()
        {
            InternalEdit();
        }

        public void GetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            InternalGetReferenceKey(ref referenceKey, keyContext);
        }

        public void Replace(string fileName, bool replaceAll)
        {
            InternalReplace(fileName, replaceAll);
        }

        public void Replace2(string fileName, bool replaceAll, object saveEdits, object keepAdaptivity)
        {
            InternalReplace2(fileName, replaceAll, saveEdits, keepAdaptivity);
        }

        public void SetDesignViewRepresentation(string representation, string reserved, bool associative)
        {
            InternalSetDesignViewRepresentation(representation, reserved, associative);
        }

        public void SetLevelOfDetailRepresentation(string representation, bool skipDocumentSave)
        {
            InternalSetLevelOfDetailRepresentation(representation, skipDocumentSave);
        }

        public void SetTransformWithoutConstraints(InvMatrix matrix)
        {
            InternalSetTransformWithoutConstraints(matrix);
        }

        public void ShowRelationships()
        {
            InternalShowRelationships();
        }

        public void Suppress(bool skipDocumentSave)
        {
            InternalSuppress(skipDocumentSave);
        }

        public void Unsuppress()
        {
            InternalUnsuppress();
        }

        #endregion
    }
}
