// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ComponentDefinitions. Do not edit; put additions in InvComponentDefinitions.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvComponentDefinitions
    {
        #region Internal properties
        internal Inventor.ComponentDefinitions InternalComponentDefinitions { get; set; }

        internal int InternalCount
        {
            get { return ComponentDefinitionsInstance.Count; }
        }

        internal InvComponentDefinition InternalItem(int index)
        {
            return InvComponentDefinition.ByInvComponentDefinition(ComponentDefinitionsInstance[index]);
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ComponentDefinitionsInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvComponentDefinitions(InvComponentDefinitions invComponentDefinitions)
        {
            InternalComponentDefinitions = invComponentDefinitions.InternalComponentDefinitions;
        }

        private InvComponentDefinitions(Inventor.ComponentDefinitions invComponentDefinitions)
        {
            InternalComponentDefinitions = invComponentDefinitions;
        }
        #endregion

        #region Private methods
        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ComponentDefinitions ComponentDefinitionsInstance
        {
            get { return InternalComponentDefinitions; }
            set { InternalComponentDefinitions = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvComponentDefinition Item(int index)
        {
            return InternalItem(index);
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvComponentDefinitions ByInvComponentDefinitions(InvComponentDefinitions invComponentDefinitions)
        {
            return invComponentDefinitions == null ? null : new InvComponentDefinitions(invComponentDefinitions);
        }

        [SupressImportIntoVM]
        public static InvComponentDefinitions ByInvComponentDefinitions(Inventor.ComponentDefinitions invComponentDefinitions)
        {
            return invComponentDefinitions == null ? null : new InvComponentDefinitions(invComponentDefinitions);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
