// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ComponentDefinition. Do not edit; put additions in InvComponentDefinition.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvComponentDefinition
    {
        #region Internal properties
        internal Inventor.ComponentDefinition InternalComponentDefinition { get; set; }

        internal object InternalApplication
        {
            get { return ComponentDefinitionInstance.Application; }
        }

        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(ComponentDefinitionInstance.AttributeSets); }
        }

        // skipped: BOMQuantity: Inventor.BOMQuantity is not wrapped
        internal InvBOMStructureEnum InternalBOMStructure
        {
            get { return (InvBOMStructureEnum)ComponentDefinitionInstance.BOMStructure; }
            set { ComponentDefinitionInstance.BOMStructure = (Inventor.BOMStructureEnum)value; }
        }

        // skipped: ClientGraphicsCollection: Inventor.ClientGraphicsCollection is not wrapped
        // skipped: DataIO: Inventor.DataIO is not wrapped
        internal object InternalDocument
        {
            get { return ComponentDefinitionInstance.Document; }
        }

        internal bool InternalHasDesignProblems
        {
            get { return ComponentDefinitionInstance.HasDesignProblems; }
        }

        // skipped: ImmediateReferencedDefinitions: Inventor.ComponentDefinitionReferences is not wrapped
        internal string InternalModelGeometryVersion
        {
            get { return ComponentDefinitionInstance.ModelGeometryVersion; }
        }

        internal InvComponentOccurrences InternalOccurrences
        {
            get { return InvComponentOccurrences.ByInvComponentOccurrences(ComponentDefinitionInstance.Occurrences); }
        }

        internal InvOrientedBox InternalOrientedMinimumRangeBox
        {
            get { return InvOrientedBox.ByInvOrientedBox(ComponentDefinitionInstance.OrientedMinimumRangeBox); }
        }

        internal InvBox InternalPreciseRangeBox
        {
            get { return InvBox.ByInvBox(ComponentDefinitionInstance.PreciseRangeBox); }
        }

        internal InvBox InternalRangeBox
        {
            get { return InvBox.ByInvBox(ComponentDefinitionInstance.RangeBox); }
        }

        internal InvSurfaceBodies InternalSurfaceBodies
        {
            get { return InvSurfaceBodies.ByInvSurfaceBodies(ComponentDefinitionInstance.SurfaceBodies); }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ComponentDefinitionInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvComponentDefinition(InvComponentDefinition invComponentDefinition)
        {
            InternalComponentDefinition = invComponentDefinition.InternalComponentDefinition;
        }

        private InvComponentDefinition(Inventor.ComponentDefinition invComponentDefinition)
        {
            InternalComponentDefinition = invComponentDefinition;
        }
        #endregion

        #region Private methods
        // skipped: FindUsingPoint(): parameter ObjectTypes is Inventor.SelectionFilterEnum[], not wrapped
        // skipped: FindUsingVector(): parameter ObjectTypes is Inventor.SelectionFilterEnum[], not wrapped
        // skipped: GetUnusedGeometries(): parameter UnusedGeometries is a ref/out Inventor.ObjectCollection
        private void InternalPurgeUnusedGeometries(object unusedGeometries)
        {
            ComponentDefinitionInstance.PurgeUnusedGeometries(unusedGeometries);
        }

        private void InternalRepositionObject(object targetObject, bool before, object startObject, object endObject)
        {
            ComponentDefinitionInstance.RepositionObject(targetObject, before, startObject, endObject);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ComponentDefinition ComponentDefinitionInstance
        {
            get { return InternalComponentDefinition; }
            set { InternalComponentDefinition = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public InvBOMStructureEnum BOMStructure
        {
            get { return InternalBOMStructure; }
            set { InternalBOMStructure = value; }
        }

        public object Document
        {
            get { return InternalDocument; }
        }

        public bool HasDesignProblems
        {
            get { return InternalHasDesignProblems; }
        }

        public string ModelGeometryVersion
        {
            get { return InternalModelGeometryVersion; }
        }

        public InvComponentOccurrences Occurrences
        {
            get { return InternalOccurrences; }
        }

        public InvOrientedBox OrientedMinimumRangeBox
        {
            get { return InternalOrientedMinimumRangeBox; }
        }

        public InvBox PreciseRangeBox
        {
            get { return InternalPreciseRangeBox; }
        }

        public InvBox RangeBox
        {
            get { return InternalRangeBox; }
        }

        public InvSurfaceBodies SurfaceBodies
        {
            get { return InternalSurfaceBodies; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvComponentDefinition ByInvComponentDefinition(InvComponentDefinition invComponentDefinition)
        {
            return invComponentDefinition == null ? null : new InvComponentDefinition(invComponentDefinition);
        }

        [SupressImportIntoVM]
        public static InvComponentDefinition ByInvComponentDefinition(Inventor.ComponentDefinition invComponentDefinition)
        {
            return invComponentDefinition == null ? null : new InvComponentDefinition(invComponentDefinition);
        }
        #endregion

        #region Public methods
        public void PurgeUnusedGeometries(object unusedGeometries)
        {
            InternalPurgeUnusedGeometries(unusedGeometries);
        }

        public void RepositionObject(object targetObject, bool before, object startObject, object endObject)
        {
            InternalRepositionObject(targetObject, before, startObject, endObject);
        }

        #endregion
    }
}
