// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.CommandTypesEnum. Do not edit; put additions in InvCommandTypesEnum.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public enum InvCommandTypesEnum
    {
        kEditMaskCmdType = Inventor.CommandTypesEnum.kEditMaskCmdType,
        kFileOperationsCmdType = Inventor.CommandTypesEnum.kFileOperationsCmdType,
        kFilePropertyEditCmdType = Inventor.CommandTypesEnum.kFilePropertyEditCmdType,
        kModelStateSmudgeCmdType = Inventor.CommandTypesEnum.kModelStateSmudgeCmdType,
        kModelStateUpdatesCmdType = Inventor.CommandTypesEnum.kModelStateUpdatesCmdType,
        kNonShapeEditCmdType = Inventor.CommandTypesEnum.kNonShapeEditCmdType,
        kQueryOnlyCmdType = Inventor.CommandTypesEnum.kQueryOnlyCmdType,
        kReferencesChangeCmdType = Inventor.CommandTypesEnum.kReferencesChangeCmdType,
        kSchemaChangeCmdType = Inventor.CommandTypesEnum.kSchemaChangeCmdType,
        kShapeEditCmdType = Inventor.CommandTypesEnum.kShapeEditCmdType,
        kUpdateWithReferencesCmdType = Inventor.CommandTypesEnum.kUpdateWithReferencesCmdType,
        kViewRepSmudgeCmdType = Inventor.CommandTypesEnum.kViewRepSmudgeCmdType
    }
}
