// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.DocumentEvents. Do not edit; put additions in InvDocumentEvents.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvDocumentEvents
    {
        #region Internal properties
        internal Inventor.DocumentEvents InternalDocumentEvents { get; set; }

        #endregion

        #region Private constructors
        private InvDocumentEvents(InvDocumentEvents invDocumentEvents)
        {
            InternalDocumentEvents = invDocumentEvents.InternalDocumentEvents;
        }

        private InvDocumentEvents(Inventor.DocumentEvents invDocumentEvents)
        {
            InternalDocumentEvents = invDocumentEvents;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.DocumentEvents DocumentEventsInstance
        {
            get { return InternalDocumentEvents; }
            set { InternalDocumentEvents = value; }
        }

        #endregion

        #region Public static constructors
        public static InvDocumentEvents ByInvDocumentEvents(InvDocumentEvents invDocumentEvents)
        {
            return invDocumentEvents == null ? null : new InvDocumentEvents(invDocumentEvents);
        }

        [SupressImportIntoVM]
        public static InvDocumentEvents ByInvDocumentEvents(Inventor.DocumentEvents invDocumentEvents)
        {
            return invDocumentEvents == null ? null : new InvDocumentEvents(invDocumentEvents);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
