// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.DisabledCommandList. Do not edit; put additions in InvDisabledCommandList.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvDisabledCommandList
    {
        #region Internal properties
        internal Inventor.DisabledCommandList InternalDisabledCommandList { get; set; }

        internal InvApplication InternalApplication
        {
            get { return InvApplication.ByInvApplication(DisabledCommandListInstance.Application); }
        }

        internal int InternalCount
        {
            get { return DisabledCommandListInstance.Count; }
        }

        // skipped: Item: Inventor.ControlDefinition is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)DisabledCommandListInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvDisabledCommandList(InvDisabledCommandList invDisabledCommandList)
        {
            InternalDisabledCommandList = invDisabledCommandList.InternalDisabledCommandList;
        }

        private InvDisabledCommandList(Inventor.DisabledCommandList invDisabledCommandList)
        {
            InternalDisabledCommandList = invDisabledCommandList;
        }
        #endregion

        #region Private methods
        // skipped: Add(): parameter Command is Inventor.ControlDefinition, not wrapped
        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        private void InternalRemove(int index)
        {
            DisabledCommandListInstance.Remove(index);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.DisabledCommandList DisabledCommandListInstance
        {
            get { return InternalDisabledCommandList; }
            set { InternalDisabledCommandList = value; }
        }

        public InvApplication Application
        {
            get { return InternalApplication; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvDisabledCommandList ByInvDisabledCommandList(InvDisabledCommandList invDisabledCommandList)
        {
            return invDisabledCommandList == null ? null : new InvDisabledCommandList(invDisabledCommandList);
        }

        [SupressImportIntoVM]
        public static InvDisabledCommandList ByInvDisabledCommandList(Inventor.DisabledCommandList invDisabledCommandList)
        {
            return invDisabledCommandList == null ? null : new InvDisabledCommandList(invDisabledCommandList);
        }
        #endregion

        #region Public methods
        public void Remove(int index)
        {
            InternalRemove(index);
        }

        #endregion
    }
}
