// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.DisplaySettings. Do not edit; put additions in InvDisplaySettings.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvDisplaySettings
    {
        #region Internal properties
        internal Inventor.DisplaySettings InternalDisplaySettings { get; set; }

        internal object InternalApplication
        {
            get { return DisplaySettingsInstance.Application; }
        }

        internal bool InternalAreTexturesOn
        {
            get { return DisplaySettingsInstance.AreTexturesOn; }
            set { DisplaySettingsInstance.AreTexturesOn = value; }
        }

        internal bool InternalDepthDimming
        {
            get { return DisplaySettingsInstance.DepthDimming; }
            set { DisplaySettingsInstance.DepthDimming = value; }
        }

        internal bool InternalDisplaySilhouettes
        {
            get { return DisplaySettingsInstance.DisplaySilhouettes; }
            set { DisplaySettingsInstance.DisplaySilhouettes = value; }
        }

        // skipped: EdgeColor: Inventor.Color is not wrapped
        // skipped: GroundPlaneSettings: Inventor.GroundPlaneSettings is not wrapped
        internal int InternalHiddenLineDimmingPercent
        {
            get { return DisplaySettingsInstance.HiddenLineDimmingPercent; }
            set { DisplaySettingsInstance.HiddenLineDimmingPercent = value; }
        }

        // skipped: NewWindowDisplayMode: Inventor.DisplayModeEnum is not wrapped
        // skipped: NewWindowProjectionType: Inventor.ProjectionTypeEnum is not wrapped
        internal bool InternalNewWindowShowAmbientShadows
        {
            get { return DisplaySettingsInstance.NewWindowShowAmbientShadows; }
            set { DisplaySettingsInstance.NewWindowShowAmbientShadows = value; }
        }

        internal bool InternalNewWindowShowGroundPlane
        {
            get { return DisplaySettingsInstance.NewWindowShowGroundPlane; }
            set { DisplaySettingsInstance.NewWindowShowGroundPlane = value; }
        }

        internal bool InternalNewWindowShowGroundReflections
        {
            get { return DisplaySettingsInstance.NewWindowShowGroundReflections; }
            set { DisplaySettingsInstance.NewWindowShowGroundReflections = value; }
        }

        internal bool InternalNewWindowShowGroundShadows
        {
            get { return DisplaySettingsInstance.NewWindowShowGroundShadows; }
            set { DisplaySettingsInstance.NewWindowShowGroundShadows = value; }
        }

        internal bool InternalNewWindowShowObjectShadows
        {
            get { return DisplaySettingsInstance.NewWindowShowObjectShadows; }
            set { DisplaySettingsInstance.NewWindowShowObjectShadows = value; }
        }

        internal object InternalParent
        {
            get { return DisplaySettingsInstance.Parent; }
        }

        // skipped: RayTracingQuality: Inventor.RayTracingQualityEnum is not wrapped
        internal bool InternalSolidLinesForHiddenEdges
        {
            get { return DisplaySettingsInstance.SolidLinesForHiddenEdges; }
            set { DisplaySettingsInstance.SolidLinesForHiddenEdges = value; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)DisplaySettingsInstance.Type; }
        }

        internal bool InternalUseRayTracingForRealisticDisplay
        {
            get { return DisplaySettingsInstance.UseRayTracingForRealisticDisplay; }
            set { DisplaySettingsInstance.UseRayTracingForRealisticDisplay = value; }
        }

        #endregion

        #region Private constructors
        private InvDisplaySettings(InvDisplaySettings invDisplaySettings)
        {
            InternalDisplaySettings = invDisplaySettings.InternalDisplaySettings;
        }

        private InvDisplaySettings(Inventor.DisplaySettings invDisplaySettings)
        {
            InternalDisplaySettings = invDisplaySettings;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.DisplaySettings DisplaySettingsInstance
        {
            get { return InternalDisplaySettings; }
            set { InternalDisplaySettings = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public bool AreTexturesOn
        {
            get { return InternalAreTexturesOn; }
            set { InternalAreTexturesOn = value; }
        }

        public bool DepthDimming
        {
            get { return InternalDepthDimming; }
            set { InternalDepthDimming = value; }
        }

        public bool DisplaySilhouettes
        {
            get { return InternalDisplaySilhouettes; }
            set { InternalDisplaySilhouettes = value; }
        }

        public int HiddenLineDimmingPercent
        {
            get { return InternalHiddenLineDimmingPercent; }
            set { InternalHiddenLineDimmingPercent = value; }
        }

        public bool NewWindowShowAmbientShadows
        {
            get { return InternalNewWindowShowAmbientShadows; }
            set { InternalNewWindowShowAmbientShadows = value; }
        }

        public bool NewWindowShowGroundPlane
        {
            get { return InternalNewWindowShowGroundPlane; }
            set { InternalNewWindowShowGroundPlane = value; }
        }

        public bool NewWindowShowGroundReflections
        {
            get { return InternalNewWindowShowGroundReflections; }
            set { InternalNewWindowShowGroundReflections = value; }
        }

        public bool NewWindowShowGroundShadows
        {
            get { return InternalNewWindowShowGroundShadows; }
            set { InternalNewWindowShowGroundShadows = value; }
        }

        public bool NewWindowShowObjectShadows
        {
            get { return InternalNewWindowShowObjectShadows; }
            set { InternalNewWindowShowObjectShadows = value; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public bool SolidLinesForHiddenEdges
        {
            get { return InternalSolidLinesForHiddenEdges; }
            set { InternalSolidLinesForHiddenEdges = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public bool UseRayTracingForRealisticDisplay
        {
            get { return InternalUseRayTracingForRealisticDisplay; }
            set { InternalUseRayTracingForRealisticDisplay = value; }
        }

        #endregion

        #region Public static constructors
        public static InvDisplaySettings ByInvDisplaySettings(InvDisplaySettings invDisplaySettings)
        {
            return invDisplaySettings == null ? null : new InvDisplaySettings(invDisplaySettings);
        }

        [SupressImportIntoVM]
        public static InvDisplaySettings ByInvDisplaySettings(Inventor.DisplaySettings invDisplaySettings)
        {
            return invDisplaySettings == null ? null : new InvDisplaySettings(invDisplaySettings);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
