// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.DocumentSubType. Do not edit; put additions in InvDocumentSubType.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvDocumentSubType
    {
        #region Internal properties
        internal Inventor.DocumentSubType InternalDocumentSubType { get; set; }

        internal string InternalDocumentSubTypeID
        {
            get { return DocumentSubTypeInstance.DocumentSubTypeID; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)DocumentSubTypeInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvDocumentSubType(InvDocumentSubType invDocumentSubType)
        {
            InternalDocumentSubType = invDocumentSubType.InternalDocumentSubType;
        }

        private InvDocumentSubType(Inventor.DocumentSubType invDocumentSubType)
        {
            InternalDocumentSubType = invDocumentSubType;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.DocumentSubType DocumentSubTypeInstance
        {
            get { return InternalDocumentSubType; }
            set { InternalDocumentSubType = value; }
        }

        public string DocumentSubTypeID
        {
            get { return InternalDocumentSubTypeID; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvDocumentSubType ByInvDocumentSubType(InvDocumentSubType invDocumentSubType)
        {
            return invDocumentSubType == null ? null : new InvDocumentSubType(invDocumentSubType);
        }

        [SupressImportIntoVM]
        public static InvDocumentSubType ByInvDocumentSubType(Inventor.DocumentSubType invDocumentSubType)
        {
            return invDocumentSubType == null ? null : new InvDocumentSubType(invDocumentSubType);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
