// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Documents. Do not edit; put additions in InvDocuments.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvDocuments
    {
        #region Internal properties
        internal Inventor.Documents InternalDocuments { get; set; }

        internal int InternalCount
        {
            get { return DocumentsInstance.Count; }
        }

        // skipped: Item: Inventor._Document is not wrapped
        // skipped: ItemByName: Inventor._Document is not wrapped
        internal int InternalLoadedCount
        {
            get { return DocumentsInstance.LoadedCount; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)DocumentsInstance.Type; }
        }

        internal InvDocumentsEnumerator InternalVisibleDocuments
        {
            get { return InvDocumentsEnumerator.ByInvDocumentsEnumerator(DocumentsInstance.VisibleDocuments); }
        }

        #endregion

        #region Private constructors
        private InvDocuments(InvDocuments invDocuments)
        {
            InternalDocuments = invDocuments.InternalDocuments;
        }

        private InvDocuments(Inventor.Documents invDocuments)
        {
            InternalDocuments = invDocuments;
        }
        #endregion

        #region Private methods
        // skipped: Add(): returns Inventor._Document, not wrapped
        // skipped: AddWithOptions(): returns Inventor._Document, not wrapped
        private void InternalCloseAll(bool unreferencedOnly)
        {
            DocumentsInstance.CloseAll(unreferencedOnly);
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        // skipped: Open(): returns Inventor._Document, not wrapped
        // skipped: OpenWithOptions(): returns Inventor._Document, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Documents DocumentsInstance
        {
            get { return InternalDocuments; }
            set { InternalDocuments = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public int LoadedCount
        {
            get { return InternalLoadedCount; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public InvDocumentsEnumerator VisibleDocuments
        {
            get { return InternalVisibleDocuments; }
        }

        #endregion

        #region Public static constructors
        public static InvDocuments ByInvDocuments(InvDocuments invDocuments)
        {
            return invDocuments == null ? null : new InvDocuments(invDocuments);
        }

        [SupressImportIntoVM]
        public static InvDocuments ByInvDocuments(Inventor.Documents invDocuments)
        {
            return invDocuments == null ? null : new InvDocuments(invDocuments);
        }
        #endregion

        #region Public methods
        public void CloseAll(bool unreferencedOnly)
        {
            InternalCloseAll(unreferencedOnly);
        }

        #endregion
    }
}
