// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.DocumentsEnumerator. Do not edit; put additions in InvDocumentsEnumerator.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvDocumentsEnumerator
    {
        #region Internal properties
        internal Inventor.DocumentsEnumerator InternalDocumentsEnumerator { get; set; }

        internal int InternalCount
        {
            get { return DocumentsEnumeratorInstance.Count; }
        }

        // skipped: Item: Inventor._Document is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)DocumentsEnumeratorInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvDocumentsEnumerator(InvDocumentsEnumerator invDocumentsEnumerator)
        {
            InternalDocumentsEnumerator = invDocumentsEnumerator.InternalDocumentsEnumerator;
        }

        private InvDocumentsEnumerator(Inventor.DocumentsEnumerator invDocumentsEnumerator)
        {
            InternalDocumentsEnumerator = invDocumentsEnumerator;
        }
        #endregion

        #region Private methods
        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.DocumentsEnumerator DocumentsEnumeratorInstance
        {
            get { return InternalDocumentsEnumerator; }
            set { InternalDocumentsEnumerator = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvDocumentsEnumerator ByInvDocumentsEnumerator(InvDocumentsEnumerator invDocumentsEnumerator)
        {
            return invDocumentsEnumerator == null ? null : new InvDocumentsEnumerator(invDocumentsEnumerator);
        }

        [SupressImportIntoVM]
        public static InvDocumentsEnumerator ByInvDocumentsEnumerator(Inventor.DocumentsEnumerator invDocumentsEnumerator)
        {
            return invDocumentsEnumerator == null ? null : new InvDocumentsEnumerator(invDocumentsEnumerator);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
