// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.EnvironmentManager. Do not edit; put additions in InvEnvironmentManager.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvEnvironmentManager
    {
        #region Internal properties
        internal Inventor.EnvironmentManager InternalEnvironmentManager { get; set; }

        internal InvApplication InternalApplication
        {
            get { return InvApplication.ByInvApplication(EnvironmentManagerInstance.Application); }
        }

        internal InvEnvironment InternalBaseEnvironment
        {
            get { return InvEnvironment.ByInvEnvironment(EnvironmentManagerInstance.BaseEnvironment); }
        }

        internal InvEnvironment InternalEditObjectEnvironment
        {
            get { return InvEnvironment.ByInvEnvironment(EnvironmentManagerInstance.EditObjectEnvironment); }
        }

        internal InvEnvironment InternalOverrideEnvironment
        {
            get { return InvEnvironment.ByInvEnvironment(EnvironmentManagerInstance.OverrideEnvironment); }
            set { EnvironmentManagerInstance.OverrideEnvironment = value?.EnvironmentInstance; }
        }

        // skipped: Parent: Inventor._Document is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)EnvironmentManagerInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvEnvironmentManager(InvEnvironmentManager invEnvironmentManager)
        {
            InternalEnvironmentManager = invEnvironmentManager.InternalEnvironmentManager;
        }

        private InvEnvironmentManager(Inventor.EnvironmentManager invEnvironmentManager)
        {
            InternalEnvironmentManager = invEnvironmentManager;
        }
        #endregion

        #region Private methods
        // skipped: GetCurrentEnvironment(): parameter Environment is a ref/out Inventor.Environment
        private void InternalSetCurrentEnvironment(InvEnvironment environment, string editObjectId)
        {
            EnvironmentManagerInstance.SetCurrentEnvironment(environment?.EnvironmentInstance, editObjectId);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.EnvironmentManager EnvironmentManagerInstance
        {
            get { return InternalEnvironmentManager; }
            set { InternalEnvironmentManager = value; }
        }

        public InvApplication Application
        {
            get { return InternalApplication; }
        }

        public InvEnvironment BaseEnvironment
        {
            get { return InternalBaseEnvironment; }
        }

        public InvEnvironment EditObjectEnvironment
        {
            get { return InternalEditObjectEnvironment; }
        }

        public InvEnvironment OverrideEnvironment
        {
            get { return InternalOverrideEnvironment; }
            set { InternalOverrideEnvironment = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvEnvironmentManager ByInvEnvironmentManager(InvEnvironmentManager invEnvironmentManager)
        {
            return invEnvironmentManager == null ? null : new InvEnvironmentManager(invEnvironmentManager);
        }

        [SupressImportIntoVM]
        public static InvEnvironmentManager ByInvEnvironmentManager(Inventor.EnvironmentManager invEnvironmentManager)
        {
            return invEnvironmentManager == null ? null : new InvEnvironmentManager(invEnvironmentManager);
        }
        #endregion

        #region Public methods
        public void SetCurrentEnvironment(InvEnvironment environment, string editObjectId)
        {
            InternalSetCurrentEnvironment(environment, editObjectId);
        }

        #endregion
    }
}
