// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Environment. Do not edit; put additions in InvEnvironment.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvEnvironment
    {
        #region Internal properties
        internal Inventor.Environment InternalEnvironment { get; set; }

        internal object InternalAdditionalVisibleRibbonTabs
        {
            get { return EnvironmentInstance.AdditionalVisibleRibbonTabs; }
            set { EnvironmentInstance.AdditionalVisibleRibbonTabs = value; }
        }

        internal InvApplication InternalApplication
        {
            get { return InvApplication.ByInvApplication(EnvironmentInstance.Application); }
        }

        internal bool InternalBuiltIn
        {
            get { return EnvironmentInstance.BuiltIn; }
        }

        internal string InternalClientId
        {
            get { return EnvironmentInstance.ClientId; }
        }

        // skipped: ContextMenuList: Inventor.CommandBarList is not wrapped
        // skipped: DefaultMenuBar: Inventor.CommandBar is not wrapped
        internal string InternalDefaultRibbonTab
        {
            get { return EnvironmentInstance.DefaultRibbonTab; }
            set { EnvironmentInstance.DefaultRibbonTab = value; }
        }

        // skipped: DefaultToolBar: Inventor.CommandBar is not wrapped
        internal InvDisabledCommandList InternalDisabledCommandList
        {
            get { return InvDisabledCommandList.ByInvDisabledCommandList(EnvironmentInstance.DisabledCommandList); }
        }

        internal InvCommandTypesEnum InternalDisabledCommandTypes
        {
            get { return (InvCommandTypesEnum)EnvironmentInstance.DisabledCommandTypes; }
            set { EnvironmentInstance.DisabledCommandTypes = (Inventor.CommandTypesEnum)value; }
        }

        internal string InternalDisplayName
        {
            get { return EnvironmentInstance.DisplayName; }
            set { EnvironmentInstance.DisplayName = value; }
        }

        internal object InternalEnabledCommandList
        {
            get { return EnvironmentInstance.EnabledCommandList; }
            set { EnvironmentInstance.EnabledCommandList = value; }
        }

        internal string InternalExitDisplayName
        {
            get { return EnvironmentInstance.ExitDisplayName; }
            set { EnvironmentInstance.ExitDisplayName = value; }
        }

        internal bool InternalInheritAllRibbonTabs
        {
            get { return EnvironmentInstance.InheritAllRibbonTabs; }
            set { EnvironmentInstance.InheritAllRibbonTabs = value; }
        }

        internal string InternalInternalName
        {
            get { return EnvironmentInstance.InternalName; }
        }

        // skipped: LargeIcon: stdole.IPictureDisp is not wrapped
        // skipped: PanelBar: Inventor.PanelBar is not wrapped
        internal InvApplication InternalParent
        {
            get { return InvApplication.ByInvApplication(EnvironmentInstance.Parent); }
        }

        internal bool InternalPreserveWhenSwitchModelState
        {
            get { return EnvironmentInstance.PreserveWhenSwitchModelState; }
            set { EnvironmentInstance.PreserveWhenSwitchModelState = value; }
        }

        // skipped: RadialMarkingMenus: Inventor.RadialMarkingMenus is not wrapped
        // skipped: Ribbon: Inventor.Ribbon is not wrapped
        // skipped: StandardIcon: stdole.IPictureDisp is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)EnvironmentInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvEnvironment(InvEnvironment invEnvironment)
        {
            InternalEnvironment = invEnvironment.InternalEnvironment;
        }

        private InvEnvironment(Inventor.Environment invEnvironment)
        {
            InternalEnvironment = invEnvironment;
        }
        #endregion

        #region Private methods
        private void InternalDelete()
        {
            EnvironmentInstance.Delete();
        }

        // skipped: GetRadialMarkingMenu(): returns Inventor.RadialMarkingMenu, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Environment EnvironmentInstance
        {
            get { return InternalEnvironment; }
            set { InternalEnvironment = value; }
        }

        public object AdditionalVisibleRibbonTabs
        {
            get { return InternalAdditionalVisibleRibbonTabs; }
            set { InternalAdditionalVisibleRibbonTabs = value; }
        }

        public InvApplication Application
        {
            get { return InternalApplication; }
        }

        public bool BuiltIn
        {
            get { return InternalBuiltIn; }
        }

        public string ClientId
        {
            get { return InternalClientId; }
        }

        public string DefaultRibbonTab
        {
            get { return InternalDefaultRibbonTab; }
            set { InternalDefaultRibbonTab = value; }
        }

        public InvDisabledCommandList DisabledCommandList
        {
            get { return InternalDisabledCommandList; }
        }

        public InvCommandTypesEnum DisabledCommandTypes
        {
            get { return InternalDisabledCommandTypes; }
            set { InternalDisabledCommandTypes = value; }
        }

        public string DisplayName
        {
            get { return InternalDisplayName; }
            set { InternalDisplayName = value; }
        }

        public object EnabledCommandList
        {
            get { return InternalEnabledCommandList; }
            set { InternalEnabledCommandList = value; }
        }

        public string ExitDisplayName
        {
            get { return InternalExitDisplayName; }
            set { InternalExitDisplayName = value; }
        }

        public bool InheritAllRibbonTabs
        {
            get { return InternalInheritAllRibbonTabs; }
            set { InternalInheritAllRibbonTabs = value; }
        }

        public string InternalName
        {
            get { return InternalInternalName; }
        }

        public InvApplication Parent
        {
            get { return InternalParent; }
        }

        public bool PreserveWhenSwitchModelState
        {
            get { return InternalPreserveWhenSwitchModelState; }
            set { InternalPreserveWhenSwitchModelState = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvEnvironment ByInvEnvironment(InvEnvironment invEnvironment)
        {
            return invEnvironment == null ? null : new InvEnvironment(invEnvironment);
        }

        [SupressImportIntoVM]
        public static InvEnvironment ByInvEnvironment(Inventor.Environment invEnvironment)
        {
            return invEnvironment == null ? null : new InvEnvironment(invEnvironment);
        }
        #endregion

        #region Public methods
        public void Delete()
        {
            InternalDelete();
        }

        #endregion
    }
}
