// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Face. Do not edit; put additions in InvFace.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvFace
    {
        #region Internal properties
        internal Inventor.Face InternalFace { get; set; }

        internal InvSurfaceBody InternalAlternateBody(int alternateForm)
        {
            return InvSurfaceBody.ByInvSurfaceBody(FaceInstance.get_AlternateBody(alternateForm));
        }

        internal InvAsset InternalAppearance
        {
            get { return InvAsset.ByInvAsset(FaceInstance.Appearance); }
            set { FaceInstance.Appearance = value?.AssetInstance; }
        }

        // skipped: AppearanceSourceType: Inventor.AppearanceSourceTypeEnum is not wrapped
        internal object InternalApplication
        {
            get { return FaceInstance.Application; }
        }

        internal int InternalAssociativeID
        {
            get { return FaceInstance.AssociativeID; }
            set { FaceInstance.AssociativeID = value; }
        }

        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(FaceInstance.AttributeSets); }
        }

        // skipped: CreatedByFeature: Inventor.PartFeature is not wrapped
        // skipped: EdgeLoops: Inventor.EdgeLoops is not wrapped
        internal InvEdges InternalEdges
        {
            get { return InvEdges.ByInvEdges(FaceInstance.Edges); }
        }

        // skipped: Evaluator: Inventor.SurfaceEvaluator is not wrapped
        // skipped: FaceShell: Inventor.FaceShell is not wrapped
        internal object InternalGeometry
        {
            get { return FaceInstance.Geometry; }
        }

        internal int InternalGeometryForm
        {
            get { return FaceInstance.GeometryForm; }
        }

        internal bool InternalHasReferenceComponent
        {
            get { return FaceInstance.HasReferenceComponent; }
        }

        internal string InternalInternalName
        {
            get { return FaceInstance.InternalName; }
        }

        internal bool InternalIsParamReversed
        {
            get { return FaceInstance.IsParamReversed; }
        }

        internal InvSurfaceBody InternalParent
        {
            get { return InvSurfaceBody.ByInvSurfaceBody(FaceInstance.Parent); }
        }

        internal InvPoint InternalPointOnFace
        {
            get { return InvPoint.ByInvPoint(FaceInstance.PointOnFace); }
        }

        // skipped: ReferenceComponent: Inventor.ReferenceComponent is not wrapped
        internal object InternalReferencedEntity
        {
            get { return FaceInstance.ReferencedEntity; }
        }

        // skipped: indexer Surface: parameter Type is Inventor.SurfaceTypeEnum, not wrapped
        internal InvSurfaceBody InternalSurfaceBody
        {
            get { return InvSurfaceBody.ByInvSurfaceBody(FaceInstance.SurfaceBody); }
        }

        // skipped: SurfaceType: Inventor.SurfaceTypeEnum is not wrapped
        // skipped: TangentiallyConnectedFaces: Inventor.FaceCollection is not wrapped
        // skipped: TextureMaps: Inventor.TextureMaps is not wrapped
        internal InvObjectCollection InternalThreadInfos
        {
            get { return InvObjectCollection.ByInvObjectCollection(FaceInstance.ThreadInfos); }
        }

        internal int InternalTransientKey
        {
            get { return FaceInstance.TransientKey; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)FaceInstance.Type; }
        }

        // skipped: Vertices: Inventor.Vertices is not wrapped
        #endregion

        #region Private constructors
        private InvFace(InvFace invFace)
        {
            InternalFace = invFace.InternalFace;
        }

        private InvFace(Inventor.Face invFace)
        {
            InternalFace = invFace;
        }
        #endregion

        #region Private methods
        private void InternalCalculateFacets(double tolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices)
        {
            FaceInstance.CalculateFacets(tolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices);
        }

        private void InternalCalculateFacetsAndTextureMap(double tolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates)
        {
            FaceInstance.CalculateFacetsAndTextureMap(tolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        private void InternalCalculateFacetsWithOptions(double chordalTolerance, InvNameValueMap options, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out object textureCoordinates)
        {
            FaceInstance.CalculateFacetsWithOptions(chordalTolerance, options?.NameValueMapInstance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        private void InternalCalculateStrokes(double tolerance, out int vertexCount, out int segmentCount, out double[] vertexCoordinates, out int[] vertexIndices)
        {
            FaceInstance.CalculateStrokes(tolerance, out vertexCount, out segmentCount, out vertexCoordinates, out vertexIndices);
        }

        private void InternalCalculateStrokesWithOptions(double chordalTolerance, InvNameValueMap options, out int vertexCount, out double[] vertexCoordinates, out int polylineCount, out int[] polylineLengths)
        {
            FaceInstance.CalculateStrokesWithOptions(chordalTolerance, options?.NameValueMapInstance, out vertexCount, out vertexCoordinates, out polylineCount, out polylineLengths);
        }

        private InvPoint InternalGetClosestPointTo(InvPoint inputPoint)
        {
            return InvPoint.ByInvPoint(FaceInstance.GetClosestPointTo(inputPoint?.PointInstance));
        }

        private void InternalGetExistingFacetTolerances(out int toleranceCount, out double[] existingTolerances)
        {
            FaceInstance.GetExistingFacetTolerances(out toleranceCount, out existingTolerances);
        }

        private void InternalGetExistingFacets(double toleranceIndex, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices)
        {
            FaceInstance.GetExistingFacets(toleranceIndex, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices);
        }

        private void InternalGetExistingFacetsAndTextureMap(double toleranceIndex, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates)
        {
            FaceInstance.GetExistingFacetsAndTextureMap(toleranceIndex, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        private void InternalGetExistingFacetsAndTextureMap2(double chordalTolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates, out int[] indexCountPerFace)
        {
            FaceInstance.GetExistingFacetsAndTextureMap2(chordalTolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates, out indexCountPerFace);
        }

        private void InternalGetExistingStrokeTolerances(out int toleranceCount, out double[] existingTolerances)
        {
            FaceInstance.GetExistingStrokeTolerances(out toleranceCount, out existingTolerances);
        }

        private void InternalGetExistingStrokes(double toleranceIndex, out int vertexCount, out double[] vertexCoordinates, out int polylineCount, out int[] polylineLengths)
        {
            FaceInstance.GetExistingStrokes(toleranceIndex, out vertexCount, out vertexCoordinates, out polylineCount, out polylineLengths);
        }

        private void InternalGetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            FaceInstance.GetReferenceKey(ref referenceKey, keyContext);
        }

        // skipped: GetRenderStyle(): parameter StyleSourceType is Inventor.StyleSourceTypeEnum, not wrapped
        private InvFace InternalGetSourceFace(bool getLeafSource)
        {
            return InvFace.ByInvFace(FaceInstance.GetSourceFace(getLeafSource));
        }

        private void InternalGetTextureScale(out double uScale, out double vScale)
        {
            FaceInstance.GetTextureScale(out uScale, out vScale);
        }

        // skipped: SetRenderStyle(): parameter StyleSourceType is Inventor.StyleSourceTypeEnum, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Face FaceInstance
        {
            get { return InternalFace; }
            set { InternalFace = value; }
        }

        public InvSurfaceBody AlternateBody(int alternateForm)
        {
            return InternalAlternateBody(alternateForm);
        }

        public InvAsset Appearance
        {
            get { return InternalAppearance; }
            set { InternalAppearance = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int AssociativeID
        {
            get { return InternalAssociativeID; }
            set { InternalAssociativeID = value; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public InvEdges Edges
        {
            get { return InternalEdges; }
        }

        public object Geometry
        {
            get { return InternalGeometry; }
        }

        public int GeometryForm
        {
            get { return InternalGeometryForm; }
        }

        public bool HasReferenceComponent
        {
            get { return InternalHasReferenceComponent; }
        }

        public string InternalName
        {
            get { return InternalInternalName; }
        }

        public bool IsParamReversed
        {
            get { return InternalIsParamReversed; }
        }

        public InvSurfaceBody Parent
        {
            get { return InternalParent; }
        }

        public InvPoint PointOnFace
        {
            get { return InternalPointOnFace; }
        }

        public object ReferencedEntity
        {
            get { return InternalReferencedEntity; }
        }

        public InvSurfaceBody SurfaceBody
        {
            get { return InternalSurfaceBody; }
        }

        public InvObjectCollection ThreadInfos
        {
            get { return InternalThreadInfos; }
        }

        public int TransientKey
        {
            get { return InternalTransientKey; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvFace ByInvFace(InvFace invFace)
        {
            return invFace == null ? null : new InvFace(invFace);
        }

        [SupressImportIntoVM]
        public static InvFace ByInvFace(Inventor.Face invFace)
        {
            return invFace == null ? null : new InvFace(invFace);
        }
        #endregion

        #region Public methods
        public void CalculateFacets(double tolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices)
        {
            InternalCalculateFacets(tolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices);
        }

        public void CalculateFacetsAndTextureMap(double tolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates)
        {
            InternalCalculateFacetsAndTextureMap(tolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        public void CalculateFacetsWithOptions(double chordalTolerance, InvNameValueMap options, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out object textureCoordinates)
        {
            InternalCalculateFacetsWithOptions(chordalTolerance, options, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        public void CalculateStrokes(double tolerance, out int vertexCount, out int segmentCount, out double[] vertexCoordinates, out int[] vertexIndices)
        {
            InternalCalculateStrokes(tolerance, out vertexCount, out segmentCount, out vertexCoordinates, out vertexIndices);
        }

        public void CalculateStrokesWithOptions(double chordalTolerance, InvNameValueMap options, out int vertexCount, out double[] vertexCoordinates, out int polylineCount, out int[] polylineLengths)
        {
            InternalCalculateStrokesWithOptions(chordalTolerance, options, out vertexCount, out vertexCoordinates, out polylineCount, out polylineLengths);
        }

        public InvPoint GetClosestPointTo(InvPoint inputPoint)
        {
            return InternalGetClosestPointTo(inputPoint);
        }

        public void GetExistingFacetTolerances(out int toleranceCount, out double[] existingTolerances)
        {
            InternalGetExistingFacetTolerances(out toleranceCount, out existingTolerances);
        }

        public void GetExistingFacets(double toleranceIndex, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices)
        {
            InternalGetExistingFacets(toleranceIndex, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices);
        }

        public void GetExistingFacetsAndTextureMap(double toleranceIndex, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates)
        {
            InternalGetExistingFacetsAndTextureMap(toleranceIndex, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        public void GetExistingFacetsAndTextureMap2(double chordalTolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates, out int[] indexCountPerFace)
        {
            InternalGetExistingFacetsAndTextureMap2(chordalTolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates, out indexCountPerFace);
        }

        public void GetExistingStrokeTolerances(out int toleranceCount, out double[] existingTolerances)
        {
            InternalGetExistingStrokeTolerances(out toleranceCount, out existingTolerances);
        }

        public void GetExistingStrokes(double toleranceIndex, out int vertexCount, out double[] vertexCoordinates, out int polylineCount, out int[] polylineLengths)
        {
            InternalGetExistingStrokes(toleranceIndex, out vertexCount, out vertexCoordinates, out polylineCount, out polylineLengths);
        }

        public void GetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            InternalGetReferenceKey(ref referenceKey, keyContext);
        }

        public InvFace GetSourceFace(bool getLeafSource)
        {
            return InternalGetSourceFace(getLeafSource);
        }

        public void GetTextureScale(out double uScale, out double vScale)
        {
            InternalGetTextureScale(out uScale, out vScale);
        }

        #endregion
    }
}
