// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.FixedWorkPointDef. Do not edit; put additions in InvFixedWorkPointDef.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvFixedWorkPointDef
    {
        #region Internal properties
        internal Inventor.FixedWorkPointDef InternalFixedWorkPointDef { get; set; }

        internal object InternalApplication
        {
            get { return FixedWorkPointDefInstance.Application; }
        }

        internal InvWorkPoint InternalParent
        {
            get { return InvWorkPoint.ByInvWorkPoint(FixedWorkPointDefInstance.Parent); }
        }

        internal InvPoint InternalPoint
        {
            get { return InvPoint.ByInvPoint(FixedWorkPointDefInstance.Point); }
            set { FixedWorkPointDefInstance.Point = value?.PointInstance; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)FixedWorkPointDefInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvFixedWorkPointDef(InvFixedWorkPointDef invFixedWorkPointDef)
        {
            InternalFixedWorkPointDef = invFixedWorkPointDef.InternalFixedWorkPointDef;
        }

        private InvFixedWorkPointDef(Inventor.FixedWorkPointDef invFixedWorkPointDef)
        {
            InternalFixedWorkPointDef = invFixedWorkPointDef;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.FixedWorkPointDef FixedWorkPointDefInstance
        {
            get { return InternalFixedWorkPointDef; }
            set { InternalFixedWorkPointDef = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public InvWorkPoint Parent
        {
            get { return InternalParent; }
        }

        public InvPoint Point
        {
            get { return InternalPoint; }
            set { InternalPoint = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvFixedWorkPointDef ByInvFixedWorkPointDef(InvFixedWorkPointDef invFixedWorkPointDef)
        {
            return invFixedWorkPointDef == null ? null : new InvFixedWorkPointDef(invFixedWorkPointDef);
        }

        [SupressImportIntoVM]
        public static InvFixedWorkPointDef ByInvFixedWorkPointDef(Inventor.FixedWorkPointDef invFixedWorkPointDef)
        {
            return invFixedWorkPointDef == null ? null : new InvFixedWorkPointDef(invFixedWorkPointDef);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
