// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.File. Do not edit; put additions in InvFile.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvFile
    {
        #region Internal properties
        internal Inventor.File InternalFile { get; set; }

        // skipped: AllReferencedFiles: Inventor.FilesEnumerator is not wrapped
        internal object InternalApplication
        {
            get { return FileInstance.Application; }
        }

        internal object InternalAvailableDocuments
        {
            get { return FileInstance.AvailableDocuments; }
        }

        internal string InternalDatabaseRevisionId
        {
            get { return FileInstance.DatabaseRevisionId; }
        }

        internal int InternalFileSaveCounter
        {
            get { return FileInstance.FileSaveCounter; }
        }

        internal string InternalFullFileName
        {
            get { return FileInstance.FullFileName; }
            set { FileInstance.FullFileName = value; }
        }

        internal bool InternalHasLoadedDocuments
        {
            get { return FileInstance.HasLoadedDocuments; }
        }

        internal bool InternalHasReferencingFiles
        {
            get { return FileInstance.HasReferencingFiles; }
        }

        internal string InternalInternalName
        {
            get { return FileInstance.InternalName; }
        }

        internal InvFileOwnershipEnum InternalOwnershipType
        {
            get { return (InvFileOwnershipEnum)FileInstance.OwnershipType; }
        }

        // skipped: ReferencedFileDescriptors: Inventor.FileDescriptorsEnumerator is not wrapped
        // skipped: ReferencedFiles: Inventor.FilesEnumerator is not wrapped
        // skipped: ReferencingFiles: Inventor.FilesEnumerator is not wrapped
        internal string InternalRevisionId
        {
            get { return FileInstance.RevisionId; }
        }

        internal InvSoftwareVersion InternalSoftwareVersionCreated
        {
            get { return InvSoftwareVersion.ByInvSoftwareVersion(FileInstance.SoftwareVersionCreated); }
        }

        internal InvSoftwareVersion InternalSoftwareVersionSaved
        {
            get { return InvSoftwareVersion.ByInvSoftwareVersion(FileInstance.SoftwareVersionSaved); }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)FileInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvFile(InvFile invFile)
        {
            InternalFile = invFile.InternalFile;
        }

        private InvFile(Inventor.File invFile)
        {
            InternalFile = invFile;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.File FileInstance
        {
            get { return InternalFile; }
            set { InternalFile = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public object AvailableDocuments
        {
            get { return InternalAvailableDocuments; }
        }

        public string DatabaseRevisionId
        {
            get { return InternalDatabaseRevisionId; }
        }

        public int FileSaveCounter
        {
            get { return InternalFileSaveCounter; }
        }

        public string FullFileName
        {
            get { return InternalFullFileName; }
            set { InternalFullFileName = value; }
        }

        public bool HasLoadedDocuments
        {
            get { return InternalHasLoadedDocuments; }
        }

        public bool HasReferencingFiles
        {
            get { return InternalHasReferencingFiles; }
        }

        public string InternalName
        {
            get { return InternalInternalName; }
        }

        public InvFileOwnershipEnum OwnershipType
        {
            get { return InternalOwnershipType; }
        }

        public string RevisionId
        {
            get { return InternalRevisionId; }
        }

        public InvSoftwareVersion SoftwareVersionCreated
        {
            get { return InternalSoftwareVersionCreated; }
        }

        public InvSoftwareVersion SoftwareVersionSaved
        {
            get { return InternalSoftwareVersionSaved; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvFile ByInvFile(InvFile invFile)
        {
            return invFile == null ? null : new InvFile(invFile);
        }

        [SupressImportIntoVM]
        public static InvFile ByInvFile(Inventor.File invFile)
        {
            return invFile == null ? null : new InvFile(invFile);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
