// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Faces. Do not edit; put additions in InvFaces.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvFaces
    {
        #region Internal properties
        internal Inventor.Faces InternalFaces { get; set; }

        internal int InternalCount
        {
            get { return FacesInstance.Count; }
        }

        internal InvFace InternalItem(int index)
        {
            return InvFace.ByInvFace(FacesInstance[index]);
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)FacesInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvFaces(InvFaces invFaces)
        {
            InternalFaces = invFaces.InternalFaces;
        }

        private InvFaces(Inventor.Faces invFaces)
        {
            InternalFaces = invFaces;
        }
        #endregion

        #region Private methods
        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Faces FacesInstance
        {
            get { return InternalFaces; }
            set { InternalFaces = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvFace Item(int index)
        {
            return InternalItem(index);
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvFaces ByInvFaces(InvFaces invFaces)
        {
            return invFaces == null ? null : new InvFaces(invFaces);
        }

        [SupressImportIntoVM]
        public static InvFaces ByInvFaces(Inventor.Faces invFaces)
        {
            return invFaces == null ? null : new InvFaces(invFaces);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
