// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.HealthStatusEnum. Do not edit; put additions in InvHealthStatusEnum.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public enum InvHealthStatusEnum
    {
        kBeyondStopNodeHealth = Inventor.HealthStatusEnum.kBeyondStopNodeHealth,
        kCannotComputeHealth = Inventor.HealthStatusEnum.kCannotComputeHealth,
        kDeletedHealth = Inventor.HealthStatusEnum.kDeletedHealth,
        kDriverLostHealth = Inventor.HealthStatusEnum.kDriverLostHealth,
        kInErrorHealth = Inventor.HealthStatusEnum.kInErrorHealth,
        kInconsistentHealth = Inventor.HealthStatusEnum.kInconsistentHealth,
        kInvalidLimitsHealth = Inventor.HealthStatusEnum.kInvalidLimitsHealth,
        kJointDOFLockedHealth = Inventor.HealthStatusEnum.kJointDOFLockedHealth,
        kNewlyAddedHealth = Inventor.HealthStatusEnum.kNewlyAddedHealth,
        kOutOfDateHealth = Inventor.HealthStatusEnum.kOutOfDateHealth,
        kRedundantHealth = Inventor.HealthStatusEnum.kRedundantHealth,
        kSuppressedHealth = Inventor.HealthStatusEnum.kSuppressedHealth,
        kUnknownHealth = Inventor.HealthStatusEnum.kUnknownHealth,
        kUpToDateHealth = Inventor.HealthStatusEnum.kUpToDateHealth
    }
}
