// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.InventorVBAProject. Do not edit; put additions in InvInventorVBAProject.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvInventorVBAProject
    {
        #region Internal properties
        internal Inventor.InventorVBAProject InternalInventorVBAProject { get; set; }

        // skipped: InventorVBAComponents: Inventor.InventorVBAComponents is not wrapped
        internal string InternalName
        {
            get { return InventorVBAProjectInstance.Name; }
            set { InventorVBAProjectInstance.Name = value; }
        }

        internal InvApplication InternalParent
        {
            get { return InvApplication.ByInvApplication(InventorVBAProjectInstance.Parent); }
        }

        // skipped: ProjectType: Inventor.VBAProjectTypeEnum is not wrapped
        internal bool InternalSaved
        {
            get { return InventorVBAProjectInstance.Saved; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)InventorVBAProjectInstance.Type; }
        }

        internal object InternalVBProject
        {
            get { return InventorVBAProjectInstance.VBProject; }
        }

        #endregion

        #region Private constructors
        private InvInventorVBAProject(InvInventorVBAProject invInventorVBAProject)
        {
            InternalInventorVBAProject = invInventorVBAProject.InternalInventorVBAProject;
        }

        private InvInventorVBAProject(Inventor.InventorVBAProject invInventorVBAProject)
        {
            InternalInventorVBAProject = invInventorVBAProject;
        }
        #endregion

        #region Private methods
        private void InternalClose()
        {
            InventorVBAProjectInstance.Close();
        }

        private void InternalSave()
        {
            InventorVBAProjectInstance.Save();
        }

        private void InternalSaveAs(string fullFileName)
        {
            InventorVBAProjectInstance.SaveAs(fullFileName);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.InventorVBAProject InventorVBAProjectInstance
        {
            get { return InternalInventorVBAProject; }
            set { InternalInventorVBAProject = value; }
        }

        public string Name
        {
            get { return InternalName; }
            set { InternalName = value; }
        }

        public InvApplication Parent
        {
            get { return InternalParent; }
        }

        public bool Saved
        {
            get { return InternalSaved; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public object VBProject
        {
            get { return InternalVBProject; }
        }

        #endregion

        #region Public static constructors
        public static InvInventorVBAProject ByInvInventorVBAProject(InvInventorVBAProject invInventorVBAProject)
        {
            return invInventorVBAProject == null ? null : new InvInventorVBAProject(invInventorVBAProject);
        }

        [SupressImportIntoVM]
        public static InvInventorVBAProject ByInvInventorVBAProject(Inventor.InventorVBAProject invInventorVBAProject)
        {
            return invInventorVBAProject == null ? null : new InvInventorVBAProject(invInventorVBAProject);
        }
        #endregion

        #region Public methods
        public void Close()
        {
            InternalClose();
        }

        public void Save()
        {
            InternalSave();
        }

        public void SaveAs(string fullFileName)
        {
            InternalSaveAs(fullFileName);
        }

        #endregion
    }
}
