// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.LightingStyles. Do not edit; put additions in InvLightingStyles.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvLightingStyles
    {
        #region Internal properties
        internal Inventor.LightingStyles InternalLightingStyles { get; set; }

        internal object InternalApplication
        {
            get { return LightingStylesInstance.Application; }
        }

        internal int InternalCount
        {
            get { return LightingStylesInstance.Count; }
        }

        internal InvLightingStyle InternalItem(object index)
        {
            return InvLightingStyle.ByInvLightingStyle(LightingStylesInstance[index]);
        }

        internal object InternalParent
        {
            get { return LightingStylesInstance.Parent; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)LightingStylesInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvLightingStyles(InvLightingStyles invLightingStyles)
        {
            InternalLightingStyles = invLightingStyles.InternalLightingStyles;
        }

        private InvLightingStyles(Inventor.LightingStyles invLightingStyles)
        {
            InternalLightingStyles = invLightingStyles;
        }
        #endregion

        #region Private methods
        private InvLightingStyle InternalAdd(string name)
        {
            return InvLightingStyle.ByInvLightingStyle(LightingStylesInstance.Add(name));
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.LightingStyles LightingStylesInstance
        {
            get { return InternalLightingStyles; }
            set { InternalLightingStyles = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvLightingStyle Item(object index)
        {
            return InternalItem(index);
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvLightingStyles ByInvLightingStyles(InvLightingStyles invLightingStyles)
        {
            return invLightingStyles == null ? null : new InvLightingStyles(invLightingStyles);
        }

        [SupressImportIntoVM]
        public static InvLightingStyles ByInvLightingStyles(Inventor.LightingStyles invLightingStyles)
        {
            return invLightingStyles == null ? null : new InvLightingStyles(invLightingStyles);
        }
        #endregion

        #region Public methods
        public InvLightingStyle Add(string name)
        {
            return InternalAdd(name);
        }

        #endregion
    }
}
