// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Line. Do not edit; put additions in InvLine.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvLine
    {
        #region Internal properties
        internal Inventor.Line InternalLine { get; set; }

        internal InvUnitVector InternalDirection
        {
            get { return InvUnitVector.ByInvUnitVector(LineInstance.Direction); }
            set { LineInstance.Direction = value?.UnitVectorInstance; }
        }

        // skipped: Evaluator: Inventor.CurveEvaluator is not wrapped
        internal bool InternalIsColinearTo(object line, double tolerance)
        {
            return LineInstance.get_IsColinearTo(line, tolerance);
        }

        internal InvPoint InternalRootPoint
        {
            get { return InvPoint.ByInvPoint(LineInstance.RootPoint); }
            set { LineInstance.RootPoint = value?.PointInstance; }
        }

        #endregion

        #region Private constructors
        private InvLine(InvLine invLine)
        {
            InternalLine = invLine.InternalLine;
        }

        private InvLine(Inventor.Line invLine)
        {
            InternalLine = invLine;
        }
        #endregion

        #region Private methods
        private InvLine InternalCopy()
        {
            return InvLine.ByInvLine(LineInstance.Copy());
        }

        private double InternalDistanceTo(InvPoint point)
        {
            return LineInstance.DistanceTo(point?.PointInstance);
        }

        private void InternalGetLineData(ref double[] rootPoint, ref double[] direction)
        {
            LineInstance.GetLineData(ref rootPoint, ref direction);
        }

        private InvObjectsEnumerator InternalIntersectWithCurve(object curve, double tolerance)
        {
            return InvObjectsEnumerator.ByInvObjectsEnumerator(LineInstance.IntersectWithCurve(curve, tolerance));
        }

        private InvObjectsEnumerator InternalIntersectWithSurface(object surface, double tolerance)
        {
            return InvObjectsEnumerator.ByInvObjectsEnumerator(LineInstance.IntersectWithSurface(surface, tolerance));
        }

        private void InternalPutLineData(ref double[] rootPoint, ref double[] direction)
        {
            LineInstance.PutLineData(ref rootPoint, ref direction);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Line LineInstance
        {
            get { return InternalLine; }
            set { InternalLine = value; }
        }

        public InvUnitVector Direction
        {
            get { return InternalDirection; }
            set { InternalDirection = value; }
        }

        public bool IsColinearTo(object line, double tolerance)
        {
            return InternalIsColinearTo(line, tolerance);
        }

        public InvPoint RootPoint
        {
            get { return InternalRootPoint; }
            set { InternalRootPoint = value; }
        }

        #endregion

        #region Public static constructors
        public static InvLine ByInvLine(InvLine invLine)
        {
            return invLine == null ? null : new InvLine(invLine);
        }

        [SupressImportIntoVM]
        public static InvLine ByInvLine(Inventor.Line invLine)
        {
            return invLine == null ? null : new InvLine(invLine);
        }
        #endregion

        #region Public methods
        public InvLine Copy()
        {
            return InternalCopy();
        }

        public double DistanceTo(InvPoint point)
        {
            return InternalDistanceTo(point);
        }

        public void GetLineData(ref double[] rootPoint, ref double[] direction)
        {
            InternalGetLineData(ref rootPoint, ref direction);
        }

        public InvObjectsEnumerator IntersectWithCurve(object curve, double tolerance)
        {
            return InternalIntersectWithCurve(curve, tolerance);
        }

        public InvObjectsEnumerator IntersectWithSurface(object surface, double tolerance)
        {
            return InternalIntersectWithSurface(surface, tolerance);
        }

        public void PutLineData(ref double[] rootPoint, ref double[] direction)
        {
            InternalPutLineData(ref rootPoint, ref direction);
        }

        #endregion
    }
}
