// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.LightingStyle. Do not edit; put additions in InvLightingStyle.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvLightingStyle
    {
        #region Internal properties
        internal Inventor.LightingStyle InternalLightingStyle { get; set; }

        internal double InternalAmbience
        {
            get { return LightingStyleInstance.Ambience; }
            set { LightingStyleInstance.Ambience = value; }
        }

        internal double InternalAmbientShadowIntensity
        {
            get { return LightingStyleInstance.AmbientShadowIntensity; }
            set { LightingStyleInstance.AmbientShadowIntensity = value; }
        }

        internal object InternalApplication
        {
            get { return LightingStyleInstance.Application; }
        }

        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(LightingStyleInstance.AttributeSets); }
        }

        internal double InternalBrightness
        {
            get { return LightingStyleInstance.Brightness; }
            set { LightingStyleInstance.Brightness = value; }
        }

        internal int InternalExposure
        {
            get { return LightingStyleInstance.Exposure; }
            set { LightingStyleInstance.Exposure = value; }
        }

        internal double InternalImageBasedLightingBrightness
        {
            get { return LightingStyleInstance.ImageBasedLightingBrightness; }
            set { LightingStyleInstance.ImageBasedLightingBrightness = value; }
        }

        internal double InternalImageBasedLightingRotation
        {
            get { return LightingStyleInstance.ImageBasedLightingRotation; }
            set { LightingStyleInstance.ImageBasedLightingRotation = value; }
        }

        internal double InternalImageBasedLightingScale
        {
            get { return LightingStyleInstance.ImageBasedLightingScale; }
            set { LightingStyleInstance.ImageBasedLightingScale = value; }
        }

        internal bool InternalImageBasedLightingShowImage
        {
            get { return LightingStyleInstance.ImageBasedLightingShowImage; }
            set { LightingStyleInstance.ImageBasedLightingShowImage = value; }
        }

        internal string InternalImageBasedLightingSourceInternalName
        {
            get { return LightingStyleInstance.ImageBasedLightingSourceInternalName; }
            set { LightingStyleInstance.ImageBasedLightingSourceInternalName = value; }
        }

        internal string InternalImageBasedLightingSourceName
        {
            get { return LightingStyleInstance.ImageBasedLightingSourceName; }
            set { LightingStyleInstance.ImageBasedLightingSourceName = value; }
        }

        internal bool InternalInUse
        {
            get { return LightingStyleInstance.InUse; }
        }

        internal string InternalInternalName
        {
            get { return LightingStyleInstance.InternalName; }
        }

        // skipped: LightingStyleType: Inventor.LightingStyleTypeEnum is not wrapped
        // skipped: Lights: Inventor.Lights is not wrapped
        internal string InternalNameRaw
        {
            get { return LightingStyleInstance.Name; }
            set { LightingStyleInstance.Name = value; }
        }

        internal object InternalParent
        {
            get { return LightingStyleInstance.Parent; }
        }

        internal double InternalShadowDensity
        {
            get { return LightingStyleInstance.ShadowDensity; }
            set { LightingStyleInstance.ShadowDensity = value; }
        }

        // skipped: ShadowDirection: Inventor.ShadowDirectionEnum is not wrapped
        internal double InternalShadowSoftness
        {
            get { return LightingStyleInstance.ShadowSoftness; }
            set { LightingStyleInstance.ShadowSoftness = value; }
        }

        // skipped: StyleLocation: Inventor.StyleLocationEnum is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)LightingStyleInstance.Type; }
        }

        internal bool InternalUpToDate
        {
            get { return LightingStyleInstance.UpToDate; }
        }

        #endregion

        #region Private constructors
        private InvLightingStyle(InvLightingStyle invLightingStyle)
        {
            InternalLightingStyle = invLightingStyle.InternalLightingStyle;
        }

        private InvLightingStyle(Inventor.LightingStyle invLightingStyle)
        {
            InternalLightingStyle = invLightingStyle;
        }
        #endregion

        #region Private methods
        private InvLightingStyle InternalConvertToLocal()
        {
            return InvLightingStyle.ByInvLightingStyle(LightingStyleInstance.ConvertToLocal());
        }

        private InvLightingStyle InternalCopy(string newName)
        {
            return InvLightingStyle.ByInvLightingStyle(LightingStyleInstance.Copy(newName));
        }

        private void InternalDelete()
        {
            LightingStyleInstance.Delete();
        }

        private void InternalGetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            LightingStyleInstance.GetReferenceKey(ref referenceKey, keyContext);
        }

        private void InternalSaveToGlobal()
        {
            LightingStyleInstance.SaveToGlobal();
        }

        private void InternalUpdateFromGlobal()
        {
            LightingStyleInstance.UpdateFromGlobal();
        }

        private void InternalUploadImage(string imageFileName, object envName)
        {
            LightingStyleInstance.UploadImage(imageFileName, envName);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.LightingStyle LightingStyleInstance
        {
            get { return InternalLightingStyle; }
            set { InternalLightingStyle = value; }
        }

        public double Ambience
        {
            get { return InternalAmbience; }
            set { InternalAmbience = value; }
        }

        public double AmbientShadowIntensity
        {
            get { return InternalAmbientShadowIntensity; }
            set { InternalAmbientShadowIntensity = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public double Brightness
        {
            get { return InternalBrightness; }
            set { InternalBrightness = value; }
        }

        public int Exposure
        {
            get { return InternalExposure; }
            set { InternalExposure = value; }
        }

        public double ImageBasedLightingBrightness
        {
            get { return InternalImageBasedLightingBrightness; }
            set { InternalImageBasedLightingBrightness = value; }
        }

        public double ImageBasedLightingRotation
        {
            get { return InternalImageBasedLightingRotation; }
            set { InternalImageBasedLightingRotation = value; }
        }

        public double ImageBasedLightingScale
        {
            get { return InternalImageBasedLightingScale; }
            set { InternalImageBasedLightingScale = value; }
        }

        public bool ImageBasedLightingShowImage
        {
            get { return InternalImageBasedLightingShowImage; }
            set { InternalImageBasedLightingShowImage = value; }
        }

        public string ImageBasedLightingSourceInternalName
        {
            get { return InternalImageBasedLightingSourceInternalName; }
            set { InternalImageBasedLightingSourceInternalName = value; }
        }

        public string ImageBasedLightingSourceName
        {
            get { return InternalImageBasedLightingSourceName; }
            set { InternalImageBasedLightingSourceName = value; }
        }

        public bool InUse
        {
            get { return InternalInUse; }
        }

        public string InternalName
        {
            get { return InternalInternalName; }
        }

        public string Name
        {
            get { return InternalNameRaw; }
            set { InternalNameRaw = value; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public double ShadowDensity
        {
            get { return InternalShadowDensity; }
            set { InternalShadowDensity = value; }
        }

        public double ShadowSoftness
        {
            get { return InternalShadowSoftness; }
            set { InternalShadowSoftness = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public bool UpToDate
        {
            get { return InternalUpToDate; }
        }

        #endregion

        #region Public static constructors
        public static InvLightingStyle ByInvLightingStyle(InvLightingStyle invLightingStyle)
        {
            return invLightingStyle == null ? null : new InvLightingStyle(invLightingStyle);
        }

        [SupressImportIntoVM]
        public static InvLightingStyle ByInvLightingStyle(Inventor.LightingStyle invLightingStyle)
        {
            return invLightingStyle == null ? null : new InvLightingStyle(invLightingStyle);
        }
        #endregion

        #region Public methods
        public InvLightingStyle ConvertToLocal()
        {
            return InternalConvertToLocal();
        }

        public InvLightingStyle Copy(string newName)
        {
            return InternalCopy(newName);
        }

        public void Delete()
        {
            InternalDelete();
        }

        public void GetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            InternalGetReferenceKey(ref referenceKey, keyContext);
        }

        public void SaveToGlobal()
        {
            InternalSaveToGlobal();
        }

        public void UpdateFromGlobal()
        {
            InternalUpdateFromGlobal();
        }

        public void UploadImage(string imageFileName, object envName)
        {
            InternalUploadImage(imageFileName, envName);
        }

        #endregion
    }
}
