// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ModelParameters. Do not edit; put additions in InvModelParameters.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvModelParameters
    {
        #region Internal properties
        internal Inventor.ModelParameters InternalModelParameters { get; set; }

        internal int InternalCount
        {
            get { return ModelParametersInstance.Count; }
        }

        internal InvModelParameter InternalItem(object index)
        {
            return InvModelParameter.ByInvModelParameter(ModelParametersInstance[index]);
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ModelParametersInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvModelParameters(InvModelParameters invModelParameters)
        {
            InternalModelParameters = invModelParameters.InternalModelParameters;
        }

        private InvModelParameters(Inventor.ModelParameters invModelParameters)
        {
            InternalModelParameters = invModelParameters;
        }
        #endregion

        #region Private methods
        private InvModelParameter InternalAddByExpression(string expression, object unitsSpecifier, string name)
        {
            return InvModelParameter.ByInvModelParameter(ModelParametersInstance.AddByExpression(expression, unitsSpecifier, name));
        }

        private InvModelParameter InternalAddByValue(object value, object unitsSpecifier, string name)
        {
            return InvModelParameter.ByInvModelParameter(ModelParametersInstance.AddByValue(value, unitsSpecifier, name));
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ModelParameters ModelParametersInstance
        {
            get { return InternalModelParameters; }
            set { InternalModelParameters = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvModelParameter Item(object index)
        {
            return InternalItem(index);
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvModelParameters ByInvModelParameters(InvModelParameters invModelParameters)
        {
            return invModelParameters == null ? null : new InvModelParameters(invModelParameters);
        }

        [SupressImportIntoVM]
        public static InvModelParameters ByInvModelParameters(Inventor.ModelParameters invModelParameters)
        {
            return invModelParameters == null ? null : new InvModelParameters(invModelParameters);
        }
        #endregion

        #region Public methods
        public InvModelParameter AddByExpression(string expression, object unitsSpecifier, string name)
        {
            return InternalAddByExpression(expression, unitsSpecifier, name);
        }

        public InvModelParameter AddByValue(object value, object unitsSpecifier, string name)
        {
            return InternalAddByValue(value, unitsSpecifier, name);
        }

        #endregion
    }
}
