// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Matrix. Do not edit; put additions in InvMatrix.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvMatrix
    {
        #region Internal properties
        internal Inventor.Matrix InternalMatrix { get; set; }

        internal double InternalCell(int row, int col)
        {
            return MatrixInstance.get_Cell(row, col);
        }

        internal double InternalDeterminant
        {
            get { return MatrixInstance.Determinant; }
        }

        internal InvVector InternalTranslation
        {
            get { return InvVector.ByInvVector(MatrixInstance.Translation); }
        }

        #endregion

        #region Private constructors
        private InvMatrix(InvMatrix invMatrix)
        {
            InternalMatrix = invMatrix.InternalMatrix;
        }

        private InvMatrix(Inventor.Matrix invMatrix)
        {
            InternalMatrix = invMatrix;
        }
        #endregion

        #region Private methods
        private InvMatrix InternalCopy()
        {
            return InvMatrix.ByInvMatrix(MatrixInstance.Copy());
        }

        // skipped: GetCoordinateSystem(): parameter Origin is a ref/out Inventor.Point
        private void InternalGetMatrixData(ref double[] cells)
        {
            MatrixInstance.GetMatrixData(ref cells);
        }

        private void InternalInvert()
        {
            MatrixInstance.Invert();
        }

        private bool InternalIsEqualTo(InvMatrix matrix, double tolerance)
        {
            return MatrixInstance.IsEqualTo(matrix?.MatrixInstance, tolerance);
        }

        private void InternalMultiplyBy(InvMatrix matrix)
        {
            MatrixInstance.MultiplyBy(matrix?.MatrixInstance);
        }

        private void InternalPostMultiplyBy(InvMatrix matrix)
        {
            MatrixInstance.PostMultiplyBy(matrix?.MatrixInstance);
        }

        private void InternalPreMultiplyBy(InvMatrix matrix)
        {
            MatrixInstance.PreMultiplyBy(matrix?.MatrixInstance);
        }

        private void InternalPutMatrixData(ref double[] cells)
        {
            MatrixInstance.PutMatrixData(ref cells);
        }

        private void InternalSetCoordinateSystem(InvPoint origin, InvVector xAxis, InvVector yAxis, InvVector zAxis)
        {
            MatrixInstance.SetCoordinateSystem(origin?.PointInstance, xAxis?.VectorInstance, yAxis?.VectorInstance, zAxis?.VectorInstance);
        }

        private void InternalSetToAlignCoordinateSystems(InvPoint fromOrigin, InvVector fromXAxis, InvVector fromYAxis, InvVector fromZAxis, InvPoint toOrigin, InvVector toXAxis, InvVector toYAxis, InvVector toZAxis)
        {
            MatrixInstance.SetToAlignCoordinateSystems(fromOrigin?.PointInstance, fromXAxis?.VectorInstance, fromYAxis?.VectorInstance, fromZAxis?.VectorInstance, toOrigin?.PointInstance, toXAxis?.VectorInstance, toYAxis?.VectorInstance, toZAxis?.VectorInstance);
        }

        private void InternalSetToIdentity()
        {
            MatrixInstance.SetToIdentity();
        }

        private void InternalSetToRotateTo(InvVector from, InvVector to, InvVector axis)
        {
            MatrixInstance.SetToRotateTo(from?.VectorInstance, to?.VectorInstance, axis?.VectorInstance);
        }

        private void InternalSetToRotation(double angle, InvVector axis, InvPoint center)
        {
            MatrixInstance.SetToRotation(angle, axis?.VectorInstance, center?.PointInstance);
        }

        private void InternalSetTranslation(InvVector translation, bool resetRotation)
        {
            MatrixInstance.SetTranslation(translation?.VectorInstance, resetRotation);
        }

        private void InternalTransformBy(InvMatrix matrix)
        {
            MatrixInstance.TransformBy(matrix?.MatrixInstance);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Matrix MatrixInstance
        {
            get { return InternalMatrix; }
            set { InternalMatrix = value; }
        }

        public double Cell(int row, int col)
        {
            return InternalCell(row, col);
        }

        public double Determinant
        {
            get { return InternalDeterminant; }
        }

        public InvVector Translation
        {
            get { return InternalTranslation; }
        }

        #endregion

        #region Public static constructors
        public static InvMatrix ByInvMatrix(InvMatrix invMatrix)
        {
            return invMatrix == null ? null : new InvMatrix(invMatrix);
        }

        [SupressImportIntoVM]
        public static InvMatrix ByInvMatrix(Inventor.Matrix invMatrix)
        {
            return invMatrix == null ? null : new InvMatrix(invMatrix);
        }
        #endregion

        #region Public methods
        public InvMatrix Copy()
        {
            return InternalCopy();
        }

        public void GetMatrixData(ref double[] cells)
        {
            InternalGetMatrixData(ref cells);
        }

        public void Invert()
        {
            InternalInvert();
        }

        public bool IsEqualTo(InvMatrix matrix, double tolerance)
        {
            return InternalIsEqualTo(matrix, tolerance);
        }

        public void MultiplyBy(InvMatrix matrix)
        {
            InternalMultiplyBy(matrix);
        }

        public void PostMultiplyBy(InvMatrix matrix)
        {
            InternalPostMultiplyBy(matrix);
        }

        public void PreMultiplyBy(InvMatrix matrix)
        {
            InternalPreMultiplyBy(matrix);
        }

        public void PutMatrixData(ref double[] cells)
        {
            InternalPutMatrixData(ref cells);
        }

        public void SetCoordinateSystem(InvPoint origin, InvVector xAxis, InvVector yAxis, InvVector zAxis)
        {
            InternalSetCoordinateSystem(origin, xAxis, yAxis, zAxis);
        }

        public void SetToAlignCoordinateSystems(InvPoint fromOrigin, InvVector fromXAxis, InvVector fromYAxis, InvVector fromZAxis, InvPoint toOrigin, InvVector toXAxis, InvVector toYAxis, InvVector toZAxis)
        {
            InternalSetToAlignCoordinateSystems(fromOrigin, fromXAxis, fromYAxis, fromZAxis, toOrigin, toXAxis, toYAxis, toZAxis);
        }

        public void SetToIdentity()
        {
            InternalSetToIdentity();
        }

        public void SetToRotateTo(InvVector from, InvVector to, InvVector axis)
        {
            InternalSetToRotateTo(from, to, axis);
        }

        public void SetToRotation(double angle, InvVector axis, InvPoint center)
        {
            InternalSetToRotation(angle, axis, center);
        }

        public void SetTranslation(InvVector translation, bool resetRotation)
        {
            InternalSetTranslation(translation, resetRotation);
        }

        public void TransformBy(InvMatrix matrix)
        {
            InternalTransformBy(matrix);
        }

        #endregion
    }
}
