// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ModelingSettings. Do not edit; put additions in InvModelingSettings.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvModelingSettings
    {
        #region Internal properties
        internal Inventor.ModelingSettings InternalModelingSettings { get; set; }

        internal bool InternalAdaptivelyUsedInAssembly
        {
            get { return ModelingSettingsInstance.AdaptivelyUsedInAssembly; }
            set { ModelingSettingsInstance.AdaptivelyUsedInAssembly = value; }
        }

        internal bool InternalAdvancedFeatureValidation
        {
            get { return ModelingSettingsInstance.AdvancedFeatureValidation; }
            set { ModelingSettingsInstance.AdvancedFeatureValidation = value; }
        }

        internal bool InternalAllowSectioningThruPart
        {
            get { return ModelingSettingsInstance.AllowSectioningThruPart; }
            set { ModelingSettingsInstance.AllowSectioningThruPart = value; }
        }

        internal object InternalApplication
        {
            get { return ModelingSettingsInstance.Application; }
        }

        internal bool InternalAutoFindErrorsAfterManualRepair
        {
            get { return ModelingSettingsInstance.AutoFindErrorsAfterManualRepair; }
            set { ModelingSettingsInstance.AutoFindErrorsAfterManualRepair = value; }
        }

        internal bool InternalCompactModelHistory
        {
            get { return ModelingSettingsInstance.CompactModelHistory; }
            set { ModelingSettingsInstance.CompactModelHistory = value; }
        }

        internal double InternalInitialDrawingViewHeight
        {
            get { return ModelingSettingsInstance.InitialDrawingViewHeight; }
            set { ModelingSettingsInstance.InitialDrawingViewHeight = value; }
        }

        internal double InternalInitialDrawingViewWidth
        {
            get { return ModelingSettingsInstance.InitialDrawingViewWidth; }
            set { ModelingSettingsInstance.InitialDrawingViewWidth = value; }
        }

        // skipped: InteractiveContactAnalysis: Inventor.InteractiveContactAnalysisEnum is not wrapped
        // skipped: InteractiveContactSurfaces: Inventor.InteractiveContactSurfacesEnum is not wrapped
        internal bool InternalMaintainEnhancedGraphicsDetail
        {
            get { return ModelingSettingsInstance.MaintainEnhancedGraphicsDetail; }
            set { ModelingSettingsInstance.MaintainEnhancedGraphicsDetail = value; }
        }

        // skipped: Parent: Inventor._Document is not wrapped
        internal bool InternalShowConstraintStateInBrowser
        {
            get { return ModelingSettingsInstance.ShowConstraintStateInBrowser; }
            set { ModelingSettingsInstance.ShowConstraintStateInBrowser = value; }
        }

        internal string InternalSnap3DAngle
        {
            get { return ModelingSettingsInstance.Snap3DAngle; }
            set { ModelingSettingsInstance.Snap3DAngle = value; }
        }

        internal string InternalSnap3DDistance
        {
            get { return ModelingSettingsInstance.Snap3DDistance; }
            set { ModelingSettingsInstance.Snap3DDistance = value; }
        }

        internal string InternalSolidBodyNamePrefix
        {
            get { return ModelingSettingsInstance.SolidBodyNamePrefix; }
            set { ModelingSettingsInstance.SolidBodyNamePrefix = value; }
        }

        internal string InternalSurfaceBodyNamePrefix
        {
            get { return ModelingSettingsInstance.SurfaceBodyNamePrefix; }
            set { ModelingSettingsInstance.SurfaceBodyNamePrefix = value; }
        }

        // skipped: TappedHoleDiameter: Inventor.ModelDiameterFromThreadEnum is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ModelingSettingsInstance.Type; }
        }

        internal bool InternalUpdateLegacyHoles
        {
            get { return ModelingSettingsInstance.UpdateLegacyHoles; }
            set { ModelingSettingsInstance.UpdateLegacyHoles = value; }
        }

        // skipped: UserCoordinateSystemSettings: Inventor.UserCoordinateSystemSettings is not wrapped
        #endregion

        #region Private constructors
        private InvModelingSettings(InvModelingSettings invModelingSettings)
        {
            InternalModelingSettings = invModelingSettings.InternalModelingSettings;
        }

        private InvModelingSettings(Inventor.ModelingSettings invModelingSettings)
        {
            InternalModelingSettings = invModelingSettings;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ModelingSettings ModelingSettingsInstance
        {
            get { return InternalModelingSettings; }
            set { InternalModelingSettings = value; }
        }

        public bool AdaptivelyUsedInAssembly
        {
            get { return InternalAdaptivelyUsedInAssembly; }
            set { InternalAdaptivelyUsedInAssembly = value; }
        }

        public bool AdvancedFeatureValidation
        {
            get { return InternalAdvancedFeatureValidation; }
            set { InternalAdvancedFeatureValidation = value; }
        }

        public bool AllowSectioningThruPart
        {
            get { return InternalAllowSectioningThruPart; }
            set { InternalAllowSectioningThruPart = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public bool AutoFindErrorsAfterManualRepair
        {
            get { return InternalAutoFindErrorsAfterManualRepair; }
            set { InternalAutoFindErrorsAfterManualRepair = value; }
        }

        public bool CompactModelHistory
        {
            get { return InternalCompactModelHistory; }
            set { InternalCompactModelHistory = value; }
        }

        public double InitialDrawingViewHeight
        {
            get { return InternalInitialDrawingViewHeight; }
            set { InternalInitialDrawingViewHeight = value; }
        }

        public double InitialDrawingViewWidth
        {
            get { return InternalInitialDrawingViewWidth; }
            set { InternalInitialDrawingViewWidth = value; }
        }

        public bool MaintainEnhancedGraphicsDetail
        {
            get { return InternalMaintainEnhancedGraphicsDetail; }
            set { InternalMaintainEnhancedGraphicsDetail = value; }
        }

        public bool ShowConstraintStateInBrowser
        {
            get { return InternalShowConstraintStateInBrowser; }
            set { InternalShowConstraintStateInBrowser = value; }
        }

        public string Snap3DAngle
        {
            get { return InternalSnap3DAngle; }
            set { InternalSnap3DAngle = value; }
        }

        public string Snap3DDistance
        {
            get { return InternalSnap3DDistance; }
            set { InternalSnap3DDistance = value; }
        }

        public string SolidBodyNamePrefix
        {
            get { return InternalSolidBodyNamePrefix; }
            set { InternalSolidBodyNamePrefix = value; }
        }

        public string SurfaceBodyNamePrefix
        {
            get { return InternalSurfaceBodyNamePrefix; }
            set { InternalSurfaceBodyNamePrefix = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public bool UpdateLegacyHoles
        {
            get { return InternalUpdateLegacyHoles; }
            set { InternalUpdateLegacyHoles = value; }
        }

        #endregion

        #region Public static constructors
        public static InvModelingSettings ByInvModelingSettings(InvModelingSettings invModelingSettings)
        {
            return invModelingSettings == null ? null : new InvModelingSettings(invModelingSettings);
        }

        [SupressImportIntoVM]
        public static InvModelingSettings ByInvModelingSettings(Inventor.ModelingSettings invModelingSettings)
        {
            return invModelingSettings == null ? null : new InvModelingSettings(invModelingSettings);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
