// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.NameValueMap. Do not edit; put additions in InvNameValueMap.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvNameValueMap
    {
        #region Internal properties
        internal Inventor.NameValueMap InternalNameValueMap { get; set; }

        internal int InternalCount
        {
            get { return NameValueMapInstance.Count; }
        }

        internal object InternalItem(object index)
        {
            return NameValueMapInstance.get_Item(index);
        }

        internal string InternalName(int index)
        {
            return NameValueMapInstance.get_Name(index);
        }

        internal object InternalValue(string name)
        {
            return NameValueMapInstance.get_Value(name);
        }

        #endregion

        #region Private constructors
        private InvNameValueMap(InvNameValueMap invNameValueMap)
        {
            InternalNameValueMap = invNameValueMap.InternalNameValueMap;
        }

        private InvNameValueMap(Inventor.NameValueMap invNameValueMap)
        {
            InternalNameValueMap = invNameValueMap;
        }
        #endregion

        #region Private methods
        private void InternalAdd(string name, object value)
        {
            NameValueMapInstance.Add(name, value);
        }

        private void InternalClear()
        {
            NameValueMapInstance.Clear();
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        private void InternalInsert(string name, object value, object targetIndex, bool insertBefore)
        {
            NameValueMapInstance.Insert(name, value, targetIndex, insertBefore);
        }

        private void InternalRemove(object index)
        {
            NameValueMapInstance.Remove(index);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.NameValueMap NameValueMapInstance
        {
            get { return InternalNameValueMap; }
            set { InternalNameValueMap = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public object Item(object index)
        {
            return InternalItem(index);
        }

        public string Name(int index)
        {
            return InternalName(index);
        }

        public object Value(string name)
        {
            return InternalValue(name);
        }

        #endregion

        #region Public static constructors
        public static InvNameValueMap ByInvNameValueMap(InvNameValueMap invNameValueMap)
        {
            return invNameValueMap == null ? null : new InvNameValueMap(invNameValueMap);
        }

        [SupressImportIntoVM]
        public static InvNameValueMap ByInvNameValueMap(Inventor.NameValueMap invNameValueMap)
        {
            return invNameValueMap == null ? null : new InvNameValueMap(invNameValueMap);
        }
        #endregion

        #region Public methods
        public void Add(string name, object value)
        {
            InternalAdd(name, value);
        }

        public void Clear()
        {
            InternalClear();
        }

        public void Insert(string name, object value, object targetIndex, bool insertBefore)
        {
            InternalInsert(name, value, targetIndex, insertBefore);
        }

        public void Remove(object index)
        {
            InternalRemove(index);
        }

        #endregion
    }
}
