// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ObjectsEnumerator. Do not edit; put additions in InvObjectsEnumerator.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvObjectsEnumerator
    {
        #region Internal properties
        internal Inventor.ObjectsEnumerator InternalObjectsEnumerator { get; set; }

        internal int InternalCount
        {
            get { return ObjectsEnumeratorInstance.Count; }
        }

        internal object InternalItem(int index)
        {
            return ObjectsEnumeratorInstance[index];
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ObjectsEnumeratorInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvObjectsEnumerator(InvObjectsEnumerator invObjectsEnumerator)
        {
            InternalObjectsEnumerator = invObjectsEnumerator.InternalObjectsEnumerator;
        }

        private InvObjectsEnumerator(Inventor.ObjectsEnumerator invObjectsEnumerator)
        {
            InternalObjectsEnumerator = invObjectsEnumerator;
        }
        #endregion

        #region Private methods
        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ObjectsEnumerator ObjectsEnumeratorInstance
        {
            get { return InternalObjectsEnumerator; }
            set { InternalObjectsEnumerator = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public object Item(int index)
        {
            return InternalItem(index);
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvObjectsEnumerator ByInvObjectsEnumerator(InvObjectsEnumerator invObjectsEnumerator)
        {
            return invObjectsEnumerator == null ? null : new InvObjectsEnumerator(invObjectsEnumerator);
        }

        [SupressImportIntoVM]
        public static InvObjectsEnumerator ByInvObjectsEnumerator(Inventor.ObjectsEnumerator invObjectsEnumerator)
        {
            return invObjectsEnumerator == null ? null : new InvObjectsEnumerator(invObjectsEnumerator);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
