// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.OGSSceneNode. Do not edit; put additions in InvOGSSceneNode.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvOGSSceneNode
    {
        #region Internal properties
        internal Inventor.OGSSceneNode InternalOGSSceneNode { get; set; }

        // skipped: Document: Inventor._Document is not wrapped
        internal string InternalName
        {
            get { return OGSSceneNodeInstance.Name; }
        }

        internal object InternalParent
        {
            get { return OGSSceneNodeInstance.Parent; }
        }

        // skipped: RenderItems: Inventor.OGSRenderItemsEnumerator is not wrapped
        // skipped: SceneNodeType: Inventor.OGSSceneNodeTypeEnum is not wrapped
        // skipped: SubSceneNodes: Inventor.OGSSceneNodesEnumerator is not wrapped
        internal InvMatrix InternalTransformation
        {
            get { return InvMatrix.ByInvMatrix(OGSSceneNodeInstance.Transformation); }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)OGSSceneNodeInstance.Type; }
        }

        internal bool InternalVisible
        {
            get { return OGSSceneNodeInstance.Visible; }
        }

        #endregion

        #region Private constructors
        private InvOGSSceneNode(InvOGSSceneNode invOGSSceneNode)
        {
            InternalOGSSceneNode = invOGSSceneNode.InternalOGSSceneNode;
        }

        private InvOGSSceneNode(Inventor.OGSSceneNode invOGSSceneNode)
        {
            InternalOGSSceneNode = invOGSSceneNode;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.OGSSceneNode OGSSceneNodeInstance
        {
            get { return InternalOGSSceneNode; }
            set { InternalOGSSceneNode = value; }
        }

        public string Name
        {
            get { return InternalName; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public InvMatrix Transformation
        {
            get { return InternalTransformation; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public bool Visible
        {
            get { return InternalVisible; }
        }

        #endregion

        #region Public static constructors
        public static InvOGSSceneNode ByInvOGSSceneNode(InvOGSSceneNode invOGSSceneNode)
        {
            return invOGSSceneNode == null ? null : new InvOGSSceneNode(invOGSSceneNode);
        }

        [SupressImportIntoVM]
        public static InvOGSSceneNode ByInvOGSSceneNode(Inventor.OGSSceneNode invOGSSceneNode)
        {
            return invOGSSceneNode == null ? null : new InvOGSSceneNode(invOGSSceneNode);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
