// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ObjectVisibility. Do not edit; put additions in InvObjectVisibility.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvObjectVisibility
    {
        #region Internal properties
        internal Inventor.ObjectVisibility InternalObjectVisibility { get; set; }

        internal bool InternalAllWorkFeatures
        {
            get { return ObjectVisibilityInstance.AllWorkFeatures; }
            set { ObjectVisibilityInstance.AllWorkFeatures = value; }
        }

        internal bool InternalAnnotations3D
        {
            get { return ObjectVisibilityInstance.Annotations3D; }
            set { ObjectVisibilityInstance.Annotations3D = value; }
        }

        internal object InternalApplication
        {
            get { return ObjectVisibilityInstance.Application; }
        }

        internal bool InternalComponentAnnotations3D
        {
            get { return ObjectVisibilityInstance.ComponentAnnotations3D; }
            set { ObjectVisibilityInstance.ComponentAnnotations3D = value; }
        }

        internal bool InternalConstructionSurfaces
        {
            get { return ObjectVisibilityInstance.ConstructionSurfaces; }
            set { ObjectVisibilityInstance.ConstructionSurfaces = value; }
        }

        internal bool InternalGroupDiagnostics
        {
            get { return ObjectVisibilityInstance.GroupDiagnostics; }
            set { ObjectVisibilityInstance.GroupDiagnostics = value; }
        }

        internal bool InternalGroupSolids
        {
            get { return ObjectVisibilityInstance.GroupSolids; }
            set { ObjectVisibilityInstance.GroupSolids = value; }
        }

        internal bool InternalGroupSurfaces
        {
            get { return ObjectVisibilityInstance.GroupSurfaces; }
            set { ObjectVisibilityInstance.GroupSurfaces = value; }
        }

        internal bool InternalGroupWires
        {
            get { return ObjectVisibilityInstance.GroupWires; }
            set { ObjectVisibilityInstance.GroupWires = value; }
        }

        internal bool InternalOriginWorkAxes
        {
            get { return ObjectVisibilityInstance.OriginWorkAxes; }
            set { ObjectVisibilityInstance.OriginWorkAxes = value; }
        }

        internal bool InternalOriginWorkPlanes
        {
            get { return ObjectVisibilityInstance.OriginWorkPlanes; }
            set { ObjectVisibilityInstance.OriginWorkPlanes = value; }
        }

        internal bool InternalOriginWorkPoints
        {
            get { return ObjectVisibilityInstance.OriginWorkPoints; }
            set { ObjectVisibilityInstance.OriginWorkPoints = value; }
        }

        // skipped: Parent: Inventor._Document is not wrapped
        internal bool InternalSketchDimensions
        {
            get { return ObjectVisibilityInstance.SketchDimensions; }
            set { ObjectVisibilityInstance.SketchDimensions = value; }
        }

        internal bool InternalSketches
        {
            get { return ObjectVisibilityInstance.Sketches; }
            set { ObjectVisibilityInstance.Sketches = value; }
        }

        internal bool InternalSketches3D
        {
            get { return ObjectVisibilityInstance.Sketches3D; }
            set { ObjectVisibilityInstance.Sketches3D = value; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ObjectVisibilityInstance.Type; }
        }

        internal bool InternalUCSTriads
        {
            get { return ObjectVisibilityInstance.UCSTriads; }
            set { ObjectVisibilityInstance.UCSTriads = value; }
        }

        internal bool InternalUCSWorkAxes
        {
            get { return ObjectVisibilityInstance.UCSWorkAxes; }
            set { ObjectVisibilityInstance.UCSWorkAxes = value; }
        }

        internal bool InternalUCSWorkPlanes
        {
            get { return ObjectVisibilityInstance.UCSWorkPlanes; }
            set { ObjectVisibilityInstance.UCSWorkPlanes = value; }
        }

        internal bool InternalUCSWorkPoints
        {
            get { return ObjectVisibilityInstance.UCSWorkPoints; }
            set { ObjectVisibilityInstance.UCSWorkPoints = value; }
        }

        internal bool InternalUserWorkAxes
        {
            get { return ObjectVisibilityInstance.UserWorkAxes; }
            set { ObjectVisibilityInstance.UserWorkAxes = value; }
        }

        internal bool InternalUserWorkPlanes
        {
            get { return ObjectVisibilityInstance.UserWorkPlanes; }
            set { ObjectVisibilityInstance.UserWorkPlanes = value; }
        }

        internal bool InternalUserWorkPoints
        {
            get { return ObjectVisibilityInstance.UserWorkPoints; }
            set { ObjectVisibilityInstance.UserWorkPoints = value; }
        }

        internal bool InternalWeldmentSymbols
        {
            get { return ObjectVisibilityInstance.WeldmentSymbols; }
            set { ObjectVisibilityInstance.WeldmentSymbols = value; }
        }

        internal bool InternalWelds
        {
            get { return ObjectVisibilityInstance.Welds; }
            set { ObjectVisibilityInstance.Welds = value; }
        }

        #endregion

        #region Private constructors
        private InvObjectVisibility(InvObjectVisibility invObjectVisibility)
        {
            InternalObjectVisibility = invObjectVisibility.InternalObjectVisibility;
        }

        private InvObjectVisibility(Inventor.ObjectVisibility invObjectVisibility)
        {
            InternalObjectVisibility = invObjectVisibility;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ObjectVisibility ObjectVisibilityInstance
        {
            get { return InternalObjectVisibility; }
            set { InternalObjectVisibility = value; }
        }

        public bool AllWorkFeatures
        {
            get { return InternalAllWorkFeatures; }
            set { InternalAllWorkFeatures = value; }
        }

        public bool Annotations3D
        {
            get { return InternalAnnotations3D; }
            set { InternalAnnotations3D = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public bool ComponentAnnotations3D
        {
            get { return InternalComponentAnnotations3D; }
            set { InternalComponentAnnotations3D = value; }
        }

        public bool ConstructionSurfaces
        {
            get { return InternalConstructionSurfaces; }
            set { InternalConstructionSurfaces = value; }
        }

        public bool GroupDiagnostics
        {
            get { return InternalGroupDiagnostics; }
            set { InternalGroupDiagnostics = value; }
        }

        public bool GroupSolids
        {
            get { return InternalGroupSolids; }
            set { InternalGroupSolids = value; }
        }

        public bool GroupSurfaces
        {
            get { return InternalGroupSurfaces; }
            set { InternalGroupSurfaces = value; }
        }

        public bool GroupWires
        {
            get { return InternalGroupWires; }
            set { InternalGroupWires = value; }
        }

        public bool OriginWorkAxes
        {
            get { return InternalOriginWorkAxes; }
            set { InternalOriginWorkAxes = value; }
        }

        public bool OriginWorkPlanes
        {
            get { return InternalOriginWorkPlanes; }
            set { InternalOriginWorkPlanes = value; }
        }

        public bool OriginWorkPoints
        {
            get { return InternalOriginWorkPoints; }
            set { InternalOriginWorkPoints = value; }
        }

        public bool SketchDimensions
        {
            get { return InternalSketchDimensions; }
            set { InternalSketchDimensions = value; }
        }

        public bool Sketches
        {
            get { return InternalSketches; }
            set { InternalSketches = value; }
        }

        public bool Sketches3D
        {
            get { return InternalSketches3D; }
            set { InternalSketches3D = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public bool UCSTriads
        {
            get { return InternalUCSTriads; }
            set { InternalUCSTriads = value; }
        }

        public bool UCSWorkAxes
        {
            get { return InternalUCSWorkAxes; }
            set { InternalUCSWorkAxes = value; }
        }

        public bool UCSWorkPlanes
        {
            get { return InternalUCSWorkPlanes; }
            set { InternalUCSWorkPlanes = value; }
        }

        public bool UCSWorkPoints
        {
            get { return InternalUCSWorkPoints; }
            set { InternalUCSWorkPoints = value; }
        }

        public bool UserWorkAxes
        {
            get { return InternalUserWorkAxes; }
            set { InternalUserWorkAxes = value; }
        }

        public bool UserWorkPlanes
        {
            get { return InternalUserWorkPlanes; }
            set { InternalUserWorkPlanes = value; }
        }

        public bool UserWorkPoints
        {
            get { return InternalUserWorkPoints; }
            set { InternalUserWorkPoints = value; }
        }

        public bool WeldmentSymbols
        {
            get { return InternalWeldmentSymbols; }
            set { InternalWeldmentSymbols = value; }
        }

        public bool Welds
        {
            get { return InternalWelds; }
            set { InternalWelds = value; }
        }

        #endregion

        #region Public static constructors
        public static InvObjectVisibility ByInvObjectVisibility(InvObjectVisibility invObjectVisibility)
        {
            return invObjectVisibility == null ? null : new InvObjectVisibility(invObjectVisibility);
        }

        [SupressImportIntoVM]
        public static InvObjectVisibility ByInvObjectVisibility(Inventor.ObjectVisibility invObjectVisibility)
        {
            return invObjectVisibility == null ? null : new InvObjectVisibility(invObjectVisibility);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
