// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ObjectCollection. Do not edit; put additions in InvObjectCollection.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvObjectCollection
    {
        #region Internal properties
        internal Inventor.ObjectCollection InternalObjectCollection { get; set; }

        internal int InternalCount
        {
            get { return ObjectCollectionInstance.Count; }
        }

        internal object InternalItem(int index)
        {
            return ObjectCollectionInstance[index];
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ObjectCollectionInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvObjectCollection(InvObjectCollection invObjectCollection)
        {
            InternalObjectCollection = invObjectCollection.InternalObjectCollection;
        }

        private InvObjectCollection(Inventor.ObjectCollection invObjectCollection)
        {
            InternalObjectCollection = invObjectCollection;
        }
        #endregion

        #region Private methods
        private void InternalAdd(object @object)
        {
            ObjectCollectionInstance.Add(@object);
        }

        private void InternalClear()
        {
            ObjectCollectionInstance.Clear();
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        private void InternalRemove(int index)
        {
            ObjectCollectionInstance.Remove(index);
        }

        private void InternalRemoveByObject(object @object)
        {
            ObjectCollectionInstance.RemoveByObject(@object);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ObjectCollection ObjectCollectionInstance
        {
            get { return InternalObjectCollection; }
            set { InternalObjectCollection = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public object Item(int index)
        {
            return InternalItem(index);
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvObjectCollection ByInvObjectCollection(InvObjectCollection invObjectCollection)
        {
            return invObjectCollection == null ? null : new InvObjectCollection(invObjectCollection);
        }

        [SupressImportIntoVM]
        public static InvObjectCollection ByInvObjectCollection(Inventor.ObjectCollection invObjectCollection)
        {
            return invObjectCollection == null ? null : new InvObjectCollection(invObjectCollection);
        }
        #endregion

        #region Public methods
        public void Add(object @object)
        {
            InternalAdd(@object);
        }

        public void Clear()
        {
            InternalClear();
        }

        public void Remove(int index)
        {
            InternalRemove(index);
        }

        public void RemoveByObject(object @object)
        {
            InternalRemoveByObject(@object);
        }

        #endregion
    }
}
