// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.PropertySets. Do not edit; put additions in InvPropertySets.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvPropertySets
    {
        #region Internal properties
        internal Inventor.PropertySets InternalPropertySets { get; set; }

        internal int InternalCount
        {
            get { return PropertySetsInstance.Count; }
        }

        internal bool InternalDirty
        {
            get { return PropertySetsInstance.Dirty; }
        }

        // skipped: Item: Inventor.PropertySet is not wrapped
        internal object InternalParent
        {
            get { return PropertySetsInstance.Parent; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)PropertySetsInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvPropertySets(InvPropertySets invPropertySets)
        {
            InternalPropertySets = invPropertySets.InternalPropertySets;
        }

        private InvPropertySets(Inventor.PropertySets invPropertySets)
        {
            InternalPropertySets = invPropertySets;
        }
        #endregion

        #region Private methods
        // skipped: Add(): returns Inventor.PropertySet, not wrapped
        private void InternalFlushToFile()
        {
            PropertySetsInstance.FlushToFile();
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        private bool InternalPropertySetExists(string propertySetName, out object propertySet)
        {
            return PropertySetsInstance.PropertySetExists(propertySetName, out propertySet);
        }

        private void InternalRefreshFromFile()
        {
            PropertySetsInstance.RefreshFromFile();
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.PropertySets PropertySetsInstance
        {
            get { return InternalPropertySets; }
            set { InternalPropertySets = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public bool Dirty
        {
            get { return InternalDirty; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvPropertySets ByInvPropertySets(InvPropertySets invPropertySets)
        {
            return invPropertySets == null ? null : new InvPropertySets(invPropertySets);
        }

        [SupressImportIntoVM]
        public static InvPropertySets ByInvPropertySets(Inventor.PropertySets invPropertySets)
        {
            return invPropertySets == null ? null : new InvPropertySets(invPropertySets);
        }
        #endregion

        #region Public methods
        public void FlushToFile()
        {
            InternalFlushToFile();
        }

        public bool PropertySetExists(string propertySetName, out object propertySet)
        {
            return InternalPropertySetExists(propertySetName, out propertySet);
        }

        public void RefreshFromFile()
        {
            InternalRefreshFromFile();
        }

        #endregion
    }
}
