// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.PartDocument. Do not edit; put additions in InvPartDocument.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvPartDocument
    {
        #region Internal properties
        internal Inventor.PartDocument InternalPartDocument { get; set; }

        internal object InternalActivatedObject
        {
            get { return PartDocumentInstance.ActivatedObject; }
        }

        internal string InternalActiveAnnotationsStandard
        {
            get { return PartDocumentInstance.ActiveAnnotationsStandard; }
            set { PartDocumentInstance.ActiveAnnotationsStandard = value; }
        }

        internal InvAsset InternalActiveAppearance
        {
            get { return InvAsset.ByInvAsset(PartDocumentInstance.ActiveAppearance); }
            set { PartDocumentInstance.ActiveAppearance = value?.AssetInstance; }
        }

        internal InvLightingStyle InternalActiveLightingStyle
        {
            get { return InvLightingStyle.ByInvLightingStyle(PartDocumentInstance.ActiveLightingStyle); }
            set { PartDocumentInstance.ActiveLightingStyle = value?.LightingStyleInstance; }
        }

        // skipped: ActiveMarkStyle: Inventor.MarkStyle is not wrapped
        internal InvAsset InternalActiveMaterial
        {
            get { return InvAsset.ByInvAsset(PartDocumentInstance.ActiveMaterial); }
            set { PartDocumentInstance.ActiveMaterial = value?.AssetInstance; }
        }

        internal InvRenderStyle InternalActiveRenderStyle
        {
            get { return InvRenderStyle.ByInvRenderStyle(PartDocumentInstance.ActiveRenderStyle); }
            set { PartDocumentInstance.ActiveRenderStyle = value?.RenderStyleInstance; }
        }

        internal InvDocumentsEnumerator InternalAllReferencedDocuments
        {
            get { return InvDocumentsEnumerator.ByInvDocumentsEnumerator(PartDocumentInstance.AllReferencedDocuments); }
        }

        internal InvAssetsEnumerator InternalAppearanceAssets
        {
            get { return InvAssetsEnumerator.ByInvAssetsEnumerator(PartDocumentInstance.AppearanceAssets); }
        }

        // skipped: AppearanceSourceType: Inventor.AppearanceSourceTypeEnum is not wrapped
        internal InvAssets InternalAssets
        {
            get { return InvAssets.ByInvAssets(PartDocumentInstance.Assets); }
        }

        internal string InternalAssociativeForeignFilename
        {
            get { return PartDocumentInstance.AssociativeForeignFilename; }
        }

        internal InvAttributeManager InternalAttributeManager
        {
            get { return InvAttributeManager.ByInvAttributeManager(PartDocumentInstance.AttributeManager); }
        }

        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(PartDocumentInstance.AttributeSets); }
        }

        // skipped: BrowserPanes: Inventor.BrowserPanes is not wrapped
        // skipped: ClientViews: Inventor.ClientViews is not wrapped
        internal bool InternalCompacted
        {
            get { return PartDocumentInstance.Compacted; }
        }

        internal InvPartComponentDefinition InternalComponentDefinition
        {
            get { return InvPartComponentDefinition.ByInvPartComponentDefinition(PartDocumentInstance.ComponentDefinition); }
        }

        // skipped: ComponentDefinitions: Inventor.PartComponentDefinitions is not wrapped
        internal string InternalDatabaseRevisionId
        {
            get { return PartDocumentInstance.DatabaseRevisionId; }
        }

        internal string InternalDefaultCommand
        {
            get { return PartDocumentInstance.DefaultCommand; }
        }

        internal bool InternalDirty
        {
            get { return PartDocumentInstance.Dirty; }
            set { PartDocumentInstance.Dirty = value; }
        }

        internal InvDisabledCommandList InternalDisabledCommandList
        {
            get { return InvDisabledCommandList.ByInvDisabledCommandList(PartDocumentInstance.DisabledCommandList); }
        }

        internal InvCommandTypesEnum InternalDisabledCommandTypes
        {
            get { return (InvCommandTypesEnum)PartDocumentInstance.DisabledCommandTypes; }
            set { PartDocumentInstance.DisabledCommandTypes = (Inventor.CommandTypesEnum)value; }
        }

        internal string InternalDisplayName
        {
            get { return PartDocumentInstance.DisplayName; }
            set { PartDocumentInstance.DisplayName = value; }
        }

        internal string InternalDisplayNameBasis
        {
            get { return PartDocumentInstance.DisplayNameBasis; }
            set { PartDocumentInstance.DisplayNameBasis = value; }
        }

        internal bool InternalDisplayNameOverridden
        {
            get { return PartDocumentInstance.DisplayNameOverridden; }
            set { PartDocumentInstance.DisplayNameOverridden = value; }
        }

        internal InvDisplaySettings InternalDisplaySettings
        {
            get { return InvDisplaySettings.ByInvDisplaySettings(PartDocumentInstance.DisplaySettings); }
        }

        internal InvDocumentEvents InternalDocumentEvents
        {
            get { return InvDocumentEvents.ByInvDocumentEvents(PartDocumentInstance.DocumentEvents); }
        }

        internal InvDocumentInterests InternalDocumentInterests
        {
            get { return InvDocumentInterests.ByInvDocumentInterests(PartDocumentInstance.DocumentInterests); }
        }

        internal InvDocumentSubType InternalDocumentSubType
        {
            get { return InvDocumentSubType.ByInvDocumentSubType(PartDocumentInstance.DocumentSubType); }
        }

        internal InvDocumentTypeEnum InternalDocumentType
        {
            get { return (InvDocumentTypeEnum)PartDocumentInstance.DocumentType; }
        }

        // skipped: EmbeddingDocument: Inventor._Document is not wrapped
        internal InvEnvironmentManager InternalEnvironmentManager
        {
            get { return InvEnvironmentManager.ByInvEnvironmentManager(PartDocumentInstance.EnvironmentManager); }
        }

        internal string InternalExplicitName
        {
            get { return PartDocumentInstance.ExplicitName; }
        }

        internal InvFile InternalFile
        {
            get { return InvFile.ByInvFile(PartDocumentInstance.File); }
        }

        internal InvPropertySets InternalFilePropertySets
        {
            get { return InvPropertySets.ByInvPropertySets(PartDocumentInstance.FilePropertySets); }
        }

        internal int InternalFileSaveCounter
        {
            get { return PartDocumentInstance.FileSaveCounter; }
        }

        // skipped: FlatPatternSettings: Inventor.FlatPatternSettings is not wrapped
        internal string InternalFullDisplayName
        {
            get { return PartDocumentInstance.FullDisplayName; }
        }

        internal string InternalFullDocumentName
        {
            get { return PartDocumentInstance.FullDocumentName; }
        }

        internal string InternalFullFileName
        {
            get { return PartDocumentInstance.FullFileName; }
            set { PartDocumentInstance.FullFileName = value; }
        }

        // skipped: GraphicsDataSetsCollection: Inventor.GraphicsDataSetsCollection is not wrapped
        internal bool InternalHasReferencesMissing
        {
            get { return PartDocumentInstance.HasReferencesMissing; }
        }

        internal InvHighlightSets InternalHighlightSets
        {
            get { return InvHighlightSets.ByInvHighlightSets(PartDocumentInstance.HighlightSets); }
        }

        internal string InternalInternalName
        {
            get { return PartDocumentInstance.InternalName; }
        }

        // skipped: InventorDocument: Inventor._Document is not wrapped
        internal bool InternalIsEmbeddedDocument
        {
            get { return PartDocumentInstance.IsEmbeddedDocument; }
        }

        internal bool InternalIsModifiable
        {
            get { return PartDocumentInstance.IsModifiable; }
        }

        internal bool InternalIsSubstitutePart
        {
            get { return PartDocumentInstance.IsSubstitutePart; }
            set { PartDocumentInstance.IsSubstitutePart = value; }
        }

        internal InvLightingStyles InternalLightingStyles
        {
            get { return InvLightingStyles.ByInvLightingStyles(PartDocumentInstance.LightingStyles); }
        }

        // skipped: MarkStyles: Inventor.MarkStylesEnumerator is not wrapped
        internal InvAssetsEnumerator InternalMaterialAssets
        {
            get { return InvAssetsEnumerator.ByInvAssetsEnumerator(PartDocumentInstance.MaterialAssets); }
        }

        internal InvMaterials InternalMaterials
        {
            get { return InvMaterials.ByInvMaterials(PartDocumentInstance.Materials); }
        }

        internal string InternalModelStateName
        {
            get { return PartDocumentInstance.ModelStateName; }
        }

        internal InvModelingSettings InternalModelingSettings
        {
            get { return InvModelingSettings.ByInvModelingSettings(PartDocumentInstance.ModelingSettings); }
        }

        internal bool InternalNeedsMigrating
        {
            get { return PartDocumentInstance.NeedsMigrating; }
        }

        // skipped: NonTransactingClientGraphicsCollection: Inventor.ClientGraphicsCollection is not wrapped
        // skipped: NonTransactingGraphicsDataSetsCollection: Inventor.GraphicsDataSetsCollection is not wrapped
        internal InvObjectVisibility InternalObjectVisibility
        {
            get { return InvObjectVisibility.ByInvObjectVisibility(PartDocumentInstance.ObjectVisibility); }
        }

        internal bool InternalOpen
        {
            get { return PartDocumentInstance.Open; }
        }

        internal InvFileOwnershipEnum InternalOwnershipType
        {
            get { return (InvFileOwnershipEnum)PartDocumentInstance.OwnershipType; }
        }

        internal object InternalParent
        {
            get { return PartDocumentInstance.Parent; }
        }

        internal InvAssetsEnumerator InternalPhysicalAssets
        {
            get { return InvAssetsEnumerator.ByInvAssetsEnumerator(PartDocumentInstance.PhysicalAssets); }
        }

        internal InvPrintManager InternalPrintManager
        {
            get { return InvPrintManager.ByInvPrintManager(PartDocumentInstance.PrintManager); }
        }

        internal InvPropertySets InternalPropertySets
        {
            get { return InvPropertySets.ByInvPropertySets(PartDocumentInstance.PropertySets); }
        }

        internal InvCommandTypesEnum InternalRecentChanges
        {
            get { return (InvCommandTypesEnum)PartDocumentInstance.RecentChanges; }
        }

        internal InvReferenceKeyManager InternalReferenceKeyManager
        {
            get { return InvReferenceKeyManager.ByInvReferenceKeyManager(PartDocumentInstance.ReferenceKeyManager); }
        }

        internal InvDocumentDescriptorsEnumerator InternalReferencedDocumentDescriptors
        {
            get { return InvDocumentDescriptorsEnumerator.ByInvDocumentDescriptorsEnumerator(PartDocumentInstance.ReferencedDocumentDescriptors); }
        }

        internal InvDocumentsEnumerator InternalReferencedDocuments
        {
            get { return InvDocumentsEnumerator.ByInvDocumentsEnumerator(PartDocumentInstance.ReferencedDocuments); }
        }

        internal InvReferencedFileDescriptors InternalReferencedFileDescriptors
        {
            get { return InvReferencedFileDescriptors.ByInvReferencedFileDescriptors(PartDocumentInstance.ReferencedFileDescriptors); }
        }

        internal InvDocumentsEnumerator InternalReferencedFiles
        {
            get { return InvDocumentsEnumerator.ByInvDocumentsEnumerator(PartDocumentInstance.ReferencedFiles); }
        }

        internal InvReferencedOLEFileDescriptors InternalReferencedOLEFileDescriptors
        {
            get { return InvReferencedOLEFileDescriptors.ByInvReferencedOLEFileDescriptors(PartDocumentInstance.ReferencedOLEFileDescriptors); }
        }

        // skipped: indexer ReferencedOLEFileDescriptors2: parameter ReferenceType is Inventor.OLEDocumentTypeEnum, not wrapped
        // skipped: ReferencedOpaqueFileDescriptors: Inventor.ReferencedOpaqueFileDescriptors is not wrapped
        internal InvDocumentsEnumerator InternalReferencingDocuments
        {
            get { return InvDocumentsEnumerator.ByInvDocumentsEnumerator(PartDocumentInstance.ReferencingDocuments); }
        }

        internal InvRenderStyles InternalRenderStyles
        {
            get { return InvRenderStyles.ByInvRenderStyles(PartDocumentInstance.RenderStyles); }
        }

        internal bool InternalRequiresUpdate
        {
            get { return PartDocumentInstance.RequiresUpdate; }
        }

        internal bool InternalReservedForWrite
        {
            get { return PartDocumentInstance.ReservedForWrite; }
        }

        internal bool InternalReservedForWriteByMe
        {
            get { return PartDocumentInstance.ReservedForWriteByMe; }
            set { PartDocumentInstance.ReservedForWriteByMe = value; }
        }

        internal string InternalReservedForWriteLogin
        {
            get { return PartDocumentInstance.ReservedForWriteLogin; }
        }

        internal string InternalReservedForWriteName
        {
            get { return PartDocumentInstance.ReservedForWriteName; }
        }

        internal System.DateTime InternalReservedForWriteTime
        {
            get { return PartDocumentInstance.ReservedForWriteTime; }
        }

        internal int InternalReservedForWriteVersion
        {
            get { return PartDocumentInstance.ReservedForWriteVersion; }
        }

        internal string InternalRevisionId
        {
            get { return PartDocumentInstance.RevisionId; }
        }

        internal InvSelectSet InternalSelectSet
        {
            get { return InvSelectSet.ByInvSelectSet(PartDocumentInstance.SelectSet); }
        }

        // skipped: SelectionPreferences: Inventor.SelectionPreferences is not wrapped
        internal InvSelectionPriorityEnum InternalSelectionPriority
        {
            get { return (InvSelectionPriorityEnum)PartDocumentInstance.SelectionPriority; }
            set { PartDocumentInstance.SelectionPriority = (Inventor.SelectionPriorityEnum)value; }
        }

        // skipped: Sketch3DSettings: Inventor.Sketch3DSettings is not wrapped
        internal bool InternalSketchActive
        {
            get { return PartDocumentInstance.SketchActive; }
        }

        internal InvSketchSettings InternalSketchSettings
        {
            get { return InvSketchSettings.ByInvSketchSettings(PartDocumentInstance.SketchSettings); }
        }

        internal InvSoftwareVersion InternalSoftwareVersionCreated
        {
            get { return InvSoftwareVersion.ByInvSoftwareVersion(PartDocumentInstance.SoftwareVersionCreated); }
        }

        internal InvSoftwareVersion InternalSoftwareVersionSaved
        {
            get { return InvSoftwareVersion.ByInvSoftwareVersion(PartDocumentInstance.SoftwareVersionSaved); }
        }

        internal string InternalSubType
        {
            get { return PartDocumentInstance.SubType; }
            set { PartDocumentInstance.SubType = value; }
        }

        // skipped: SubstitutePartStatus: Inventor.ReferenceStatusEnum is not wrapped
        // skipped: TextStyles: Inventor.TextStylesEnumerator is not wrapped
        // skipped: Thumbnail: stdole.IPictureDisp is not wrapped
        internal InvThumbnailSaveOptionEnum InternalThumbnailSaveOption
        {
            get { return (InvThumbnailSaveOptionEnum)PartDocumentInstance.ThumbnailSaveOption; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)PartDocumentInstance.Type; }
        }

        internal InvUnitsOfMeasure InternalUnitsOfMeasure
        {
            get { return InvUnitsOfMeasure.ByInvUnitsOfMeasure(PartDocumentInstance.UnitsOfMeasure); }
        }

        internal InvInventorVBAProject InternalVBAProject
        {
            get { return InvInventorVBAProject.ByInvInventorVBAProject(PartDocumentInstance.VBAProject); }
        }

        internal InvViews InternalViews
        {
            get { return InvViews.ByInvViews(PartDocumentInstance.Views); }
        }

        #endregion

        #region Private constructors
        private InvPartDocument(InvPartDocument invPartDocument)
        {
            InternalPartDocument = invPartDocument.InternalPartDocument;
        }

        private InvPartDocument(Inventor.PartDocument invPartDocument)
        {
            InternalPartDocument = invPartDocument;
        }
        #endregion

        #region Private methods
        private void InternalActivate()
        {
            PartDocumentInstance.Activate();
        }

        // skipped: BatchEdit(): parameter Error is Inventor.MemberManagerErrorsEnum, not wrapped
        private void InternalClose(bool skipSave)
        {
            PartDocumentInstance.Close(skipSave);
        }

        private InvHighlightSet InternalCreateHighlightSet()
        {
            return InvHighlightSet.ByInvHighlightSet(PartDocumentInstance.CreateHighlightSet());
        }

        private void InternalExecutePromptToChoose3daStyle()
        {
            PartDocumentInstance.ExecutePromptToChoose3daStyle();
        }

        private InvDocumentsEnumerator InternalFindWhereUsed(string fullFileName)
        {
            return InvDocumentsEnumerator.ByInvDocumentsEnumerator(PartDocumentInstance.FindWhereUsed(fullFileName));
        }

        // skipped: GetLocationFoundIn(): parameter LocationType is Inventor.LocationTypeEnum, not wrapped
        // skipped: GetMissingAddInBehavior(): parameter DisabledCommandTypesEnum is a ref/out Inventor.CommandTypesEnum
        private object InternalGetPrivateStorage(string storageName, bool createIfNecessary)
        {
            return PartDocumentInstance.GetPrivateStorage(storageName, createIfNecessary);
        }

        private object InternalGetPrivateStream(string streamName, bool createIfNecessary)
        {
            return PartDocumentInstance.GetPrivateStream(streamName, createIfNecessary);
        }

        // skipped: GetSelectedObject(): parameter Selection is Inventor.GenericObject, not wrapped
        private bool InternalHasPrivateStorage(string storageName)
        {
            return PartDocumentInstance.HasPrivateStorage(storageName);
        }

        private bool InternalHasPrivateStream(string streamName)
        {
            return PartDocumentInstance.HasPrivateStream(streamName);
        }

        private void InternalLockSaveSet()
        {
            PartDocumentInstance.LockSaveSet();
        }

        private void InternalMakeModelStateMemberModifiable()
        {
            PartDocumentInstance.MakeModelStateMemberModifiable();
        }

        private void InternalMigrate()
        {
            PartDocumentInstance.Migrate();
        }

        private void InternalPutGraphicsLevelsOfDetail(int levelsOfDetail)
        {
            PartDocumentInstance.PutGraphicsLevelsOfDetail(levelsOfDetail);
        }

        private void InternalPutInternalName(string name, string number, string custom, out string internalName)
        {
            PartDocumentInstance.PutInternalName(name, number, custom, out internalName);
        }

        private void InternalPutInternalNameAndRevisionId(string internalNameToken, string revisionIdToken, out string internalName, out string revisionId)
        {
            PartDocumentInstance.PutInternalNameAndRevisionId(internalNameToken, revisionIdToken, out internalName, out revisionId);
        }

        private void InternalRebuild()
        {
            PartDocumentInstance.Rebuild();
        }

        private bool InternalRebuild2(bool acceptErrorsAndContinue)
        {
            return PartDocumentInstance.Rebuild2(acceptErrorsAndContinue);
        }

        private void InternalReleaseReference()
        {
            PartDocumentInstance.ReleaseReference();
        }

        private void InternalResolveFile()
        {
            PartDocumentInstance.ResolveFile();
        }

        private void InternalRevertReservedForWriteByMe()
        {
            PartDocumentInstance.RevertReservedForWriteByMe();
        }

        private void InternalSave()
        {
            PartDocumentInstance.Save();
        }

        private void InternalSave2(bool saveDependents, object documentsToSave)
        {
            PartDocumentInstance.Save2(saveDependents, documentsToSave);
        }

        private void InternalSaveAs(string fileName, bool saveCopyAs)
        {
            PartDocumentInstance.SaveAs(fileName, saveCopyAs);
        }

        private void InternalSaveAs2(string fullFileName, bool saveCopyAs, object options)
        {
            PartDocumentInstance.SaveAs2(fullFileName, saveCopyAs, options);
        }

        private void InternalSaveAsWithOptions(string fileName, InvNameValueMap options)
        {
            PartDocumentInstance.SaveAsWithOptions(fileName, options?.NameValueMapInstance);
        }

        private void InternalSetMissingAddInBehavior(string clientId, InvCommandTypesEnum disabledCommandTypesEnum, object disabledCommands)
        {
            PartDocumentInstance.SetMissingAddInBehavior(clientId, (Inventor.CommandTypesEnum)disabledCommandTypesEnum, disabledCommands);
        }

        private void InternalSetThumbnailSaveOption(InvThumbnailSaveOptionEnum saveOption, string imageFullFileName)
        {
            PartDocumentInstance.SetThumbnailSaveOption((Inventor.ThumbnailSaveOptionEnum)saveOption, imageFullFileName);
        }

        private void InternalUpdate()
        {
            PartDocumentInstance.Update();
        }

        private bool InternalUpdate2(bool acceptErrorsAndContinue)
        {
            return PartDocumentInstance.Update2(acceptErrorsAndContinue);
        }

        private bool InternalUpdateSubstitutePart(bool ignoreErrors)
        {
            return PartDocumentInstance.UpdateSubstitutePart(ignoreErrors);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.PartDocument PartDocumentInstance
        {
            get { return InternalPartDocument; }
            set { InternalPartDocument = value; }
        }

        public object ActivatedObject
        {
            get { return InternalActivatedObject; }
        }

        public string ActiveAnnotationsStandard
        {
            get { return InternalActiveAnnotationsStandard; }
            set { InternalActiveAnnotationsStandard = value; }
        }

        public InvAsset ActiveAppearance
        {
            get { return InternalActiveAppearance; }
            set { InternalActiveAppearance = value; }
        }

        public InvLightingStyle ActiveLightingStyle
        {
            get { return InternalActiveLightingStyle; }
            set { InternalActiveLightingStyle = value; }
        }

        public InvAsset ActiveMaterial
        {
            get { return InternalActiveMaterial; }
            set { InternalActiveMaterial = value; }
        }

        public InvRenderStyle ActiveRenderStyle
        {
            get { return InternalActiveRenderStyle; }
            set { InternalActiveRenderStyle = value; }
        }

        public InvDocumentsEnumerator AllReferencedDocuments
        {
            get { return InternalAllReferencedDocuments; }
        }

        public InvAssetsEnumerator AppearanceAssets
        {
            get { return InternalAppearanceAssets; }
        }

        public InvAssets Assets
        {
            get { return InternalAssets; }
        }

        public string AssociativeForeignFilename
        {
            get { return InternalAssociativeForeignFilename; }
        }

        public InvAttributeManager AttributeManager
        {
            get { return InternalAttributeManager; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public bool Compacted
        {
            get { return InternalCompacted; }
        }

        public InvPartComponentDefinition ComponentDefinition
        {
            get { return InternalComponentDefinition; }
        }

        public string DatabaseRevisionId
        {
            get { return InternalDatabaseRevisionId; }
        }

        public string DefaultCommand
        {
            get { return InternalDefaultCommand; }
        }

        public bool Dirty
        {
            get { return InternalDirty; }
            set { InternalDirty = value; }
        }

        public InvDisabledCommandList DisabledCommandList
        {
            get { return InternalDisabledCommandList; }
        }

        public InvCommandTypesEnum DisabledCommandTypes
        {
            get { return InternalDisabledCommandTypes; }
            set { InternalDisabledCommandTypes = value; }
        }

        public string DisplayName
        {
            get { return InternalDisplayName; }
            set { InternalDisplayName = value; }
        }

        public string DisplayNameBasis
        {
            get { return InternalDisplayNameBasis; }
            set { InternalDisplayNameBasis = value; }
        }

        public bool DisplayNameOverridden
        {
            get { return InternalDisplayNameOverridden; }
            set { InternalDisplayNameOverridden = value; }
        }

        public InvDisplaySettings DisplaySettings
        {
            get { return InternalDisplaySettings; }
        }

        public InvDocumentEvents DocumentEvents
        {
            get { return InternalDocumentEvents; }
        }

        public InvDocumentInterests DocumentInterests
        {
            get { return InternalDocumentInterests; }
        }

        public InvDocumentSubType DocumentSubType
        {
            get { return InternalDocumentSubType; }
        }

        public InvDocumentTypeEnum DocumentType
        {
            get { return InternalDocumentType; }
        }

        public InvEnvironmentManager EnvironmentManager
        {
            get { return InternalEnvironmentManager; }
        }

        public string ExplicitName
        {
            get { return InternalExplicitName; }
        }

        public InvFile File
        {
            get { return InternalFile; }
        }

        public InvPropertySets FilePropertySets
        {
            get { return InternalFilePropertySets; }
        }

        public int FileSaveCounter
        {
            get { return InternalFileSaveCounter; }
        }

        public string FullDisplayName
        {
            get { return InternalFullDisplayName; }
        }

        public string FullDocumentName
        {
            get { return InternalFullDocumentName; }
        }

        public string FullFileName
        {
            get { return InternalFullFileName; }
            set { InternalFullFileName = value; }
        }

        public bool HasReferencesMissing
        {
            get { return InternalHasReferencesMissing; }
        }

        public InvHighlightSets HighlightSets
        {
            get { return InternalHighlightSets; }
        }

        public string InternalName
        {
            get { return InternalInternalName; }
        }

        public bool IsEmbeddedDocument
        {
            get { return InternalIsEmbeddedDocument; }
        }

        public bool IsModifiable
        {
            get { return InternalIsModifiable; }
        }

        public bool IsSubstitutePart
        {
            get { return InternalIsSubstitutePart; }
            set { InternalIsSubstitutePart = value; }
        }

        public InvLightingStyles LightingStyles
        {
            get { return InternalLightingStyles; }
        }

        public InvAssetsEnumerator MaterialAssets
        {
            get { return InternalMaterialAssets; }
        }

        public InvMaterials Materials
        {
            get { return InternalMaterials; }
        }

        public string ModelStateName
        {
            get { return InternalModelStateName; }
        }

        public InvModelingSettings ModelingSettings
        {
            get { return InternalModelingSettings; }
        }

        public bool NeedsMigrating
        {
            get { return InternalNeedsMigrating; }
        }

        public InvObjectVisibility ObjectVisibility
        {
            get { return InternalObjectVisibility; }
        }

        public bool Open
        {
            get { return InternalOpen; }
        }

        public InvFileOwnershipEnum OwnershipType
        {
            get { return InternalOwnershipType; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public InvAssetsEnumerator PhysicalAssets
        {
            get { return InternalPhysicalAssets; }
        }

        public InvPrintManager PrintManager
        {
            get { return InternalPrintManager; }
        }

        public InvPropertySets PropertySets
        {
            get { return InternalPropertySets; }
        }

        public InvCommandTypesEnum RecentChanges
        {
            get { return InternalRecentChanges; }
        }

        public InvReferenceKeyManager ReferenceKeyManager
        {
            get { return InternalReferenceKeyManager; }
        }

        public InvDocumentDescriptorsEnumerator ReferencedDocumentDescriptors
        {
            get { return InternalReferencedDocumentDescriptors; }
        }

        public InvDocumentsEnumerator ReferencedDocuments
        {
            get { return InternalReferencedDocuments; }
        }

        public InvReferencedFileDescriptors ReferencedFileDescriptors
        {
            get { return InternalReferencedFileDescriptors; }
        }

        public InvDocumentsEnumerator ReferencedFiles
        {
            get { return InternalReferencedFiles; }
        }

        public InvReferencedOLEFileDescriptors ReferencedOLEFileDescriptors
        {
            get { return InternalReferencedOLEFileDescriptors; }
        }

        public InvDocumentsEnumerator ReferencingDocuments
        {
            get { return InternalReferencingDocuments; }
        }

        public InvRenderStyles RenderStyles
        {
            get { return InternalRenderStyles; }
        }

        public bool RequiresUpdate
        {
            get { return InternalRequiresUpdate; }
        }

        public bool ReservedForWrite
        {
            get { return InternalReservedForWrite; }
        }

        public bool ReservedForWriteByMe
        {
            get { return InternalReservedForWriteByMe; }
            set { InternalReservedForWriteByMe = value; }
        }

        public string ReservedForWriteLogin
        {
            get { return InternalReservedForWriteLogin; }
        }

        public string ReservedForWriteName
        {
            get { return InternalReservedForWriteName; }
        }

        public System.DateTime ReservedForWriteTime
        {
            get { return InternalReservedForWriteTime; }
        }

        public int ReservedForWriteVersion
        {
            get { return InternalReservedForWriteVersion; }
        }

        public string RevisionId
        {
            get { return InternalRevisionId; }
        }

        public InvSelectSet SelectSet
        {
            get { return InternalSelectSet; }
        }

        public InvSelectionPriorityEnum SelectionPriority
        {
            get { return InternalSelectionPriority; }
            set { InternalSelectionPriority = value; }
        }

        public bool SketchActive
        {
            get { return InternalSketchActive; }
        }

        public InvSketchSettings SketchSettings
        {
            get { return InternalSketchSettings; }
        }

        public InvSoftwareVersion SoftwareVersionCreated
        {
            get { return InternalSoftwareVersionCreated; }
        }

        public InvSoftwareVersion SoftwareVersionSaved
        {
            get { return InternalSoftwareVersionSaved; }
        }

        public string SubType
        {
            get { return InternalSubType; }
            set { InternalSubType = value; }
        }

        public InvThumbnailSaveOptionEnum ThumbnailSaveOption
        {
            get { return InternalThumbnailSaveOption; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public InvUnitsOfMeasure UnitsOfMeasure
        {
            get { return InternalUnitsOfMeasure; }
        }

        public InvInventorVBAProject VBAProject
        {
            get { return InternalVBAProject; }
        }

        public InvViews Views
        {
            get { return InternalViews; }
        }

        #endregion

        #region Public static constructors
        public static InvPartDocument ByInvPartDocument(InvPartDocument invPartDocument)
        {
            return invPartDocument == null ? null : new InvPartDocument(invPartDocument);
        }

        [SupressImportIntoVM]
        public static InvPartDocument ByInvPartDocument(Inventor.PartDocument invPartDocument)
        {
            return invPartDocument == null ? null : new InvPartDocument(invPartDocument);
        }
        #endregion

        #region Public methods
        public void Activate()
        {
            InternalActivate();
        }

        public void Close(bool skipSave)
        {
            InternalClose(skipSave);
        }

        public InvHighlightSet CreateHighlightSet()
        {
            return InternalCreateHighlightSet();
        }

        public void ExecutePromptToChoose3daStyle()
        {
            InternalExecutePromptToChoose3daStyle();
        }

        public InvDocumentsEnumerator FindWhereUsed(string fullFileName)
        {
            return InternalFindWhereUsed(fullFileName);
        }

        public object GetPrivateStorage(string storageName, bool createIfNecessary)
        {
            return InternalGetPrivateStorage(storageName, createIfNecessary);
        }

        public object GetPrivateStream(string streamName, bool createIfNecessary)
        {
            return InternalGetPrivateStream(streamName, createIfNecessary);
        }

        public bool HasPrivateStorage(string storageName)
        {
            return InternalHasPrivateStorage(storageName);
        }

        public bool HasPrivateStream(string streamName)
        {
            return InternalHasPrivateStream(streamName);
        }

        public void LockSaveSet()
        {
            InternalLockSaveSet();
        }

        public void MakeModelStateMemberModifiable()
        {
            InternalMakeModelStateMemberModifiable();
        }

        public void Migrate()
        {
            InternalMigrate();
        }

        public void PutGraphicsLevelsOfDetail(int levelsOfDetail)
        {
            InternalPutGraphicsLevelsOfDetail(levelsOfDetail);
        }

        public void PutInternalName(string name, string number, string custom, out string internalName)
        {
            InternalPutInternalName(name, number, custom, out internalName);
        }

        public void PutInternalNameAndRevisionId(string internalNameToken, string revisionIdToken, out string internalName, out string revisionId)
        {
            InternalPutInternalNameAndRevisionId(internalNameToken, revisionIdToken, out internalName, out revisionId);
        }

        public void Rebuild()
        {
            InternalRebuild();
        }

        public bool Rebuild2(bool acceptErrorsAndContinue)
        {
            return InternalRebuild2(acceptErrorsAndContinue);
        }

        public void ReleaseReference()
        {
            InternalReleaseReference();
        }

        public void ResolveFile()
        {
            InternalResolveFile();
        }

        public void RevertReservedForWriteByMe()
        {
            InternalRevertReservedForWriteByMe();
        }

        public void Save()
        {
            InternalSave();
        }

        public void Save2(bool saveDependents, object documentsToSave)
        {
            InternalSave2(saveDependents, documentsToSave);
        }

        public void SaveAs(string fileName, bool saveCopyAs)
        {
            InternalSaveAs(fileName, saveCopyAs);
        }

        public void SaveAs2(string fullFileName, bool saveCopyAs, object options)
        {
            InternalSaveAs2(fullFileName, saveCopyAs, options);
        }

        public void SaveAsWithOptions(string fileName, InvNameValueMap options)
        {
            InternalSaveAsWithOptions(fileName, options);
        }

        public void SetMissingAddInBehavior(string clientId, InvCommandTypesEnum disabledCommandTypesEnum, object disabledCommands)
        {
            InternalSetMissingAddInBehavior(clientId, disabledCommandTypesEnum, disabledCommands);
        }

        public void SetThumbnailSaveOption(InvThumbnailSaveOptionEnum saveOption, string imageFullFileName)
        {
            InternalSetThumbnailSaveOption(saveOption, imageFullFileName);
        }

        public void Update()
        {
            InternalUpdate();
        }

        public bool Update2(bool acceptErrorsAndContinue)
        {
            return InternalUpdate2(acceptErrorsAndContinue);
        }

        public bool UpdateSubstitutePart(bool ignoreErrors)
        {
            return InternalUpdateSubstitutePart(ignoreErrors);
        }

        #endregion
    }
}
