// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Plane. Do not edit; put additions in InvPlane.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvPlane
    {
        #region Internal properties
        internal Inventor.Plane InternalPlane { get; set; }

        // skipped: Evaluator: Inventor.SurfaceEvaluator is not wrapped
        internal bool InternalIsCoplanarTo(InvPlane plane, double tolerance)
        {
            return PlaneInstance.get_IsCoplanarTo(plane?.PlaneInstance, tolerance);
        }

        internal bool InternalIsParallelTo(object lineOrPlane, double tolerance)
        {
            return PlaneInstance.get_IsParallelTo(lineOrPlane, tolerance);
        }

        internal bool InternalIsPerpendicularTo(object lineOrPlane, double tolerance)
        {
            return PlaneInstance.get_IsPerpendicularTo(lineOrPlane, tolerance);
        }

        internal InvUnitVector InternalNormal
        {
            get { return InvUnitVector.ByInvUnitVector(PlaneInstance.Normal); }
            set { PlaneInstance.Normal = value?.UnitVectorInstance; }
        }

        internal InvPoint InternalRootPoint
        {
            get { return InvPoint.ByInvPoint(PlaneInstance.RootPoint); }
            set { PlaneInstance.RootPoint = value?.PointInstance; }
        }

        #endregion

        #region Private constructors
        private InvPlane(InvPlane invPlane)
        {
            InternalPlane = invPlane.InternalPlane;
        }

        private InvPlane(Inventor.Plane invPlane)
        {
            InternalPlane = invPlane;
        }
        #endregion

        #region Private methods
        private InvPlane InternalCopy()
        {
            return InvPlane.ByInvPlane(PlaneInstance.Copy());
        }

        private double InternalDistanceTo(InvPoint point)
        {
            return PlaneInstance.DistanceTo(point?.PointInstance);
        }

        private void InternalGetPlaneData(ref double[] rootPoint, ref double[] normal)
        {
            PlaneInstance.GetPlaneData(ref rootPoint, ref normal);
        }

        private InvObjectsEnumerator InternalIntersectWithCurve(object curve, double tolerance)
        {
            return InvObjectsEnumerator.ByInvObjectsEnumerator(PlaneInstance.IntersectWithCurve(curve, tolerance));
        }

        private InvPoint InternalIntersectWithLine(object line, double tolerance)
        {
            return InvPoint.ByInvPoint(PlaneInstance.IntersectWithLine(line, tolerance));
        }

        private InvLine InternalIntersectWithPlane(InvPlane plane, double tolerance)
        {
            return InvLine.ByInvLine(PlaneInstance.IntersectWithPlane(plane?.PlaneInstance, tolerance));
        }

        private InvObjectsEnumerator InternalIntersectWithSurface(object surface, double tolerance)
        {
            return InvObjectsEnumerator.ByInvObjectsEnumerator(PlaneInstance.IntersectWithSurface(surface, tolerance));
        }

        private void InternalPutPlaneData(ref double[] rootPoint, ref double[] normal)
        {
            PlaneInstance.PutPlaneData(ref rootPoint, ref normal);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Plane PlaneInstance
        {
            get { return InternalPlane; }
            set { InternalPlane = value; }
        }

        public bool IsCoplanarTo(InvPlane plane, double tolerance)
        {
            return InternalIsCoplanarTo(plane, tolerance);
        }

        public bool IsParallelTo(object lineOrPlane, double tolerance)
        {
            return InternalIsParallelTo(lineOrPlane, tolerance);
        }

        public bool IsPerpendicularTo(object lineOrPlane, double tolerance)
        {
            return InternalIsPerpendicularTo(lineOrPlane, tolerance);
        }

        public InvUnitVector Normal
        {
            get { return InternalNormal; }
            set { InternalNormal = value; }
        }

        public InvPoint RootPoint
        {
            get { return InternalRootPoint; }
            set { InternalRootPoint = value; }
        }

        #endregion

        #region Public static constructors
        public static InvPlane ByInvPlane(InvPlane invPlane)
        {
            return invPlane == null ? null : new InvPlane(invPlane);
        }

        [SupressImportIntoVM]
        public static InvPlane ByInvPlane(Inventor.Plane invPlane)
        {
            return invPlane == null ? null : new InvPlane(invPlane);
        }
        #endregion

        #region Public methods
        public InvPlane Copy()
        {
            return InternalCopy();
        }

        public double DistanceTo(InvPoint point)
        {
            return InternalDistanceTo(point);
        }

        public void GetPlaneData(ref double[] rootPoint, ref double[] normal)
        {
            InternalGetPlaneData(ref rootPoint, ref normal);
        }

        public InvObjectsEnumerator IntersectWithCurve(object curve, double tolerance)
        {
            return InternalIntersectWithCurve(curve, tolerance);
        }

        public InvPoint IntersectWithLine(object line, double tolerance)
        {
            return InternalIntersectWithLine(line, tolerance);
        }

        public InvLine IntersectWithPlane(InvPlane plane, double tolerance)
        {
            return InternalIntersectWithPlane(plane, tolerance);
        }

        public InvObjectsEnumerator IntersectWithSurface(object surface, double tolerance)
        {
            return InternalIntersectWithSurface(surface, tolerance);
        }

        public void PutPlaneData(ref double[] rootPoint, ref double[] normal)
        {
            InternalPutPlaneData(ref rootPoint, ref normal);
        }

        #endregion
    }
}
