// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Point. Do not edit; put additions in InvPoint.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvPoint
    {
        #region Internal properties
        internal Inventor.Point InternalPoint { get; set; }

        internal double InternalX
        {
            get { return PointInstance.X; }
            set { PointInstance.X = value; }
        }

        internal double InternalY
        {
            get { return PointInstance.Y; }
            set { PointInstance.Y = value; }
        }

        internal double InternalZ
        {
            get { return PointInstance.Z; }
            set { PointInstance.Z = value; }
        }

        #endregion

        #region Private constructors
        private InvPoint(InvPoint invPoint)
        {
            InternalPoint = invPoint.InternalPoint;
        }

        private InvPoint(Inventor.Point invPoint)
        {
            InternalPoint = invPoint;
        }
        #endregion

        #region Private methods
        private InvPoint InternalCopy()
        {
            return InvPoint.ByInvPoint(PointInstance.Copy());
        }

        private double InternalDistanceTo(InvPoint point)
        {
            return PointInstance.DistanceTo(point?.PointInstance);
        }

        private void InternalGetPointData(ref double[] coords)
        {
            PointInstance.GetPointData(ref coords);
        }

        private bool InternalIsEqualTo(InvPoint point, double tolerance)
        {
            return PointInstance.IsEqualTo(point?.PointInstance, tolerance);
        }

        private void InternalPutPointData(ref double[] coords)
        {
            PointInstance.PutPointData(ref coords);
        }

        private void InternalTransformBy(InvMatrix matrix)
        {
            PointInstance.TransformBy(matrix?.MatrixInstance);
        }

        private void InternalTranslateBy(InvVector vector)
        {
            PointInstance.TranslateBy(vector?.VectorInstance);
        }

        private InvVector InternalVectorTo(InvPoint point)
        {
            return InvVector.ByInvVector(PointInstance.VectorTo(point?.PointInstance));
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Point PointInstance
        {
            get { return InternalPoint; }
            set { InternalPoint = value; }
        }

        public double X
        {
            get { return InternalX; }
            set { InternalX = value; }
        }

        public double Y
        {
            get { return InternalY; }
            set { InternalY = value; }
        }

        public double Z
        {
            get { return InternalZ; }
            set { InternalZ = value; }
        }

        #endregion

        #region Public static constructors
        public static InvPoint ByInvPoint(InvPoint invPoint)
        {
            return invPoint == null ? null : new InvPoint(invPoint);
        }

        [SupressImportIntoVM]
        public static InvPoint ByInvPoint(Inventor.Point invPoint)
        {
            return invPoint == null ? null : new InvPoint(invPoint);
        }
        #endregion

        #region Public methods
        public InvPoint Copy()
        {
            return InternalCopy();
        }

        public double DistanceTo(InvPoint point)
        {
            return InternalDistanceTo(point);
        }

        public void GetPointData(ref double[] coords)
        {
            InternalGetPointData(ref coords);
        }

        public bool IsEqualTo(InvPoint point, double tolerance)
        {
            return InternalIsEqualTo(point, tolerance);
        }

        public void PutPointData(ref double[] coords)
        {
            InternalPutPointData(ref coords);
        }

        public void TransformBy(InvMatrix matrix)
        {
            InternalTransformBy(matrix);
        }

        public void TranslateBy(InvVector vector)
        {
            InternalTranslateBy(vector);
        }

        public InvVector VectorTo(InvPoint point)
        {
            return InternalVectorTo(point);
        }

        #endregion
    }
}
