// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Parameter. Do not edit; put additions in InvParameter.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvParameter
    {
        #region Internal properties
        internal Inventor.Parameter InternalParameter { get; set; }

        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(ParameterInstance.AttributeSets); }
        }

        internal string InternalComment
        {
            get { return ParameterInstance.Comment; }
            set { ParameterInstance.Comment = value; }
        }

        // skipped: CustomPropertyFormat: Inventor.CustomPropertyFormat is not wrapped
        internal InvObjectCollection InternalDependents
        {
            get { return InvObjectCollection.ByInvObjectCollection(ParameterInstance.Dependents); }
        }

        internal InvActionTypeEnum InternalDisabledActionTypes
        {
            get { return (InvActionTypeEnum)ParameterInstance.DisabledActionTypes; }
            set { ParameterInstance.DisabledActionTypes = (Inventor.ActionTypeEnum)value; }
        }

        // skipped: DisplayFormat: Inventor.ParameterDisplayFormatEnum is not wrapped
        internal InvObjectCollection InternalDrivenBy
        {
            get { return InvObjectCollection.ByInvObjectCollection(ParameterInstance.DrivenBy); }
        }

        internal bool InternalExposedAsProperty
        {
            get { return ParameterInstance.ExposedAsProperty; }
            set { ParameterInstance.ExposedAsProperty = value; }
        }

        internal string InternalExpression
        {
            get { return ParameterInstance.Expression; }
            set { ParameterInstance.Expression = value; }
        }

        // skipped: ExpressionList: Inventor.ExpressionList is not wrapped
        internal InvHealthStatusEnum InternalHealthStatus
        {
            get { return (InvHealthStatusEnum)ParameterInstance.HealthStatus; }
        }

        internal bool InternalInUse
        {
            get { return ParameterInstance.InUse; }
        }

        internal bool InternalIsKey
        {
            get { return ParameterInstance.IsKey; }
            set { ParameterInstance.IsKey = value; }
        }

        internal double InternalModelValue
        {
            get { return ParameterInstance.ModelValue; }
        }

        // skipped: ModelValueType: Inventor.ModelValueTypeEnum is not wrapped
        internal string InternalName
        {
            get { return ParameterInstance.Name; }
            set { ParameterInstance.Name = value; }
        }

        internal InvParameterTypeEnum InternalParameterType
        {
            get { return (InvParameterTypeEnum)ParameterInstance.ParameterType; }
        }

        internal object InternalParent
        {
            get { return ParameterInstance.Parent; }
        }

        internal int InternalPrecision
        {
            get { return ParameterInstance.Precision; }
            set { ParameterInstance.Precision = value; }
        }

        // skipped: Tolerance: Inventor.Tolerance is not wrapped
        internal string InternalToleranceInfo
        {
            get { return ParameterInstance.ToleranceInfo; }
            set { ParameterInstance.ToleranceInfo = value; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ParameterInstance.Type; }
        }

        internal string InternalUnits
        {
            get { return ParameterInstance.get_Units(); }
        }

        internal void InternalUnitsSet(object value)
        {
            ParameterInstance.set_Units(value);
        }

        internal object InternalValue
        {
            get { return ParameterInstance.Value; }
            set { ParameterInstance.Value = value; }
        }

        internal bool InternalVisible
        {
            get { return ParameterInstance.Visible; }
            set { ParameterInstance.Visible = value; }
        }

        #endregion

        #region Private constructors
        private InvParameter(InvParameter invParameter)
        {
            InternalParameter = invParameter.InternalParameter;
        }

        private InvParameter(Inventor.Parameter invParameter)
        {
            InternalParameter = invParameter;
        }
        #endregion

        #region Private methods
        private void InternalDelete()
        {
            ParameterInstance.Delete();
        }

        private void InternalGetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            ParameterInstance.GetReferenceKey(ref referenceKey, keyContext);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Parameter ParameterInstance
        {
            get { return InternalParameter; }
            set { InternalParameter = value; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public string Comment
        {
            get { return InternalComment; }
            set { InternalComment = value; }
        }

        public InvObjectCollection Dependents
        {
            get { return InternalDependents; }
        }

        public InvActionTypeEnum DisabledActionTypes
        {
            get { return InternalDisabledActionTypes; }
            set { InternalDisabledActionTypes = value; }
        }

        public InvObjectCollection DrivenBy
        {
            get { return InternalDrivenBy; }
        }

        public bool ExposedAsProperty
        {
            get { return InternalExposedAsProperty; }
            set { InternalExposedAsProperty = value; }
        }

        public string Expression
        {
            get { return InternalExpression; }
            set { InternalExpression = value; }
        }

        public InvHealthStatusEnum HealthStatus
        {
            get { return InternalHealthStatus; }
        }

        public bool InUse
        {
            get { return InternalInUse; }
        }

        public bool IsKey
        {
            get { return InternalIsKey; }
            set { InternalIsKey = value; }
        }

        public double ModelValue
        {
            get { return InternalModelValue; }
        }

        public string Name
        {
            get { return InternalName; }
            set { InternalName = value; }
        }

        public InvParameterTypeEnum ParameterType
        {
            get { return InternalParameterType; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public int Precision
        {
            get { return InternalPrecision; }
            set { InternalPrecision = value; }
        }

        public string ToleranceInfo
        {
            get { return InternalToleranceInfo; }
            set { InternalToleranceInfo = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public string Units
        {
            get { return InternalUnits; }
        }

        public void SetUnits(object value)
        {
            InternalUnitsSet(value);
        }

        public object Value
        {
            get { return InternalValue; }
            set { InternalValue = value; }
        }

        public bool Visible
        {
            get { return InternalVisible; }
            set { InternalVisible = value; }
        }

        #endregion

        #region Public static constructors
        public static InvParameter ByInvParameter(InvParameter invParameter)
        {
            return invParameter == null ? null : new InvParameter(invParameter);
        }

        [SupressImportIntoVM]
        public static InvParameter ByInvParameter(Inventor.Parameter invParameter)
        {
            return invParameter == null ? null : new InvParameter(invParameter);
        }
        #endregion

        #region Public methods
        public void Delete()
        {
            InternalDelete();
        }

        public void GetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            InternalGetReferenceKey(ref referenceKey, keyContext);
        }

        #endregion
    }
}
