// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ParameterTypeEnum. Do not edit; put additions in InvParameterTypeEnum.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public enum InvParameterTypeEnum
    {
        kDerivedParameter = Inventor.ParameterTypeEnum.kDerivedParameter,
        kFinishParameter = Inventor.ParameterTypeEnum.kFinishParameter,
        kModelParameter = Inventor.ParameterTypeEnum.kModelParameter,
        kReferenceParameter = Inventor.ParameterTypeEnum.kReferenceParameter,
        kTableParameter = Inventor.ParameterTypeEnum.kTableParameter,
        kUserParameter = Inventor.ParameterTypeEnum.kUserParameter
    }
}
