// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.PartComponentDefinition. Do not edit; put additions in InvPartComponentDefinition.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvPartComponentDefinition
    {
        #region Internal properties
        internal Inventor.PartComponentDefinition InternalPartComponentDefinition { get; set; }

        // skipped: AnalysisManager: Inventor.AnalysisManager is not wrapped
        // skipped: AnnotationPlanes: Inventor.AnnotationPlanes is not wrapped
        internal InvObjectsEnumerator InternalAppearanceOverridesObjects
        {
            get { return InvObjectsEnumerator.ByInvObjectsEnumerator(PartComponentDefinitionInstance.AppearanceOverridesObjects); }
        }

        internal object InternalApplication
        {
            get { return PartComponentDefinitionInstance.Application; }
        }

        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(PartComponentDefinitionInstance.AttributeSets); }
        }

        // skipped: BIMComponent: Inventor.BIMComponent is not wrapped
        // skipped: BOMQuantity: Inventor.BOMQuantity is not wrapped
        internal InvBOMStructureEnum InternalBOMStructure
        {
            get { return (InvBOMStructureEnum)PartComponentDefinitionInstance.BOMStructure; }
            set { PartComponentDefinitionInstance.BOMStructure = (Inventor.BOMStructureEnum)value; }
        }

        // skipped: ClientGraphicsCollection: Inventor.ClientGraphicsCollection is not wrapped
        internal bool InternalCompactModelHistory
        {
            get { return PartComponentDefinitionInstance.CompactModelHistory; }
            set { PartComponentDefinitionInstance.CompactModelHistory = value; }
        }

        internal bool InternalCompactModelHistoryOnNextSave
        {
            get { return PartComponentDefinitionInstance.CompactModelHistoryOnNextSave; }
            set { PartComponentDefinitionInstance.CompactModelHistoryOnNextSave = value; }
        }

        // skipped: DataIO: Inventor.DataIO is not wrapped
        internal object InternalDocument
        {
            get { return PartComponentDefinitionInstance.Document; }
        }

        // skipped: FactoryDocument: Inventor._Document is not wrapped
        // skipped: Features: Inventor.PartFeatures is not wrapped
        internal bool InternalHasDesignProblems
        {
            get { return PartComponentDefinitionInstance.HasDesignProblems; }
        }

        internal bool InternalHasMultipleSolidBodies
        {
            get { return PartComponentDefinitionInstance.HasMultipleSolidBodies; }
        }

        // skipped: ImmediateReferencedDefinitions: Inventor.ComponentDefinitionReferences is not wrapped
        internal bool InternalIsContentMember
        {
            get { return PartComponentDefinitionInstance.IsContentMember; }
        }

        internal bool InternalIsModelStateFactory
        {
            get { return PartComponentDefinitionInstance.IsModelStateFactory; }
        }

        internal bool InternalIsModelStateMember
        {
            get { return PartComponentDefinitionInstance.IsModelStateMember; }
        }

        internal bool InternalIsiPartFactory
        {
            get { return PartComponentDefinitionInstance.IsiPartFactory; }
        }

        internal bool InternalIsiPartMember
        {
            get { return PartComponentDefinitionInstance.IsiPartMember; }
        }

        // skipped: MassProperties: Inventor.MassProperties is not wrapped
        internal InvMaterial InternalMaterial
        {
            get { return InvMaterial.ByInvMaterial(PartComponentDefinitionInstance.Material); }
            set { PartComponentDefinitionInstance.Material = value?.MaterialInstance; }
        }

        // skipped: MeshFeatureSets: Inventor.MeshFeatureSets is not wrapped
        // skipped: ModelAnnotations: Inventor.ModelAnnotations is not wrapped
        // skipped: ModelDatumFeatures: Inventor.ModelDatumFeaturesEnumerator is not wrapped
        // skipped: ModelDatumReferenceFrames: Inventor.ModelDatumReferenceFrames is not wrapped
        internal string InternalModelGeometryVersion
        {
            get { return PartComponentDefinitionInstance.ModelGeometryVersion; }
        }

        // skipped: ModelStates: Inventor.ModelStates is not wrapped
        // skipped: ModelToleranceFeatures: Inventor.ModelToleranceFeatures is not wrapped
        internal InvComponentOccurrences InternalOccurrences
        {
            get { return InvComponentOccurrences.ByInvComponentOccurrences(PartComponentDefinitionInstance.Occurrences); }
        }

        internal InvOrientedBox InternalOrientedMinimumRangeBox
        {
            get { return InvOrientedBox.ByInvOrientedBox(PartComponentDefinitionInstance.OrientedMinimumRangeBox); }
        }

        internal InvParameters InternalParameters
        {
            get { return InvParameters.ByInvParameters(PartComponentDefinitionInstance.Parameters); }
        }

        // skipped: PartEvents: Inventor.PartEvents is not wrapped
        // skipped: PointClouds: Inventor.PointClouds is not wrapped
        internal InvBox InternalPreciseRangeBox
        {
            get { return InvBox.ByInvBox(PartComponentDefinitionInstance.PreciseRangeBox); }
        }

        internal InvBox InternalRangeBox
        {
            get { return InvBox.ByInvBox(PartComponentDefinitionInstance.RangeBox); }
        }

        // skipped: ReferenceComponents: Inventor.ReferenceComponents is not wrapped
        // skipped: RepresentationsManager: Inventor.RepresentationsManager is not wrapped
        internal bool InternalRolledBackForEdit
        {
            get { return PartComponentDefinitionInstance.RolledBackForEdit; }
        }

        // skipped: SketchBlockDefinitions: Inventor.SketchBlockDefinitions is not wrapped
        // skipped: Sketches: Inventor.PlanarSketches is not wrapped
        // skipped: Sketches3D: Inventor.Sketches3D is not wrapped
        internal InvSurfaceBodies InternalSurfaceBodies
        {
            get { return InvSurfaceBodies.ByInvSurfaceBodies(PartComponentDefinitionInstance.SurfaceBodies); }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)PartComponentDefinitionInstance.Type; }
        }

        // skipped: UserCoordinateSystems: Inventor.UserCoordinateSystems is not wrapped
        internal InvWorkAxes InternalWorkAxes
        {
            get { return InvWorkAxes.ByInvWorkAxes(PartComponentDefinitionInstance.WorkAxes); }
        }

        internal InvWorkPlanes InternalWorkPlanes
        {
            get { return InvWorkPlanes.ByInvWorkPlanes(PartComponentDefinitionInstance.WorkPlanes); }
        }

        internal InvWorkPoints InternalWorkPoints
        {
            get { return InvWorkPoints.ByInvWorkPoints(PartComponentDefinitionInstance.WorkPoints); }
        }

        // skipped: WorkPointsEnumerator: Inventor.WorkPointsEnumerator is not wrapped
        // skipped: WorkSurfaces: Inventor.WorkSurfaces is not wrapped
        // skipped: iMateDefinitions: Inventor.iMateDefinitions is not wrapped
        // skipped: iPartFactory: Inventor.iPartFactory is not wrapped
        // skipped: iPartMember: Inventor.iPartMember is not wrapped
        #endregion

        #region Private constructors
        private InvPartComponentDefinition(InvPartComponentDefinition invPartComponentDefinition)
        {
            InternalPartComponentDefinition = invPartComponentDefinition.InternalPartComponentDefinition;
        }

        private InvPartComponentDefinition(Inventor.PartComponentDefinition invPartComponentDefinition)
        {
            InternalPartComponentDefinition = invPartComponentDefinition;
        }
        #endregion

        #region Private methods
        private void InternalClearAppearanceOverrides(object appearanceOverrideObjects)
        {
            PartComponentDefinitionInstance.ClearAppearanceOverrides(appearanceOverrideObjects);
        }

        // skipped: CreateFactory(): returns Inventor.iPartFactory, not wrapped
        // skipped: CreateGeometryIntent(): returns Inventor.GeometryIntent, not wrapped
        private void InternalDeleteObjects(InvObjectCollection objects, bool retainConsumedSketches, bool retainDepFeatsAndSketches, bool retainDepWorkFeats)
        {
            PartComponentDefinitionInstance.DeleteObjects(objects?.ObjectCollectionInstance, retainConsumedSketches, retainDepFeatsAndSketches, retainDepWorkFeats);
        }

        private void InternalExportObjects(InvObjectCollection objects)
        {
            PartComponentDefinitionInstance.ExportObjects(objects?.ObjectCollectionInstance);
        }

        // skipped: FindUsingPoint(): parameter ObjectTypes is Inventor.SelectionFilterEnum[], not wrapped
        // skipped: FindUsingRay(): parameter FoundEntities is a ref/out Inventor.ObjectsEnumerator
        // skipped: FindUsingVector(): parameter ObjectTypes is Inventor.SelectionFilterEnum[], not wrapped
        private void InternalGetEndOfPartPosition(out object after, out object before)
        {
            PartComponentDefinitionInstance.GetEndOfPartPosition(out after, out before);
        }

        // skipped: GetUnusedGeometries(): parameter UnusedGeometries is a ref/out Inventor.ObjectCollection
        private void InternalPurgeUnusedGeometries(object unusedGeometries)
        {
            PartComponentDefinitionInstance.PurgeUnusedGeometries(unusedGeometries);
        }

        private void InternalRepositionObject(object targetObject, bool before, object startObject, object endObject)
        {
            PartComponentDefinitionInstance.RepositionObject(targetObject, before, startObject, endObject);
        }

        private void InternalSetEndOfPartToTopOrBottom(bool setToTop)
        {
            PartComponentDefinitionInstance.SetEndOfPartToTopOrBottom(setToTop);
        }

        private void InternalSuppressFeatures(InvObjectCollection features)
        {
            PartComponentDefinitionInstance.SuppressFeatures(features?.ObjectCollectionInstance);
        }

        private void InternalUnsuppressFeatures(InvObjectCollection features)
        {
            PartComponentDefinitionInstance.UnsuppressFeatures(features?.ObjectCollectionInstance);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.PartComponentDefinition PartComponentDefinitionInstance
        {
            get { return InternalPartComponentDefinition; }
            set { InternalPartComponentDefinition = value; }
        }

        public InvObjectsEnumerator AppearanceOverridesObjects
        {
            get { return InternalAppearanceOverridesObjects; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public InvBOMStructureEnum BOMStructure
        {
            get { return InternalBOMStructure; }
            set { InternalBOMStructure = value; }
        }

        public bool CompactModelHistory
        {
            get { return InternalCompactModelHistory; }
            set { InternalCompactModelHistory = value; }
        }

        public bool CompactModelHistoryOnNextSave
        {
            get { return InternalCompactModelHistoryOnNextSave; }
            set { InternalCompactModelHistoryOnNextSave = value; }
        }

        public object Document
        {
            get { return InternalDocument; }
        }

        public bool HasDesignProblems
        {
            get { return InternalHasDesignProblems; }
        }

        public bool HasMultipleSolidBodies
        {
            get { return InternalHasMultipleSolidBodies; }
        }

        public bool IsContentMember
        {
            get { return InternalIsContentMember; }
        }

        public bool IsModelStateFactory
        {
            get { return InternalIsModelStateFactory; }
        }

        public bool IsModelStateMember
        {
            get { return InternalIsModelStateMember; }
        }

        public bool IsiPartFactory
        {
            get { return InternalIsiPartFactory; }
        }

        public bool IsiPartMember
        {
            get { return InternalIsiPartMember; }
        }

        public InvMaterial Material
        {
            get { return InternalMaterial; }
            set { InternalMaterial = value; }
        }

        public string ModelGeometryVersion
        {
            get { return InternalModelGeometryVersion; }
        }

        public InvComponentOccurrences Occurrences
        {
            get { return InternalOccurrences; }
        }

        public InvOrientedBox OrientedMinimumRangeBox
        {
            get { return InternalOrientedMinimumRangeBox; }
        }

        public InvParameters Parameters
        {
            get { return InternalParameters; }
        }

        public InvBox PreciseRangeBox
        {
            get { return InternalPreciseRangeBox; }
        }

        public InvBox RangeBox
        {
            get { return InternalRangeBox; }
        }

        public bool RolledBackForEdit
        {
            get { return InternalRolledBackForEdit; }
        }

        public InvSurfaceBodies SurfaceBodies
        {
            get { return InternalSurfaceBodies; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public InvWorkAxes WorkAxes
        {
            get { return InternalWorkAxes; }
        }

        public InvWorkPlanes WorkPlanes
        {
            get { return InternalWorkPlanes; }
        }

        public InvWorkPoints WorkPoints
        {
            get { return InternalWorkPoints; }
        }

        #endregion

        #region Public static constructors
        public static InvPartComponentDefinition ByInvPartComponentDefinition(InvPartComponentDefinition invPartComponentDefinition)
        {
            return invPartComponentDefinition == null ? null : new InvPartComponentDefinition(invPartComponentDefinition);
        }

        [SupressImportIntoVM]
        public static InvPartComponentDefinition ByInvPartComponentDefinition(Inventor.PartComponentDefinition invPartComponentDefinition)
        {
            return invPartComponentDefinition == null ? null : new InvPartComponentDefinition(invPartComponentDefinition);
        }
        #endregion

        #region Public methods
        public void ClearAppearanceOverrides(object appearanceOverrideObjects)
        {
            InternalClearAppearanceOverrides(appearanceOverrideObjects);
        }

        public void DeleteObjects(InvObjectCollection objects, bool retainConsumedSketches, bool retainDepFeatsAndSketches, bool retainDepWorkFeats)
        {
            InternalDeleteObjects(objects, retainConsumedSketches, retainDepFeatsAndSketches, retainDepWorkFeats);
        }

        public void ExportObjects(InvObjectCollection objects)
        {
            InternalExportObjects(objects);
        }

        public void GetEndOfPartPosition(out object after, out object before)
        {
            InternalGetEndOfPartPosition(out after, out before);
        }

        public void PurgeUnusedGeometries(object unusedGeometries)
        {
            InternalPurgeUnusedGeometries(unusedGeometries);
        }

        public void RepositionObject(object targetObject, bool before, object startObject, object endObject)
        {
            InternalRepositionObject(targetObject, before, startObject, endObject);
        }

        public void SetEndOfPartToTopOrBottom(bool setToTop)
        {
            InternalSetEndOfPartToTopOrBottom(setToTop);
        }

        public void SuppressFeatures(InvObjectCollection features)
        {
            InternalSuppressFeatures(features);
        }

        public void UnsuppressFeatures(InvObjectCollection features)
        {
            InternalUnsuppressFeatures(features);
        }

        #endregion
    }
}
