// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.PrintManager. Do not edit; put additions in InvPrintManager.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvPrintManager
    {
        #region Internal properties
        internal Inventor.PrintManager InternalPrintManager { get; set; }

        internal object InternalApplication
        {
            get { return PrintManagerInstance.Application; }
        }

        // skipped: ColorMode: Inventor.PrintColorModeEnum is not wrapped
        internal int InternalNumberOfCopies
        {
            get { return PrintManagerInstance.NumberOfCopies; }
            set { PrintManagerInstance.NumberOfCopies = value; }
        }

        // skipped: Orientation: Inventor.PrintOrientationEnum is not wrapped
        internal double InternalPaperHeight
        {
            get { return PrintManagerInstance.PaperHeight; }
            set { PrintManagerInstance.PaperHeight = value; }
        }

        // skipped: PaperSize: Inventor.PaperSizeEnum is not wrapped
        internal int InternalPaperSource
        {
            get { return PrintManagerInstance.PaperSource; }
            set { PrintManagerInstance.PaperSource = value; }
        }

        internal double InternalPaperWidth
        {
            get { return PrintManagerInstance.PaperWidth; }
            set { PrintManagerInstance.PaperWidth = value; }
        }

        internal string InternalPrinter
        {
            get { return PrintManagerInstance.Printer; }
            set { PrintManagerInstance.Printer = value; }
        }

        internal int InternalPrinterDeviceContext
        {
            get { return PrintManagerInstance.PrinterDeviceContext; }
            set { PrintManagerInstance.PrinterDeviceContext = value; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)PrintManagerInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvPrintManager(InvPrintManager invPrintManager)
        {
            InternalPrintManager = invPrintManager.InternalPrintManager;
        }

        private InvPrintManager(Inventor.PrintManager invPrintManager)
        {
            InternalPrintManager = invPrintManager;
        }
        #endregion

        #region Private methods
        private void InternalPrintToFile(string fileName)
        {
            PrintManagerInstance.PrintToFile(fileName);
        }

        // skipped: SetCurrentView(): parameter CurrentView is Inventor.ClientView, not wrapped
        private void InternalSubmitPrint()
        {
            PrintManagerInstance.SubmitPrint();
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.PrintManager PrintManagerInstance
        {
            get { return InternalPrintManager; }
            set { InternalPrintManager = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int NumberOfCopies
        {
            get { return InternalNumberOfCopies; }
            set { InternalNumberOfCopies = value; }
        }

        public double PaperHeight
        {
            get { return InternalPaperHeight; }
            set { InternalPaperHeight = value; }
        }

        public int PaperSource
        {
            get { return InternalPaperSource; }
            set { InternalPaperSource = value; }
        }

        public double PaperWidth
        {
            get { return InternalPaperWidth; }
            set { InternalPaperWidth = value; }
        }

        public string Printer
        {
            get { return InternalPrinter; }
            set { InternalPrinter = value; }
        }

        public int PrinterDeviceContext
        {
            get { return InternalPrinterDeviceContext; }
            set { InternalPrinterDeviceContext = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvPrintManager ByInvPrintManager(InvPrintManager invPrintManager)
        {
            return invPrintManager == null ? null : new InvPrintManager(invPrintManager);
        }

        [SupressImportIntoVM]
        public static InvPrintManager ByInvPrintManager(Inventor.PrintManager invPrintManager)
        {
            return invPrintManager == null ? null : new InvPrintManager(invPrintManager);
        }
        #endregion

        #region Public methods
        public void PrintToFile(string fileName)
        {
            InternalPrintToFile(fileName);
        }

        public void SubmitPrint()
        {
            InternalSubmitPrint();
        }

        #endregion
    }
}
