// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.Parameters. Do not edit; put additions in InvParameters.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvParameters
    {
        #region Internal properties
        internal Inventor.Parameters InternalParameters { get; set; }

        internal int InternalAngularDimensionPrecision
        {
            get { return ParametersInstance.AngularDimensionPrecision; }
            set { ParametersInstance.AngularDimensionPrecision = value; }
        }

        internal string InternalAngularStandardTolerance(int precision)
        {
            return ParametersInstance.get_AngularStandardTolerance(precision);
        }

        internal int InternalCount
        {
            get { return ParametersInstance.Count; }
        }

        // skipped: CustomParameterGroups: Inventor.CustomParameterGroups is not wrapped
        // skipped: DerivedParameterTables: Inventor.DerivedParameterTables is not wrapped
        // skipped: DimensionDisplayType: Inventor.DimensionDisplayTypeEnum is not wrapped
        internal bool InternalDisplayParameterAsExpression
        {
            get { return ParametersInstance.DisplayParameterAsExpression; }
            set { ParametersInstance.DisplayParameterAsExpression = value; }
        }

        internal bool InternalExportStandardTolerances
        {
            get { return ParametersInstance.ExportStandardTolerances; }
            set { ParametersInstance.ExportStandardTolerances = value; }
        }

        // skipped: FinishParameters: Inventor.FinishParameters is not wrapped
        internal InvParameter InternalItem(object index)
        {
            return InvParameter.ByInvParameter(ParametersInstance[index]);
        }

        internal int InternalLinearDimensionPrecision
        {
            get { return ParametersInstance.LinearDimensionPrecision; }
            set { ParametersInstance.LinearDimensionPrecision = value; }
        }

        internal string InternalLinearStandardTolerance(int precision)
        {
            return ParametersInstance.get_LinearStandardTolerance(precision);
        }

        internal InvModelParameters InternalModelParameters
        {
            get { return InvModelParameters.ByInvModelParameters(ParametersInstance.ModelParameters); }
        }

        // skipped: ParameterTables: Inventor.ParameterTables is not wrapped
        // skipped: ReferenceParameters: Inventor.ReferenceParameters is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ParametersInstance.Type; }
        }

        internal bool InternalUseStandardTolerances
        {
            get { return ParametersInstance.UseStandardTolerances; }
            set { ParametersInstance.UseStandardTolerances = value; }
        }

        internal InvUserParameters InternalUserParameters
        {
            get { return InvUserParameters.ByInvUserParameters(ParametersInstance.UserParameters); }
        }

        #endregion

        #region Private constructors
        private InvParameters(InvParameters invParameters)
        {
            InternalParameters = invParameters.InternalParameters;
        }

        private InvParameters(Inventor.Parameters invParameters)
        {
            InternalParameters = invParameters;
        }
        #endregion

        #region Private methods
        private void InternalExportToXML(string fileName, object options)
        {
            ParametersInstance.ExportToXML(fileName, options);
        }

        private void InternalExportToXMLWithStatus(string fileName, out bool isNoop, object options)
        {
            ParametersInstance.ExportToXMLWithStatus(fileName, out isNoop, options);
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        private object InternalGetValueFromExpression(string expression, object unitsSpecifier)
        {
            return ParametersInstance.GetValueFromExpression(expression, unitsSpecifier);
        }

        private void InternalImportFromXML(string fileName)
        {
            ParametersInstance.ImportFromXML(fileName);
        }

        private void InternalImportFromXMLWithStatus(string fileName, out string[] failedParameters)
        {
            ParametersInstance.ImportFromXMLWithStatus(fileName, out failedParameters);
        }

        private bool InternalIsExpressionValid(string expression, object unitsSpecifier)
        {
            return ParametersInstance.IsExpressionValid(expression, unitsSpecifier);
        }

        private void InternalSetAllToMax()
        {
            ParametersInstance.SetAllToMax();
        }

        private void InternalSetAllToMedian()
        {
            ParametersInstance.SetAllToMedian();
        }

        private void InternalSetAllToMin()
        {
            ParametersInstance.SetAllToMin();
        }

        private void InternalSetAllToNominal()
        {
            ParametersInstance.SetAllToNominal();
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.Parameters ParametersInstance
        {
            get { return InternalParameters; }
            set { InternalParameters = value; }
        }

        public int AngularDimensionPrecision
        {
            get { return InternalAngularDimensionPrecision; }
            set { InternalAngularDimensionPrecision = value; }
        }

        public string AngularStandardTolerance(int precision)
        {
            return InternalAngularStandardTolerance(precision);
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public bool DisplayParameterAsExpression
        {
            get { return InternalDisplayParameterAsExpression; }
            set { InternalDisplayParameterAsExpression = value; }
        }

        public bool ExportStandardTolerances
        {
            get { return InternalExportStandardTolerances; }
            set { InternalExportStandardTolerances = value; }
        }

        public InvParameter Item(object index)
        {
            return InternalItem(index);
        }

        public int LinearDimensionPrecision
        {
            get { return InternalLinearDimensionPrecision; }
            set { InternalLinearDimensionPrecision = value; }
        }

        public string LinearStandardTolerance(int precision)
        {
            return InternalLinearStandardTolerance(precision);
        }

        public InvModelParameters ModelParameters
        {
            get { return InternalModelParameters; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public bool UseStandardTolerances
        {
            get { return InternalUseStandardTolerances; }
            set { InternalUseStandardTolerances = value; }
        }

        public InvUserParameters UserParameters
        {
            get { return InternalUserParameters; }
        }

        #endregion

        #region Public static constructors
        public static InvParameters ByInvParameters(InvParameters invParameters)
        {
            return invParameters == null ? null : new InvParameters(invParameters);
        }

        [SupressImportIntoVM]
        public static InvParameters ByInvParameters(Inventor.Parameters invParameters)
        {
            return invParameters == null ? null : new InvParameters(invParameters);
        }
        #endregion

        #region Public methods
        public void ExportToXML(string fileName, object options)
        {
            InternalExportToXML(fileName, options);
        }

        public void ExportToXMLWithStatus(string fileName, out bool isNoop, object options)
        {
            InternalExportToXMLWithStatus(fileName, out isNoop, options);
        }

        public object GetValueFromExpression(string expression, object unitsSpecifier)
        {
            return InternalGetValueFromExpression(expression, unitsSpecifier);
        }

        public void ImportFromXML(string fileName)
        {
            InternalImportFromXML(fileName);
        }

        public void ImportFromXMLWithStatus(string fileName, out string[] failedParameters)
        {
            InternalImportFromXMLWithStatus(fileName, out failedParameters);
        }

        public bool IsExpressionValid(string expression, object unitsSpecifier)
        {
            return InternalIsExpressionValid(expression, unitsSpecifier);
        }

        public void SetAllToMax()
        {
            InternalSetAllToMax();
        }

        public void SetAllToMedian()
        {
            InternalSetAllToMedian();
        }

        public void SetAllToMin()
        {
            InternalSetAllToMin();
        }

        public void SetAllToNominal()
        {
            InternalSetAllToNominal();
        }

        #endregion
    }
}
