// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ReferenceKeyManager. Do not edit; put additions in InvReferenceKeyManager.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvReferenceKeyManager
    {
        #region Internal properties
        internal Inventor.ReferenceKeyManager InternalReferenceKeyManager { get; set; }

        internal object InternalApplication
        {
            get { return ReferenceKeyManagerInstance.Application; }
        }

        internal object InternalParent
        {
            get { return ReferenceKeyManagerInstance.Parent; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ReferenceKeyManagerInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvReferenceKeyManager(InvReferenceKeyManager invReferenceKeyManager)
        {
            InternalReferenceKeyManager = invReferenceKeyManager.InternalReferenceKeyManager;
        }

        private InvReferenceKeyManager(Inventor.ReferenceKeyManager invReferenceKeyManager)
        {
            InternalReferenceKeyManager = invReferenceKeyManager;
        }
        #endregion

        #region Private methods
        private object InternalBindKeyToObject(ref byte[] referenceKey, int keyContext, out object matchType)
        {
            return ReferenceKeyManagerInstance.BindKeyToObject(ref referenceKey, keyContext, out matchType);
        }

        private bool InternalCanBindKeyToObject(ref byte[] referenceKey, int keyContext, out object @object, out object context)
        {
            return ReferenceKeyManagerInstance.CanBindKeyToObject(ref referenceKey, keyContext, out @object, out context);
        }

        private int InternalCreateKeyContext()
        {
            return ReferenceKeyManagerInstance.CreateKeyContext();
        }

        private string InternalKeyToString(ref byte[] referenceKey)
        {
            return ReferenceKeyManagerInstance.KeyToString(ref referenceKey);
        }

        private int InternalLoadContextFromArray(ref byte[] contextData)
        {
            return ReferenceKeyManagerInstance.LoadContextFromArray(ref contextData);
        }

        private void InternalReleaseKeyContext(int keyContext)
        {
            ReferenceKeyManagerInstance.ReleaseKeyContext(keyContext);
        }

        private void InternalSaveContextToArray(int keyContext, ref byte[] result)
        {
            ReferenceKeyManagerInstance.SaveContextToArray(keyContext, ref result);
        }

        private void InternalStringToKey(string referenceKeyString, ref byte[] referenceKey)
        {
            ReferenceKeyManagerInstance.StringToKey(referenceKeyString, ref referenceKey);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ReferenceKeyManager ReferenceKeyManagerInstance
        {
            get { return InternalReferenceKeyManager; }
            set { InternalReferenceKeyManager = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvReferenceKeyManager ByInvReferenceKeyManager(InvReferenceKeyManager invReferenceKeyManager)
        {
            return invReferenceKeyManager == null ? null : new InvReferenceKeyManager(invReferenceKeyManager);
        }

        [SupressImportIntoVM]
        public static InvReferenceKeyManager ByInvReferenceKeyManager(Inventor.ReferenceKeyManager invReferenceKeyManager)
        {
            return invReferenceKeyManager == null ? null : new InvReferenceKeyManager(invReferenceKeyManager);
        }
        #endregion

        #region Public methods
        public object BindKeyToObject(ref byte[] referenceKey, int keyContext, out object matchType)
        {
            return InternalBindKeyToObject(ref referenceKey, keyContext, out matchType);
        }

        public bool CanBindKeyToObject(ref byte[] referenceKey, int keyContext, out object @object, out object context)
        {
            return InternalCanBindKeyToObject(ref referenceKey, keyContext, out @object, out context);
        }

        public int CreateKeyContext()
        {
            return InternalCreateKeyContext();
        }

        public string KeyToString(ref byte[] referenceKey)
        {
            return InternalKeyToString(ref referenceKey);
        }

        public int LoadContextFromArray(ref byte[] contextData)
        {
            return InternalLoadContextFromArray(ref contextData);
        }

        public void ReleaseKeyContext(int keyContext)
        {
            InternalReleaseKeyContext(keyContext);
        }

        public void SaveContextToArray(int keyContext, ref byte[] result)
        {
            InternalSaveContextToArray(keyContext, ref result);
        }

        public void StringToKey(string referenceKeyString, ref byte[] referenceKey)
        {
            InternalStringToKey(referenceKeyString, ref referenceKey);
        }

        #endregion
    }
}
