// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.RenderStyles. Do not edit; put additions in InvRenderStyles.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvRenderStyles
    {
        #region Internal properties
        internal Inventor.RenderStyles InternalRenderStyles { get; set; }

        internal object InternalApplication
        {
            get { return RenderStylesInstance.Application; }
        }

        internal int InternalCount
        {
            get { return RenderStylesInstance.Count; }
        }

        internal InvRenderStyle InternalItem(object index)
        {
            return InvRenderStyle.ByInvRenderStyle(RenderStylesInstance[index]);
        }

        internal object InternalParent
        {
            get { return RenderStylesInstance.Parent; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)RenderStylesInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvRenderStyles(InvRenderStyles invRenderStyles)
        {
            InternalRenderStyles = invRenderStyles.InternalRenderStyles;
        }

        private InvRenderStyles(Inventor.RenderStyles invRenderStyles)
        {
            InternalRenderStyles = invRenderStyles;
        }
        #endregion

        #region Private methods
        private InvRenderStyle InternalAdd(string name)
        {
            return InvRenderStyle.ByInvRenderStyle(RenderStylesInstance.Add(name));
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.RenderStyles RenderStylesInstance
        {
            get { return InternalRenderStyles; }
            set { InternalRenderStyles = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvRenderStyle Item(object index)
        {
            return InternalItem(index);
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvRenderStyles ByInvRenderStyles(InvRenderStyles invRenderStyles)
        {
            return invRenderStyles == null ? null : new InvRenderStyles(invRenderStyles);
        }

        [SupressImportIntoVM]
        public static InvRenderStyles ByInvRenderStyles(Inventor.RenderStyles invRenderStyles)
        {
            return invRenderStyles == null ? null : new InvRenderStyles(invRenderStyles);
        }
        #endregion

        #region Public methods
        public InvRenderStyle Add(string name)
        {
            return InternalAdd(name);
        }

        #endregion
    }
}
