// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ReferencedFileDescriptors. Do not edit; put additions in InvReferencedFileDescriptors.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvReferencedFileDescriptors
    {
        #region Internal properties
        internal Inventor.ReferencedFileDescriptors InternalReferencedFileDescriptors { get; set; }

        internal object InternalApplication
        {
            get { return ReferencedFileDescriptorsInstance.Application; }
        }

        internal int InternalCount
        {
            get { return ReferencedFileDescriptorsInstance.Count; }
        }

        // skipped: Item: Inventor.ReferencedFileDescriptor is not wrapped
        // skipped: ItemByName: Inventor.ReferencedFileDescriptor is not wrapped
        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)ReferencedFileDescriptorsInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvReferencedFileDescriptors(InvReferencedFileDescriptors invReferencedFileDescriptors)
        {
            InternalReferencedFileDescriptors = invReferencedFileDescriptors.InternalReferencedFileDescriptors;
        }

        private InvReferencedFileDescriptors(Inventor.ReferencedFileDescriptors invReferencedFileDescriptors)
        {
            InternalReferencedFileDescriptors = invReferencedFileDescriptors;
        }
        #endregion

        #region Private methods
        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.ReferencedFileDescriptors ReferencedFileDescriptorsInstance
        {
            get { return InternalReferencedFileDescriptors; }
            set { InternalReferencedFileDescriptors = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvReferencedFileDescriptors ByInvReferencedFileDescriptors(InvReferencedFileDescriptors invReferencedFileDescriptors)
        {
            return invReferencedFileDescriptors == null ? null : new InvReferencedFileDescriptors(invReferencedFileDescriptors);
        }

        [SupressImportIntoVM]
        public static InvReferencedFileDescriptors ByInvReferencedFileDescriptors(Inventor.ReferencedFileDescriptors invReferencedFileDescriptors)
        {
            return invReferencedFileDescriptors == null ? null : new InvReferencedFileDescriptors(invReferencedFileDescriptors);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
