// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.SketchSettings. Do not edit; put additions in InvSketchSettings.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvSketchSettings
    {
        #region Internal properties
        internal Inventor.SketchSettings InternalSketchSettings { get; set; }

        internal object InternalApplication
        {
            get { return SketchSettingsInstance.Application; }
        }

        internal bool InternalDisplayLineWeights
        {
            get { return SketchSettingsInstance.DisplayLineWeights; }
            set { SketchSettingsInstance.DisplayLineWeights = value; }
        }

        // skipped: LineWeightType: Inventor.LineWeightTypeEnum is not wrapped
        internal int InternalMinorLinesPerMajorGridLine
        {
            get { return SketchSettingsInstance.MinorLinesPerMajorGridLine; }
            set { SketchSettingsInstance.MinorLinesPerMajorGridLine = value; }
        }

        // skipped: Parent: Inventor._Document is not wrapped
        internal int InternalSnapsPerMinorGrid
        {
            get { return SketchSettingsInstance.SnapsPerMinorGrid; }
            set { SketchSettingsInstance.SnapsPerMinorGrid = value; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)SketchSettingsInstance.Type; }
        }

        internal double InternalUpperLimitForFirstRangeOfLineWeights
        {
            get { return SketchSettingsInstance.UpperLimitForFirstRangeOfLineWeights; }
            set { SketchSettingsInstance.UpperLimitForFirstRangeOfLineWeights = value; }
        }

        internal double InternalUpperLimitForSecondRangeOfLineWeights
        {
            get { return SketchSettingsInstance.UpperLimitForSecondRangeOfLineWeights; }
            set { SketchSettingsInstance.UpperLimitForSecondRangeOfLineWeights = value; }
        }

        internal double InternalUpperLimitForThirdRangeOfLineWeights
        {
            get { return SketchSettingsInstance.UpperLimitForThirdRangeOfLineWeights; }
            set { SketchSettingsInstance.UpperLimitForThirdRangeOfLineWeights = value; }
        }

        internal string InternalXSnapSpacing
        {
            get { return SketchSettingsInstance.XSnapSpacing; }
            set { SketchSettingsInstance.XSnapSpacing = value; }
        }

        internal string InternalYSnapSpacing
        {
            get { return SketchSettingsInstance.YSnapSpacing; }
            set { SketchSettingsInstance.YSnapSpacing = value; }
        }

        #endregion

        #region Private constructors
        private InvSketchSettings(InvSketchSettings invSketchSettings)
        {
            InternalSketchSettings = invSketchSettings.InternalSketchSettings;
        }

        private InvSketchSettings(Inventor.SketchSettings invSketchSettings)
        {
            InternalSketchSettings = invSketchSettings;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.SketchSettings SketchSettingsInstance
        {
            get { return InternalSketchSettings; }
            set { InternalSketchSettings = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public bool DisplayLineWeights
        {
            get { return InternalDisplayLineWeights; }
            set { InternalDisplayLineWeights = value; }
        }

        public int MinorLinesPerMajorGridLine
        {
            get { return InternalMinorLinesPerMajorGridLine; }
            set { InternalMinorLinesPerMajorGridLine = value; }
        }

        public int SnapsPerMinorGrid
        {
            get { return InternalSnapsPerMinorGrid; }
            set { InternalSnapsPerMinorGrid = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public double UpperLimitForFirstRangeOfLineWeights
        {
            get { return InternalUpperLimitForFirstRangeOfLineWeights; }
            set { InternalUpperLimitForFirstRangeOfLineWeights = value; }
        }

        public double UpperLimitForSecondRangeOfLineWeights
        {
            get { return InternalUpperLimitForSecondRangeOfLineWeights; }
            set { InternalUpperLimitForSecondRangeOfLineWeights = value; }
        }

        public double UpperLimitForThirdRangeOfLineWeights
        {
            get { return InternalUpperLimitForThirdRangeOfLineWeights; }
            set { InternalUpperLimitForThirdRangeOfLineWeights = value; }
        }

        public string XSnapSpacing
        {
            get { return InternalXSnapSpacing; }
            set { InternalXSnapSpacing = value; }
        }

        public string YSnapSpacing
        {
            get { return InternalYSnapSpacing; }
            set { InternalYSnapSpacing = value; }
        }

        #endregion

        #region Public static constructors
        public static InvSketchSettings ByInvSketchSettings(InvSketchSettings invSketchSettings)
        {
            return invSketchSettings == null ? null : new InvSketchSettings(invSketchSettings);
        }

        [SupressImportIntoVM]
        public static InvSketchSettings ByInvSketchSettings(Inventor.SketchSettings invSketchSettings)
        {
            return invSketchSettings == null ? null : new InvSketchSettings(invSketchSettings);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
