// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.SelectionPriorityEnum. Do not edit; put additions in InvSelectionPriorityEnum.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public enum InvSelectionPriorityEnum
    {
        kAnnotationSelectionPriority = Inventor.SelectionPriorityEnum.kAnnotationSelectionPriority,
        kBodySelectionPriority = Inventor.SelectionPriorityEnum.kBodySelectionPriority,
        kComponentSelectionPriority = Inventor.SelectionPriorityEnum.kComponentSelectionPriority,
        kEdgeAndFaceSelectionPriority = Inventor.SelectionPriorityEnum.kEdgeAndFaceSelectionPriority,
        kEdgeSelectionPriority = Inventor.SelectionPriorityEnum.kEdgeSelectionPriority,
        kFeatureSelectionPriority = Inventor.SelectionPriorityEnum.kFeatureSelectionPriority,
        kGroupSelectionPriority = Inventor.SelectionPriorityEnum.kGroupSelectionPriority,
        kPartSelectionPriority = Inventor.SelectionPriorityEnum.kPartSelectionPriority,
        kSketchSelectionPriority = Inventor.SelectionPriorityEnum.kSketchSelectionPriority,
        kWireSelectionPriority = Inventor.SelectionPriorityEnum.kWireSelectionPriority
    }
}
