// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.SurfaceBody. Do not edit; put additions in InvSurfaceBody.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvSurfaceBody
    {
        #region Internal properties
        internal Inventor.SurfaceBody InternalSurfaceBody { get; set; }

        // skipped: AffectedByFeatures: Inventor.PartFeaturesEnumerator is not wrapped
        internal InvSurfaceBody InternalAlternateBody(int alternateForm)
        {
            return InvSurfaceBody.ByInvSurfaceBody(SurfaceBodyInstance.get_AlternateBody(alternateForm));
        }

        internal InvAsset InternalAppearance
        {
            get { return InvAsset.ByInvAsset(SurfaceBodyInstance.Appearance); }
            set { SurfaceBodyInstance.Appearance = value?.AssetInstance; }
        }

        // skipped: AppearanceSourceType: Inventor.AppearanceSourceTypeEnum is not wrapped
        internal object InternalApplication
        {
            get { return SurfaceBodyInstance.Application; }
        }

        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(SurfaceBodyInstance.AttributeSets); }
        }

        internal InvComponentDefinition InternalComponentDefinition
        {
            get { return InvComponentDefinition.ByInvComponentDefinition(SurfaceBodyInstance.ComponentDefinition); }
        }

        // skipped: ConcaveEdges: Inventor.EdgeCollection is not wrapped
        // skipped: ConvexEdges: Inventor.EdgeCollection is not wrapped
        // skipped: CreatedByFeature: Inventor.PartFeature is not wrapped
        // skipped: DataIO: Inventor.DataIO is not wrapped
        internal InvEdges InternalEdges
        {
            get { return InvEdges.ByInvEdges(SurfaceBodyInstance.Edges); }
        }

        internal bool InternalExported
        {
            get { return SurfaceBodyInstance.Exported; }
            set { SurfaceBodyInstance.Exported = value; }
        }

        // skipped: FaceShells: Inventor.FaceShells is not wrapped
        internal InvFaces InternalFaces
        {
            get { return InvFaces.ByInvFaces(SurfaceBodyInstance.Faces); }
        }

        internal int InternalGeometryForm
        {
            get { return SurfaceBodyInstance.GeometryForm; }
        }

        // skipped: IsPointInside: Inventor.ContainmentEnum is not wrapped
        internal bool InternalIsSolid
        {
            get { return SurfaceBodyInstance.IsSolid; }
        }

        internal bool InternalIsTransient
        {
            get { return SurfaceBodyInstance.IsTransient; }
        }

        // skipped: MassProperties: Inventor.SurfaceBodyMassProperties is not wrapped
        internal string InternalName
        {
            get { return SurfaceBodyInstance.Name; }
            set { SurfaceBodyInstance.Name = value; }
        }

        internal InvOrientedBox InternalOrientedMinimumRangeBox
        {
            get { return InvOrientedBox.ByInvOrientedBox(SurfaceBodyInstance.OrientedMinimumRangeBox); }
        }

        internal object InternalParent
        {
            get { return SurfaceBodyInstance.Parent; }
        }

        internal InvBox InternalPreciseRangeBox
        {
            get { return InvBox.ByInvBox(SurfaceBodyInstance.PreciseRangeBox); }
        }

        internal InvBox InternalRangeBox
        {
            get { return InvBox.ByInvBox(SurfaceBodyInstance.RangeBox); }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)SurfaceBodyInstance.Type; }
        }

        // skipped: Vertices: Inventor.Vertices is not wrapped
        internal bool InternalVisible
        {
            get { return SurfaceBodyInstance.Visible; }
            set { SurfaceBodyInstance.Visible = value; }
        }

        internal double InternalVolume(double precisionPercent)
        {
            return SurfaceBodyInstance.get_Volume(precisionPercent);
        }

        // skipped: Wires: Inventor.Wires is not wrapped
        #endregion

        #region Private constructors
        private InvSurfaceBody(InvSurfaceBody invSurfaceBody)
        {
            InternalSurfaceBody = invSurfaceBody.InternalSurfaceBody;
        }

        private InvSurfaceBody(Inventor.SurfaceBody invSurfaceBody)
        {
            InternalSurfaceBody = invSurfaceBody;
        }
        #endregion

        #region Private methods
        private object InternalBindTransientKeyToObject(int transientKey)
        {
            return SurfaceBodyInstance.BindTransientKeyToObject(transientKey);
        }

        private void InternalCalculateFacets(double tolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices)
        {
            SurfaceBodyInstance.CalculateFacets(tolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices);
        }

        private void InternalCalculateFacetsAndTextureMap(double tolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates)
        {
            SurfaceBodyInstance.CalculateFacetsAndTextureMap(tolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        private void InternalCalculateFacetsWithOptions(double chordalTolerance, InvNameValueMap options, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out object textureCoordinates)
        {
            SurfaceBodyInstance.CalculateFacetsWithOptions(chordalTolerance, options?.NameValueMapInstance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        private void InternalCalculateStrokes(double tolerance, out int vertexCount, out int segmentCount, out double[] vertexCoordinates, out int[] vertexIndices)
        {
            SurfaceBodyInstance.CalculateStrokes(tolerance, out vertexCount, out segmentCount, out vertexCoordinates, out vertexIndices);
        }

        private void InternalCalculateStrokesWithOptions(double chordalTolerance, InvNameValueMap options, out int vertexCount, out double[] vertexCoordinates, out int polylineCount, out int[] polylineLengths)
        {
            SurfaceBodyInstance.CalculateStrokesWithOptions(chordalTolerance, options?.NameValueMapInstance, out vertexCount, out vertexCoordinates, out polylineCount, out polylineLengths);
        }

        private void InternalClearAppearanceOverrides()
        {
            SurfaceBodyInstance.ClearAppearanceOverrides();
        }

        private void InternalDelete()
        {
            SurfaceBodyInstance.Delete();
        }

        // skipped: FindUsingRay(): parameter FoundEntities is a ref/out Inventor.ObjectsEnumerator
        private InvNameValueMap InternalGetASMAttributes(object entity)
        {
            return InvNameValueMap.ByInvNameValueMap(SurfaceBodyInstance.GetASMAttributes(entity));
        }

        // skipped: GetAppearanceTextureMappingData(): parameter TextureMappingType is Inventor.TextureMappingTypeEnum, not wrapped
        private void InternalGetExistingFacetTolerances(out int toleranceCount, out double[] existingTolerances)
        {
            SurfaceBodyInstance.GetExistingFacetTolerances(out toleranceCount, out existingTolerances);
        }

        private void InternalGetExistingFacets(double toleranceIndex, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices)
        {
            SurfaceBodyInstance.GetExistingFacets(toleranceIndex, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices);
        }

        private void InternalGetExistingFacetsAndTextureMap(double toleranceIndex, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates)
        {
            SurfaceBodyInstance.GetExistingFacetsAndTextureMap(toleranceIndex, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        private void InternalGetExistingFacetsAndTextureMap2(double chordalTolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates, out int[] indexCountPerFace)
        {
            SurfaceBodyInstance.GetExistingFacetsAndTextureMap2(chordalTolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates, out indexCountPerFace);
        }

        private void InternalGetExistingStrokeTolerances(out int toleranceCount, out double[] existingTolerances)
        {
            SurfaceBodyInstance.GetExistingStrokeTolerances(out toleranceCount, out existingTolerances);
        }

        private void InternalGetExistingStrokes(double toleranceIndex, out int vertexCount, out double[] vertexCoordinates, out int polylineCount, out int[] polylineLengths)
        {
            SurfaceBodyInstance.GetExistingStrokes(toleranceIndex, out vertexCount, out vertexCoordinates, out polylineCount, out polylineLengths);
        }

        private InvObjectCollection InternalGetFaceColors(object faces)
        {
            return InvObjectCollection.ByInvObjectCollection(SurfaceBodyInstance.GetFaceColors(faces));
        }

        private void InternalGetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            SurfaceBodyInstance.GetReferenceKey(ref referenceKey, keyContext);
        }

        // skipped: GetRenderStyle(): parameter StyleSourceType is Inventor.StyleSourceTypeEnum, not wrapped
        private bool InternalIsEntityValid(object entityToCheck, int checkLevel, ref object problemEntities)
        {
            return SurfaceBodyInstance.IsEntityValid(entityToCheck, checkLevel, ref problemEntities);
        }

        private object InternalLocateUsingPoint(InvObjectTypeEnum objectType, InvPoint pointOnObject, object proximityTolerance)
        {
            return SurfaceBodyInstance.LocateUsingPoint((Inventor.ObjectTypeEnum)objectType, pointOnObject?.PointInstance, proximityTolerance);
        }

        // skipped: SetAppearanceTextureMappingData(): parameter TextureMappingType is Inventor.TextureMappingTypeEnum, not wrapped
        // skipped: SetRenderStyle(): parameter StyleSourceType is Inventor.StyleSourceTypeEnum, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.SurfaceBody SurfaceBodyInstance
        {
            get { return InternalSurfaceBody; }
            set { InternalSurfaceBody = value; }
        }

        public InvSurfaceBody AlternateBody(int alternateForm)
        {
            return InternalAlternateBody(alternateForm);
        }

        public InvAsset Appearance
        {
            get { return InternalAppearance; }
            set { InternalAppearance = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public InvComponentDefinition ComponentDefinition
        {
            get { return InternalComponentDefinition; }
        }

        public InvEdges Edges
        {
            get { return InternalEdges; }
        }

        public bool Exported
        {
            get { return InternalExported; }
            set { InternalExported = value; }
        }

        public InvFaces Faces
        {
            get { return InternalFaces; }
        }

        public int GeometryForm
        {
            get { return InternalGeometryForm; }
        }

        public bool IsSolid
        {
            get { return InternalIsSolid; }
        }

        public bool IsTransient
        {
            get { return InternalIsTransient; }
        }

        public string Name
        {
            get { return InternalName; }
            set { InternalName = value; }
        }

        public InvOrientedBox OrientedMinimumRangeBox
        {
            get { return InternalOrientedMinimumRangeBox; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public InvBox PreciseRangeBox
        {
            get { return InternalPreciseRangeBox; }
        }

        public InvBox RangeBox
        {
            get { return InternalRangeBox; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public bool Visible
        {
            get { return InternalVisible; }
            set { InternalVisible = value; }
        }

        public double Volume(double precisionPercent)
        {
            return InternalVolume(precisionPercent);
        }

        #endregion

        #region Public static constructors
        public static InvSurfaceBody ByInvSurfaceBody(InvSurfaceBody invSurfaceBody)
        {
            return invSurfaceBody == null ? null : new InvSurfaceBody(invSurfaceBody);
        }

        [SupressImportIntoVM]
        public static InvSurfaceBody ByInvSurfaceBody(Inventor.SurfaceBody invSurfaceBody)
        {
            return invSurfaceBody == null ? null : new InvSurfaceBody(invSurfaceBody);
        }
        #endregion

        #region Public methods
        public object BindTransientKeyToObject(int transientKey)
        {
            return InternalBindTransientKeyToObject(transientKey);
        }

        public void CalculateFacets(double tolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices)
        {
            InternalCalculateFacets(tolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices);
        }

        public void CalculateFacetsAndTextureMap(double tolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates)
        {
            InternalCalculateFacetsAndTextureMap(tolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        public void CalculateFacetsWithOptions(double chordalTolerance, InvNameValueMap options, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out object textureCoordinates)
        {
            InternalCalculateFacetsWithOptions(chordalTolerance, options, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        public void CalculateStrokes(double tolerance, out int vertexCount, out int segmentCount, out double[] vertexCoordinates, out int[] vertexIndices)
        {
            InternalCalculateStrokes(tolerance, out vertexCount, out segmentCount, out vertexCoordinates, out vertexIndices);
        }

        public void CalculateStrokesWithOptions(double chordalTolerance, InvNameValueMap options, out int vertexCount, out double[] vertexCoordinates, out int polylineCount, out int[] polylineLengths)
        {
            InternalCalculateStrokesWithOptions(chordalTolerance, options, out vertexCount, out vertexCoordinates, out polylineCount, out polylineLengths);
        }

        public void ClearAppearanceOverrides()
        {
            InternalClearAppearanceOverrides();
        }

        public void Delete()
        {
            InternalDelete();
        }

        public InvNameValueMap GetASMAttributes(object entity)
        {
            return InternalGetASMAttributes(entity);
        }

        public void GetExistingFacetTolerances(out int toleranceCount, out double[] existingTolerances)
        {
            InternalGetExistingFacetTolerances(out toleranceCount, out existingTolerances);
        }

        public void GetExistingFacets(double toleranceIndex, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices)
        {
            InternalGetExistingFacets(toleranceIndex, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices);
        }

        public void GetExistingFacetsAndTextureMap(double toleranceIndex, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates)
        {
            InternalGetExistingFacetsAndTextureMap(toleranceIndex, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates);
        }

        public void GetExistingFacetsAndTextureMap2(double chordalTolerance, out int vertexCount, out int facetCount, out double[] vertexCoordinates, out double[] normalVectors, out int[] vertexIndices, out double[] textureCoordinates, out int[] indexCountPerFace)
        {
            InternalGetExistingFacetsAndTextureMap2(chordalTolerance, out vertexCount, out facetCount, out vertexCoordinates, out normalVectors, out vertexIndices, out textureCoordinates, out indexCountPerFace);
        }

        public void GetExistingStrokeTolerances(out int toleranceCount, out double[] existingTolerances)
        {
            InternalGetExistingStrokeTolerances(out toleranceCount, out existingTolerances);
        }

        public void GetExistingStrokes(double toleranceIndex, out int vertexCount, out double[] vertexCoordinates, out int polylineCount, out int[] polylineLengths)
        {
            InternalGetExistingStrokes(toleranceIndex, out vertexCount, out vertexCoordinates, out polylineCount, out polylineLengths);
        }

        public InvObjectCollection GetFaceColors(object faces)
        {
            return InternalGetFaceColors(faces);
        }

        public void GetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            InternalGetReferenceKey(ref referenceKey, keyContext);
        }

        public bool IsEntityValid(object entityToCheck, int checkLevel, ref object problemEntities)
        {
            return InternalIsEntityValid(entityToCheck, checkLevel, ref problemEntities);
        }

        public object LocateUsingPoint(InvObjectTypeEnum objectType, InvPoint pointOnObject, object proximityTolerance)
        {
            return InternalLocateUsingPoint(objectType, pointOnObject, proximityTolerance);
        }

        #endregion
    }
}
