// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.SoftwareVersion. Do not edit; put additions in InvSoftwareVersion.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvSoftwareVersion
    {
        #region Internal properties
        internal Inventor.SoftwareVersion InternalSoftwareVersion { get; set; }

        internal int InternalBetaVersion
        {
            get { return SoftwareVersionInstance.BetaVersion; }
        }

        internal int InternalBuildIdentifier
        {
            get { return SoftwareVersionInstance.BuildIdentifier; }
        }

        internal string InternalDisplayName
        {
            get { return SoftwareVersionInstance.DisplayName; }
        }

        internal string InternalDisplayVersion
        {
            get { return SoftwareVersionInstance.DisplayVersion; }
        }

        internal bool InternalIs64BitVersion
        {
            get { return SoftwareVersionInstance.Is64BitVersion; }
        }

        internal bool InternalIsEducationVersion
        {
            get { return SoftwareVersionInstance.IsEducationVersion; }
        }

        internal int InternalMajor
        {
            get { return SoftwareVersionInstance.Major; }
        }

        internal int InternalMinor
        {
            get { return SoftwareVersionInstance.Minor; }
        }

        internal bool InternalNotProduction
        {
            get { return SoftwareVersionInstance.NotProduction; }
        }

        // skipped: ProductEdition: Inventor.ProductEditionEnum is not wrapped
        internal string InternalProductName
        {
            get { return SoftwareVersionInstance.ProductName; }
        }

        internal int InternalServicePack
        {
            get { return SoftwareVersionInstance.ServicePack; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)SoftwareVersionInstance.Type; }
        }

        internal string InternalVersionInfoLabel
        {
            get { return SoftwareVersionInstance.VersionInfoLabel; }
        }

        #endregion

        #region Private constructors
        private InvSoftwareVersion(InvSoftwareVersion invSoftwareVersion)
        {
            InternalSoftwareVersion = invSoftwareVersion.InternalSoftwareVersion;
        }

        private InvSoftwareVersion(Inventor.SoftwareVersion invSoftwareVersion)
        {
            InternalSoftwareVersion = invSoftwareVersion;
        }
        #endregion

        #region Private methods
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.SoftwareVersion SoftwareVersionInstance
        {
            get { return InternalSoftwareVersion; }
            set { InternalSoftwareVersion = value; }
        }

        public int BetaVersion
        {
            get { return InternalBetaVersion; }
        }

        public int BuildIdentifier
        {
            get { return InternalBuildIdentifier; }
        }

        public string DisplayName
        {
            get { return InternalDisplayName; }
        }

        public string DisplayVersion
        {
            get { return InternalDisplayVersion; }
        }

        public bool Is64BitVersion
        {
            get { return InternalIs64BitVersion; }
        }

        public bool IsEducationVersion
        {
            get { return InternalIsEducationVersion; }
        }

        public int Major
        {
            get { return InternalMajor; }
        }

        public int Minor
        {
            get { return InternalMinor; }
        }

        public bool NotProduction
        {
            get { return InternalNotProduction; }
        }

        public string ProductName
        {
            get { return InternalProductName; }
        }

        public int ServicePack
        {
            get { return InternalServicePack; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public string VersionInfoLabel
        {
            get { return InternalVersionInfoLabel; }
        }

        #endregion

        #region Public static constructors
        public static InvSoftwareVersion ByInvSoftwareVersion(InvSoftwareVersion invSoftwareVersion)
        {
            return invSoftwareVersion == null ? null : new InvSoftwareVersion(invSoftwareVersion);
        }

        [SupressImportIntoVM]
        public static InvSoftwareVersion ByInvSoftwareVersion(Inventor.SoftwareVersion invSoftwareVersion)
        {
            return invSoftwareVersion == null ? null : new InvSoftwareVersion(invSoftwareVersion);
        }
        #endregion

        #region Public methods
        #endregion
    }
}
