// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.SelectSet. Do not edit; put additions in InvSelectSet.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvSelectSet
    {
        #region Internal properties
        internal Inventor.SelectSet InternalSelectSet { get; set; }

        internal int InternalCount
        {
            get { return SelectSetInstance.Count; }
        }

        internal object InternalItem(int index)
        {
            return SelectSetInstance[index];
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)SelectSetInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvSelectSet(InvSelectSet invSelectSet)
        {
            InternalSelectSet = invSelectSet.InternalSelectSet;
        }

        private InvSelectSet(Inventor.SelectSet invSelectSet)
        {
            InternalSelectSet = invSelectSet;
        }
        #endregion

        #region Private methods
        private void InternalClear()
        {
            SelectSetInstance.Clear();
        }

        private void InternalDelete()
        {
            SelectSetInstance.Delete();
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        private void InternalRemove(object index)
        {
            SelectSetInstance.Remove(index);
        }

        private void InternalSelect(object entity)
        {
            SelectSetInstance.Select(entity);
        }

        private void InternalSelectMultiple(InvObjectCollection entities)
        {
            SelectSetInstance.SelectMultiple(entities?.ObjectCollectionInstance);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.SelectSet SelectSetInstance
        {
            get { return InternalSelectSet; }
            set { InternalSelectSet = value; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public object Item(int index)
        {
            return InternalItem(index);
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvSelectSet ByInvSelectSet(InvSelectSet invSelectSet)
        {
            return invSelectSet == null ? null : new InvSelectSet(invSelectSet);
        }

        [SupressImportIntoVM]
        public static InvSelectSet ByInvSelectSet(Inventor.SelectSet invSelectSet)
        {
            return invSelectSet == null ? null : new InvSelectSet(invSelectSet);
        }
        #endregion

        #region Public methods
        public void Clear()
        {
            InternalClear();
        }

        public void Delete()
        {
            InternalDelete();
        }

        public void Remove(object index)
        {
            InternalRemove(index);
        }

        public void Select(object entity)
        {
            InternalSelect(entity);
        }

        public void SelectMultiple(InvObjectCollection entities)
        {
            InternalSelectMultiple(entities);
        }

        #endregion
    }
}
