// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.ThumbnailSaveOptionEnum. Do not edit; put additions in InvThumbnailSaveOptionEnum.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public enum InvThumbnailSaveOptionEnum
    {
        kActiveComponentIsoViewOnSave = Inventor.ThumbnailSaveOptionEnum.kActiveComponentIsoViewOnSave,
        kActiveWindow = Inventor.ThumbnailSaveOptionEnum.kActiveWindow,
        kActiveWindowOnSave = Inventor.ThumbnailSaveOptionEnum.kActiveWindowOnSave,
        kImportFromFile = Inventor.ThumbnailSaveOptionEnum.kImportFromFile,
        kNoThumbnail = Inventor.ThumbnailSaveOptionEnum.kNoThumbnail
    }
}
