// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.TransientGeometry. Do not edit; put additions in InvTransientGeometry.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvTransientGeometry
    {
        #region Internal properties
        internal Inventor.TransientGeometry InternalTransientGeometry { get; set; }

        internal double InternalPointTolerance
        {
            get { return TransientGeometryInstance.PointTolerance; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)TransientGeometryInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvTransientGeometry(InvTransientGeometry invTransientGeometry)
        {
            InternalTransientGeometry = invTransientGeometry.InternalTransientGeometry;
        }

        private InvTransientGeometry(Inventor.TransientGeometry invTransientGeometry)
        {
            InternalTransientGeometry = invTransientGeometry;
        }
        #endregion

        #region Private methods
        // skipped: CreateArc2d(): returns Inventor.Arc2d, not wrapped
        // skipped: CreateArc2dByThreePoints(): returns Inventor.Arc2d, not wrapped
        // skipped: CreateArc2dByThreePoints2(): returns Inventor.Arc2d, not wrapped
        // skipped: CreateArc3d(): returns Inventor.Arc3d, not wrapped
        // skipped: CreateArc3dByThreePoints(): returns Inventor.Arc3d, not wrapped
        // skipped: CreateBSplineCurve(): returns Inventor.BSplineCurve, not wrapped
        // skipped: CreateBSplineCurve2d(): returns Inventor.BSplineCurve2d, not wrapped
        // skipped: CreateBSplineCurve2dDefinition(): returns Inventor.BSplineCurve2dDefinition, not wrapped
        // skipped: CreateBSplineCurveDefinition(): returns Inventor.BSplineCurveDefinition, not wrapped
        // skipped: CreateBSplineSurface(): returns Inventor.BSplineSurface, not wrapped
        private InvBox InternalCreateBox()
        {
            return InvBox.ByInvBox(TransientGeometryInstance.CreateBox());
        }

        // skipped: CreateBox2d(): returns Inventor.Box2d, not wrapped
        // skipped: CreateCircle(): returns Inventor.Circle, not wrapped
        // skipped: CreateCircle2d(): returns Inventor.Circle2d, not wrapped
        // skipped: CreateCircle2dByThreePoints(): returns Inventor.Circle2d, not wrapped
        // skipped: CreateCircleByThreePoints(): returns Inventor.Circle, not wrapped
        // skipped: CreateCone(): returns Inventor.Cone, not wrapped
        // skipped: CreateCylinder(): returns Inventor.Cylinder, not wrapped
        // skipped: CreateEllipseFull(): returns Inventor.EllipseFull, not wrapped
        // skipped: CreateEllipseFull2d(): returns Inventor.EllipseFull2d, not wrapped
        // skipped: CreateEllipticalArc(): returns Inventor.EllipticalArc, not wrapped
        // skipped: CreateEllipticalArc2d(): returns Inventor.EllipticalArc2d, not wrapped
        // skipped: CreateEllipticalCone(): returns Inventor.EllipticalCone, not wrapped
        // skipped: CreateEllipticalCylinder(): returns Inventor.EllipticalCylinder, not wrapped
        // skipped: CreateFittedBSplineCurve(): returns Inventor.BSplineCurve, not wrapped
        // skipped: CreateFittedBSplineCurve2d(): returns Inventor.BSplineCurve2d, not wrapped
        private InvLine InternalCreateLine(InvPoint rootPoint, InvVector direction)
        {
            return InvLine.ByInvLine(TransientGeometryInstance.CreateLine(rootPoint?.PointInstance, direction?.VectorInstance));
        }

        // skipped: CreateLine2d(): returns Inventor.Line2d, not wrapped
        // skipped: CreateLineSegment(): returns Inventor.LineSegment, not wrapped
        // skipped: CreateLineSegment2d(): returns Inventor.LineSegment2d, not wrapped
        private InvMatrix InternalCreateMatrix()
        {
            return InvMatrix.ByInvMatrix(TransientGeometryInstance.CreateMatrix());
        }

        // skipped: CreateMatrix2d(): returns Inventor.Matrix2d, not wrapped
        private InvOrientedBox InternalCreateOrientedBox(object cornerPoint, object directionOne, object directionTwo, object directionThree)
        {
            return InvOrientedBox.ByInvOrientedBox(TransientGeometryInstance.CreateOrientedBox(cornerPoint, directionOne, directionTwo, directionThree));
        }

        private InvPlane InternalCreatePlane(InvPoint rootPoint, InvVector normal)
        {
            return InvPlane.ByInvPlane(TransientGeometryInstance.CreatePlane(rootPoint?.PointInstance, normal?.VectorInstance));
        }

        private InvPlane InternalCreatePlaneByThreePoints(InvPoint pointOne, InvPoint pointTwo, InvPoint pointThree)
        {
            return InvPlane.ByInvPlane(TransientGeometryInstance.CreatePlaneByThreePoints(pointOne?.PointInstance, pointTwo?.PointInstance, pointThree?.PointInstance));
        }

        private InvPoint InternalCreatePoint(double xCoord, double yCoord, double zCoord)
        {
            return InvPoint.ByInvPoint(TransientGeometryInstance.CreatePoint(xCoord, yCoord, zCoord));
        }

        // skipped: CreatePoint2d(): returns Inventor.Point2d, not wrapped
        // skipped: CreatePolyline2d(): returns Inventor.Polyline2d, not wrapped
        // skipped: CreatePolyline2dFromCurve(): returns Inventor.Polyline2d, not wrapped
        // skipped: CreatePolyline3d(): returns Inventor.Polyline3d, not wrapped
        // skipped: CreatePolyline3dFromCurve(): returns Inventor.Polyline3d, not wrapped
        // skipped: CreateSphere(): returns Inventor.Sphere, not wrapped
        // skipped: CreateTorus(): returns Inventor.Torus, not wrapped
        private InvUnitVector InternalCreateUnitVector(double xCoord, double yCoord, double zCoord)
        {
            return InvUnitVector.ByInvUnitVector(TransientGeometryInstance.CreateUnitVector(xCoord, yCoord, zCoord));
        }

        // skipped: CreateUnitVector2d(): returns Inventor.UnitVector2d, not wrapped
        private InvVector InternalCreateVector(double xCoord, double yCoord, double zCoord)
        {
            return InvVector.ByInvVector(TransientGeometryInstance.CreateVector(xCoord, yCoord, zCoord));
        }

        // skipped: CreateVector2d(): returns Inventor.Vector2d, not wrapped
        private InvObjectsEnumerator InternalCurveCurveIntersection(object curveOne, object curveTwo, double tolerance)
        {
            return InvObjectsEnumerator.ByInvObjectsEnumerator(TransientGeometryInstance.CurveCurveIntersection(curveOne, curveTwo, tolerance));
        }

        private InvObjectsEnumerator InternalCurveSurfaceIntersection(object curve, object surface, double tolerance)
        {
            return InvObjectsEnumerator.ByInvObjectsEnumerator(TransientGeometryInstance.CurveSurfaceIntersection(curve, surface, tolerance));
        }

        private InvPoint InternalGetFarmostPoint(object entity, InvUnitVector direction)
        {
            return InvPoint.ByInvPoint(TransientGeometryInstance.GetFarmostPoint(entity, direction?.UnitVectorInstance));
        }

        private InvObjectsEnumerator InternalSurfaceSurfaceIntersection(object surfaceOne, object surfaceTwo, double tolerance)
        {
            return InvObjectsEnumerator.ByInvObjectsEnumerator(TransientGeometryInstance.SurfaceSurfaceIntersection(surfaceOne, surfaceTwo, tolerance));
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.TransientGeometry TransientGeometryInstance
        {
            get { return InternalTransientGeometry; }
            set { InternalTransientGeometry = value; }
        }

        public double PointTolerance
        {
            get { return InternalPointTolerance; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvTransientGeometry ByInvTransientGeometry(InvTransientGeometry invTransientGeometry)
        {
            return invTransientGeometry == null ? null : new InvTransientGeometry(invTransientGeometry);
        }

        [SupressImportIntoVM]
        public static InvTransientGeometry ByInvTransientGeometry(Inventor.TransientGeometry invTransientGeometry)
        {
            return invTransientGeometry == null ? null : new InvTransientGeometry(invTransientGeometry);
        }
        #endregion

        #region Public methods
        public InvBox CreateBox()
        {
            return InternalCreateBox();
        }

        public InvLine CreateLine(InvPoint rootPoint, InvVector direction)
        {
            return InternalCreateLine(rootPoint, direction);
        }

        public InvMatrix CreateMatrix()
        {
            return InternalCreateMatrix();
        }

        public InvOrientedBox CreateOrientedBox(object cornerPoint, object directionOne, object directionTwo, object directionThree)
        {
            return InternalCreateOrientedBox(cornerPoint, directionOne, directionTwo, directionThree);
        }

        public InvPlane CreatePlane(InvPoint rootPoint, InvVector normal)
        {
            return InternalCreatePlane(rootPoint, normal);
        }

        public InvPlane CreatePlaneByThreePoints(InvPoint pointOne, InvPoint pointTwo, InvPoint pointThree)
        {
            return InternalCreatePlaneByThreePoints(pointOne, pointTwo, pointThree);
        }

        public InvPoint CreatePoint(double xCoord, double yCoord, double zCoord)
        {
            return InternalCreatePoint(xCoord, yCoord, zCoord);
        }

        public InvUnitVector CreateUnitVector(double xCoord, double yCoord, double zCoord)
        {
            return InternalCreateUnitVector(xCoord, yCoord, zCoord);
        }

        public InvVector CreateVector(double xCoord, double yCoord, double zCoord)
        {
            return InternalCreateVector(xCoord, yCoord, zCoord);
        }

        public InvObjectsEnumerator CurveCurveIntersection(object curveOne, object curveTwo, double tolerance)
        {
            return InternalCurveCurveIntersection(curveOne, curveTwo, tolerance);
        }

        public InvObjectsEnumerator CurveSurfaceIntersection(object curve, object surface, double tolerance)
        {
            return InternalCurveSurfaceIntersection(curve, surface, tolerance);
        }

        public InvPoint GetFarmostPoint(object entity, InvUnitVector direction)
        {
            return InternalGetFarmostPoint(entity, direction);
        }

        public InvObjectsEnumerator SurfaceSurfaceIntersection(object surfaceOne, object surfaceTwo, double tolerance)
        {
            return InternalSurfaceSurfaceIntersection(surfaceOne, surfaceTwo, tolerance);
        }

        #endregion
    }
}
