// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.UnitsOfMeasure. Do not edit; put additions in InvUnitsOfMeasure.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvUnitsOfMeasure
    {
        #region Internal properties
        internal Inventor.UnitsOfMeasure InternalUnitsOfMeasure { get; set; }

        internal int InternalAngleDisplayPrecision
        {
            get { return UnitsOfMeasureInstance.AngleDisplayPrecision; }
            set { UnitsOfMeasureInstance.AngleDisplayPrecision = value; }
        }

        internal InvUnitsTypeEnum InternalAngleUnits
        {
            get { return (InvUnitsTypeEnum)UnitsOfMeasureInstance.AngleUnits; }
            set { UnitsOfMeasureInstance.AngleUnits = (Inventor.UnitsTypeEnum)value; }
        }

        internal int InternalLengthDisplayPrecision
        {
            get { return UnitsOfMeasureInstance.LengthDisplayPrecision; }
            set { UnitsOfMeasureInstance.LengthDisplayPrecision = value; }
        }

        internal InvUnitsTypeEnum InternalLengthUnits
        {
            get { return (InvUnitsTypeEnum)UnitsOfMeasureInstance.LengthUnits; }
            set { UnitsOfMeasureInstance.LengthUnits = (Inventor.UnitsTypeEnum)value; }
        }

        internal InvUnitsTypeEnum InternalMassUnits
        {
            get { return (InvUnitsTypeEnum)UnitsOfMeasureInstance.MassUnits; }
            set { UnitsOfMeasureInstance.MassUnits = (Inventor.UnitsTypeEnum)value; }
        }

        internal object InternalParent
        {
            get { return UnitsOfMeasureInstance.Parent; }
        }

        internal InvUnitsTypeEnum InternalTimeUnits
        {
            get { return (InvUnitsTypeEnum)UnitsOfMeasureInstance.TimeUnits; }
            set { UnitsOfMeasureInstance.TimeUnits = (Inventor.UnitsTypeEnum)value; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)UnitsOfMeasureInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvUnitsOfMeasure(InvUnitsOfMeasure invUnitsOfMeasure)
        {
            InternalUnitsOfMeasure = invUnitsOfMeasure.InternalUnitsOfMeasure;
        }

        private InvUnitsOfMeasure(Inventor.UnitsOfMeasure invUnitsOfMeasure)
        {
            InternalUnitsOfMeasure = invUnitsOfMeasure;
        }
        #endregion

        #region Private methods
        private bool InternalCompatibleUnits(string expression1, object unitsSpecifier1, string expression2, object unitsSpecifier2)
        {
            return UnitsOfMeasureInstance.CompatibleUnits(expression1, unitsSpecifier1, expression2, unitsSpecifier2);
        }

        private double InternalConvertUnits(double value, object inputUnitsSpecifier, object outputUnitsSpecifier)
        {
            return UnitsOfMeasureInstance.ConvertUnits(value, inputUnitsSpecifier, outputUnitsSpecifier);
        }

        private string InternalGetDatabaseUnitsFromExpression(string expression, object unitsSpecifier)
        {
            return UnitsOfMeasureInstance.GetDatabaseUnitsFromExpression(expression, unitsSpecifier);
        }

        // skipped: GetDrivingParameters(): returns Inventor.ParametersEnumerator, not wrapped
        private string InternalGetLocaleCorrectedExpression(string expression, object unitsSpecifier)
        {
            return UnitsOfMeasureInstance.GetLocaleCorrectedExpression(expression, unitsSpecifier);
        }

        private string InternalGetPreciseStringFromValue(double value, object unitsSpecifier)
        {
            return UnitsOfMeasureInstance.GetPreciseStringFromValue(value, unitsSpecifier);
        }

        private string InternalGetStringFromType(InvUnitsTypeEnum unitsType)
        {
            return UnitsOfMeasureInstance.GetStringFromType((Inventor.UnitsTypeEnum)unitsType);
        }

        private string InternalGetStringFromValue(double value, object unitsSpecifier)
        {
            return UnitsOfMeasureInstance.GetStringFromValue(value, unitsSpecifier);
        }

        private InvUnitsTypeEnum InternalGetTypeFromString(string unitsString)
        {
            return (InvUnitsTypeEnum)UnitsOfMeasureInstance.GetTypeFromString(unitsString);
        }

        private object InternalGetValueFromExpression(string expression, object unitsSpecifier)
        {
            return UnitsOfMeasureInstance.GetValueFromExpression(expression, unitsSpecifier);
        }

        private bool InternalIsExpressionValid(string expression, object unitsSpecifier)
        {
            return UnitsOfMeasureInstance.IsExpressionValid(expression, unitsSpecifier);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.UnitsOfMeasure UnitsOfMeasureInstance
        {
            get { return InternalUnitsOfMeasure; }
            set { InternalUnitsOfMeasure = value; }
        }

        public int AngleDisplayPrecision
        {
            get { return InternalAngleDisplayPrecision; }
            set { InternalAngleDisplayPrecision = value; }
        }

        public InvUnitsTypeEnum AngleUnits
        {
            get { return InternalAngleUnits; }
            set { InternalAngleUnits = value; }
        }

        public int LengthDisplayPrecision
        {
            get { return InternalLengthDisplayPrecision; }
            set { InternalLengthDisplayPrecision = value; }
        }

        public InvUnitsTypeEnum LengthUnits
        {
            get { return InternalLengthUnits; }
            set { InternalLengthUnits = value; }
        }

        public InvUnitsTypeEnum MassUnits
        {
            get { return InternalMassUnits; }
            set { InternalMassUnits = value; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public InvUnitsTypeEnum TimeUnits
        {
            get { return InternalTimeUnits; }
            set { InternalTimeUnits = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvUnitsOfMeasure ByInvUnitsOfMeasure(InvUnitsOfMeasure invUnitsOfMeasure)
        {
            return invUnitsOfMeasure == null ? null : new InvUnitsOfMeasure(invUnitsOfMeasure);
        }

        [SupressImportIntoVM]
        public static InvUnitsOfMeasure ByInvUnitsOfMeasure(Inventor.UnitsOfMeasure invUnitsOfMeasure)
        {
            return invUnitsOfMeasure == null ? null : new InvUnitsOfMeasure(invUnitsOfMeasure);
        }
        #endregion

        #region Public methods
        public bool CompatibleUnits(string expression1, object unitsSpecifier1, string expression2, object unitsSpecifier2)
        {
            return InternalCompatibleUnits(expression1, unitsSpecifier1, expression2, unitsSpecifier2);
        }

        public double ConvertUnits(double value, object inputUnitsSpecifier, object outputUnitsSpecifier)
        {
            return InternalConvertUnits(value, inputUnitsSpecifier, outputUnitsSpecifier);
        }

        public string GetDatabaseUnitsFromExpression(string expression, object unitsSpecifier)
        {
            return InternalGetDatabaseUnitsFromExpression(expression, unitsSpecifier);
        }

        public string GetLocaleCorrectedExpression(string expression, object unitsSpecifier)
        {
            return InternalGetLocaleCorrectedExpression(expression, unitsSpecifier);
        }

        public string GetPreciseStringFromValue(double value, object unitsSpecifier)
        {
            return InternalGetPreciseStringFromValue(value, unitsSpecifier);
        }

        public string GetStringFromType(InvUnitsTypeEnum unitsType)
        {
            return InternalGetStringFromType(unitsType);
        }

        public string GetStringFromValue(double value, object unitsSpecifier)
        {
            return InternalGetStringFromValue(value, unitsSpecifier);
        }

        public InvUnitsTypeEnum GetTypeFromString(string unitsString)
        {
            return InternalGetTypeFromString(unitsString);
        }

        public object GetValueFromExpression(string expression, object unitsSpecifier)
        {
            return InternalGetValueFromExpression(expression, unitsSpecifier);
        }

        public bool IsExpressionValid(string expression, object unitsSpecifier)
        {
            return InternalIsExpressionValid(expression, unitsSpecifier);
        }

        #endregion
    }
}
