// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.UserParameter. Do not edit; put additions in InvUserParameter.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvUserParameter
    {
        #region Internal properties
        internal Inventor.UserParameter InternalUserParameter { get; set; }

        internal InvAttributeSets InternalAttributeSets
        {
            get { return InvAttributeSets.ByInvAttributeSets(UserParameterInstance.AttributeSets); }
        }

        internal string InternalComment
        {
            get { return UserParameterInstance.Comment; }
            set { UserParameterInstance.Comment = value; }
        }

        // skipped: CustomPropertyFormat: Inventor.CustomPropertyFormat is not wrapped
        internal InvObjectCollection InternalDependents
        {
            get { return InvObjectCollection.ByInvObjectCollection(UserParameterInstance.Dependents); }
        }

        internal InvActionTypeEnum InternalDisabledActionTypes
        {
            get { return (InvActionTypeEnum)UserParameterInstance.DisabledActionTypes; }
            set { UserParameterInstance.DisabledActionTypes = (Inventor.ActionTypeEnum)value; }
        }

        // skipped: DisplayFormat: Inventor.ParameterDisplayFormatEnum is not wrapped
        internal InvObjectCollection InternalDrivenBy
        {
            get { return InvObjectCollection.ByInvObjectCollection(UserParameterInstance.DrivenBy); }
        }

        internal bool InternalExposedAsProperty
        {
            get { return UserParameterInstance.ExposedAsProperty; }
            set { UserParameterInstance.ExposedAsProperty = value; }
        }

        internal string InternalExpression
        {
            get { return UserParameterInstance.Expression; }
            set { UserParameterInstance.Expression = value; }
        }

        // skipped: ExpressionList: Inventor.ExpressionList is not wrapped
        internal InvHealthStatusEnum InternalHealthStatus
        {
            get { return (InvHealthStatusEnum)UserParameterInstance.HealthStatus; }
        }

        internal bool InternalInUse
        {
            get { return UserParameterInstance.InUse; }
        }

        internal bool InternalIsKey
        {
            get { return UserParameterInstance.IsKey; }
            set { UserParameterInstance.IsKey = value; }
        }

        internal double InternalModelValue
        {
            get { return UserParameterInstance.ModelValue; }
        }

        // skipped: ModelValueType: Inventor.ModelValueTypeEnum is not wrapped
        internal string InternalName
        {
            get { return UserParameterInstance.Name; }
            set { UserParameterInstance.Name = value; }
        }

        internal InvParameterTypeEnum InternalParameterType
        {
            get { return (InvParameterTypeEnum)UserParameterInstance.ParameterType; }
        }

        internal object InternalParent
        {
            get { return UserParameterInstance.Parent; }
        }

        internal int InternalPrecision
        {
            get { return UserParameterInstance.Precision; }
            set { UserParameterInstance.Precision = value; }
        }

        // skipped: Tolerance: Inventor.Tolerance is not wrapped
        internal string InternalToleranceInfo
        {
            get { return UserParameterInstance.ToleranceInfo; }
            set { UserParameterInstance.ToleranceInfo = value; }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)UserParameterInstance.Type; }
        }

        internal string InternalUnits
        {
            get { return UserParameterInstance.get_Units(); }
        }

        internal void InternalUnitsSet(object value)
        {
            UserParameterInstance.set_Units(value);
        }

        internal object InternalValue
        {
            get { return UserParameterInstance.Value; }
            set { UserParameterInstance.Value = value; }
        }

        internal bool InternalVisible
        {
            get { return UserParameterInstance.Visible; }
            set { UserParameterInstance.Visible = value; }
        }

        #endregion

        #region Private constructors
        private InvUserParameter(InvUserParameter invUserParameter)
        {
            InternalUserParameter = invUserParameter.InternalUserParameter;
        }

        private InvUserParameter(Inventor.UserParameter invUserParameter)
        {
            InternalUserParameter = invUserParameter;
        }
        #endregion

        #region Private methods
        private InvModelParameter InternalConvertToModelParameter()
        {
            return InvModelParameter.ByInvModelParameter(UserParameterInstance.ConvertToModelParameter());
        }

        // skipped: ConvertToReferenceParameter(): returns Inventor.ReferenceParameter, not wrapped
        private void InternalDelete()
        {
            UserParameterInstance.Delete();
        }

        private void InternalGetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            UserParameterInstance.GetReferenceKey(ref referenceKey, keyContext);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.UserParameter UserParameterInstance
        {
            get { return InternalUserParameter; }
            set { InternalUserParameter = value; }
        }

        public InvAttributeSets AttributeSets
        {
            get { return InternalAttributeSets; }
        }

        public string Comment
        {
            get { return InternalComment; }
            set { InternalComment = value; }
        }

        public InvObjectCollection Dependents
        {
            get { return InternalDependents; }
        }

        public InvActionTypeEnum DisabledActionTypes
        {
            get { return InternalDisabledActionTypes; }
            set { InternalDisabledActionTypes = value; }
        }

        public InvObjectCollection DrivenBy
        {
            get { return InternalDrivenBy; }
        }

        public bool ExposedAsProperty
        {
            get { return InternalExposedAsProperty; }
            set { InternalExposedAsProperty = value; }
        }

        public string Expression
        {
            get { return InternalExpression; }
            set { InternalExpression = value; }
        }

        public InvHealthStatusEnum HealthStatus
        {
            get { return InternalHealthStatus; }
        }

        public bool InUse
        {
            get { return InternalInUse; }
        }

        public bool IsKey
        {
            get { return InternalIsKey; }
            set { InternalIsKey = value; }
        }

        public double ModelValue
        {
            get { return InternalModelValue; }
        }

        public string Name
        {
            get { return InternalName; }
            set { InternalName = value; }
        }

        public InvParameterTypeEnum ParameterType
        {
            get { return InternalParameterType; }
        }

        public object Parent
        {
            get { return InternalParent; }
        }

        public int Precision
        {
            get { return InternalPrecision; }
            set { InternalPrecision = value; }
        }

        public string ToleranceInfo
        {
            get { return InternalToleranceInfo; }
            set { InternalToleranceInfo = value; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        public string Units
        {
            get { return InternalUnits; }
        }

        public void SetUnits(object value)
        {
            InternalUnitsSet(value);
        }

        public object Value
        {
            get { return InternalValue; }
            set { InternalValue = value; }
        }

        public bool Visible
        {
            get { return InternalVisible; }
            set { InternalVisible = value; }
        }

        #endregion

        #region Public static constructors
        public static InvUserParameter ByInvUserParameter(InvUserParameter invUserParameter)
        {
            return invUserParameter == null ? null : new InvUserParameter(invUserParameter);
        }

        [SupressImportIntoVM]
        public static InvUserParameter ByInvUserParameter(Inventor.UserParameter invUserParameter)
        {
            return invUserParameter == null ? null : new InvUserParameter(invUserParameter);
        }
        #endregion

        #region Public methods
        public InvModelParameter ConvertToModelParameter()
        {
            return InternalConvertToModelParameter();
        }

        public void Delete()
        {
            InternalDelete();
        }

        public void GetReferenceKey(ref byte[] referenceKey, int keyContext)
        {
            InternalGetReferenceKey(ref referenceKey, keyContext);
        }

        #endregion
    }
}
