// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.UnitVector. Do not edit; put additions in InvUnitVector.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvUnitVector
    {
        #region Internal properties
        internal Inventor.UnitVector InternalUnitVector { get; set; }

        internal double InternalX
        {
            get { return UnitVectorInstance.X; }
            set { UnitVectorInstance.X = value; }
        }

        internal double InternalY
        {
            get { return UnitVectorInstance.Y; }
            set { UnitVectorInstance.Y = value; }
        }

        internal double InternalZ
        {
            get { return UnitVectorInstance.Z; }
            set { UnitVectorInstance.Z = value; }
        }

        #endregion

        #region Private constructors
        private InvUnitVector(InvUnitVector invUnitVector)
        {
            InternalUnitVector = invUnitVector.InternalUnitVector;
        }

        private InvUnitVector(Inventor.UnitVector invUnitVector)
        {
            InternalUnitVector = invUnitVector;
        }
        #endregion

        #region Private methods
        private double InternalAngleTo(InvUnitVector argument)
        {
            return UnitVectorInstance.AngleTo(argument?.UnitVectorInstance);
        }

        private InvVector InternalAsVector()
        {
            return InvVector.ByInvVector(UnitVectorInstance.AsVector());
        }

        private InvUnitVector InternalCopy()
        {
            return InvUnitVector.ByInvUnitVector(UnitVectorInstance.Copy());
        }

        private InvUnitVector InternalCrossProduct(InvUnitVector argument)
        {
            return InvUnitVector.ByInvUnitVector(UnitVectorInstance.CrossProduct(argument?.UnitVectorInstance));
        }

        private double InternalDotProduct(InvUnitVector argument)
        {
            return UnitVectorInstance.DotProduct(argument?.UnitVectorInstance);
        }

        private void InternalGetUnitVectorData(ref double[] coords)
        {
            UnitVectorInstance.GetUnitVectorData(ref coords);
        }

        private bool InternalIsEqualTo(InvUnitVector argument, double tolerance)
        {
            return UnitVectorInstance.IsEqualTo(argument?.UnitVectorInstance, tolerance);
        }

        private bool InternalIsParallelTo(InvUnitVector argument, double tolerance)
        {
            return UnitVectorInstance.IsParallelTo(argument?.UnitVectorInstance, tolerance);
        }

        private bool InternalIsPerpendicularTo(InvUnitVector argument, double tolerance)
        {
            return UnitVectorInstance.IsPerpendicularTo(argument?.UnitVectorInstance, tolerance);
        }

        private void InternalPutUnitVectorData(ref double[] coords)
        {
            UnitVectorInstance.PutUnitVectorData(ref coords);
        }

        private void InternalTransformBy(InvMatrix matrix)
        {
            UnitVectorInstance.TransformBy(matrix?.MatrixInstance);
        }

        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.UnitVector UnitVectorInstance
        {
            get { return InternalUnitVector; }
            set { InternalUnitVector = value; }
        }

        public double X
        {
            get { return InternalX; }
            set { InternalX = value; }
        }

        public double Y
        {
            get { return InternalY; }
            set { InternalY = value; }
        }

        public double Z
        {
            get { return InternalZ; }
            set { InternalZ = value; }
        }

        #endregion

        #region Public static constructors
        public static InvUnitVector ByInvUnitVector(InvUnitVector invUnitVector)
        {
            return invUnitVector == null ? null : new InvUnitVector(invUnitVector);
        }

        [SupressImportIntoVM]
        public static InvUnitVector ByInvUnitVector(Inventor.UnitVector invUnitVector)
        {
            return invUnitVector == null ? null : new InvUnitVector(invUnitVector);
        }
        #endregion

        #region Public methods
        public double AngleTo(InvUnitVector argument)
        {
            return InternalAngleTo(argument);
        }

        public InvVector AsVector()
        {
            return InternalAsVector();
        }

        public InvUnitVector Copy()
        {
            return InternalCopy();
        }

        public InvUnitVector CrossProduct(InvUnitVector argument)
        {
            return InternalCrossProduct(argument);
        }

        public double DotProduct(InvUnitVector argument)
        {
            return InternalDotProduct(argument);
        }

        public void GetUnitVectorData(ref double[] coords)
        {
            InternalGetUnitVectorData(ref coords);
        }

        public bool IsEqualTo(InvUnitVector argument, double tolerance)
        {
            return InternalIsEqualTo(argument, tolerance);
        }

        public bool IsParallelTo(InvUnitVector argument, double tolerance)
        {
            return InternalIsParallelTo(argument, tolerance);
        }

        public bool IsPerpendicularTo(InvUnitVector argument, double tolerance)
        {
            return InternalIsPerpendicularTo(argument, tolerance);
        }

        public void PutUnitVectorData(ref double[] coords)
        {
            InternalPutUnitVectorData(ref coords);
        }

        public void TransformBy(InvMatrix matrix)
        {
            InternalTransformBy(matrix);
        }

        #endregion
    }
}
