// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.WorkPlaneDefinitionEnum. Do not edit; put additions in InvWorkPlaneDefinitionEnum.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public enum InvWorkPlaneDefinitionEnum
    {
        kAssemblyWorkPlane = Inventor.WorkPlaneDefinitionEnum.kAssemblyWorkPlane,
        kFixedWorkPlane = Inventor.WorkPlaneDefinitionEnum.kFixedWorkPlane,
        kLineAndPointWorkPlane = Inventor.WorkPlaneDefinitionEnum.kLineAndPointWorkPlane,
        kLineAndTangentWorkPlane = Inventor.WorkPlaneDefinitionEnum.kLineAndTangentWorkPlane,
        kLinePlaneAndAngleWorkPlane = Inventor.WorkPlaneDefinitionEnum.kLinePlaneAndAngleWorkPlane,
        kNormalToCurveWorkPlane = Inventor.WorkPlaneDefinitionEnum.kNormalToCurveWorkPlane,
        kPlaneAndOffsetWorkPlane = Inventor.WorkPlaneDefinitionEnum.kPlaneAndOffsetWorkPlane,
        kPlaneAndPointWorkPlane = Inventor.WorkPlaneDefinitionEnum.kPlaneAndPointWorkPlane,
        kPlaneAndTangentWorkPlane = Inventor.WorkPlaneDefinitionEnum.kPlaneAndTangentWorkPlane,
        kPointAndTangentWorkPlane = Inventor.WorkPlaneDefinitionEnum.kPointAndTangentWorkPlane,
        kThreePointsWorkPlane = Inventor.WorkPlaneDefinitionEnum.kThreePointsWorkPlane,
        kTorusMidPlaneWorkPlane = Inventor.WorkPlaneDefinitionEnum.kTorusMidPlaneWorkPlane,
        kTwoLinesWorkPlane = Inventor.WorkPlaneDefinitionEnum.kTwoLinesWorkPlane,
        kTwoPlanesWorkPlane = Inventor.WorkPlaneDefinitionEnum.kTwoPlanesWorkPlane
    }
}
