// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.WorkPointDefinitionEnum. Do not edit; put additions in InvWorkPointDefinitionEnum.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public enum InvWorkPointDefinitionEnum
    {
        kAssemblyWorkPoint = Inventor.WorkPointDefinitionEnum.kAssemblyWorkPoint,
        kCentroidWorkPoint = Inventor.WorkPointDefinitionEnum.kCentroidWorkPoint,
        kCurveAndEntityWorkPoint = Inventor.WorkPointDefinitionEnum.kCurveAndEntityWorkPoint,
        kFixedWorkPoint = Inventor.WorkPointDefinitionEnum.kFixedWorkPoint,
        kLineAndFaceWorkPoint = Inventor.WorkPointDefinitionEnum.kLineAndFaceWorkPoint,
        kMidPointWorkPoint = Inventor.WorkPointDefinitionEnum.kMidPointWorkPoint,
        kNonLinearEdgeWorkPoint = Inventor.WorkPointDefinitionEnum.kNonLinearEdgeWorkPoint,
        kPointWorkPoint = Inventor.WorkPointDefinitionEnum.kPointWorkPoint,
        kSphereCenterPointWorkPoint = Inventor.WorkPointDefinitionEnum.kSphereCenterPointWorkPoint,
        kThreePlanesWorkPoint = Inventor.WorkPointDefinitionEnum.kThreePlanesWorkPoint,
        kTorusCenterPointWorkPoint = Inventor.WorkPointDefinitionEnum.kTorusCenterPointWorkPoint,
        kTwoLinesWorkPoint = Inventor.WorkPointDefinitionEnum.kTwoLinesWorkPoint
    }
}
