// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.WorkPoints. Do not edit; put additions in InvWorkPoints.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvWorkPoints
    {
        #region Internal properties
        internal Inventor.WorkPoints InternalWorkPoints { get; set; }

        internal object InternalApplication
        {
            get { return WorkPointsInstance.Application; }
        }

        internal int InternalCount
        {
            get { return WorkPointsInstance.Count; }
        }

        internal InvWorkPoint InternalItem(object index)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance[index]);
        }

        internal InvComponentDefinition InternalParent
        {
            get { return InvComponentDefinition.ByInvComponentDefinition(WorkPointsInstance.Parent); }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)WorkPointsInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvWorkPoints(InvWorkPoints invWorkPoints)
        {
            InternalWorkPoints = invWorkPoints.InternalWorkPoints;
        }

        private InvWorkPoints(Inventor.WorkPoints invWorkPoints)
        {
            InternalWorkPoints = invWorkPoints;
        }
        #endregion

        #region Private methods
        private InvWorkPoint InternalAddAtCentroid(object entities, bool construction)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance.AddAtCentroid(entities, construction));
        }

        private InvWorkPoint InternalAddByCurveAndEntity(object curve, object entity, object proximityPoint, bool construction)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance.AddByCurveAndEntity(curve, entity, proximityPoint, construction));
        }

        private InvWorkPoint InternalAddByMidPoint(InvEdge edge, bool construction)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance.AddByMidPoint(edge?.EdgeInstance, construction));
        }

        private InvWorkPoint InternalAddByPoint(object point, bool construction)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance.AddByPoint(point, construction));
        }

        private InvWorkPoint InternalAddBySphereCenterPoint(InvFace face, bool construction)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance.AddBySphereCenterPoint(face?.FaceInstance, construction));
        }

        private InvWorkPoint InternalAddByThreePlanes(object plane1, object plane2, object plane3, bool construction)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance.AddByThreePlanes(plane1, plane2, plane3, construction));
        }

        private InvWorkPoint InternalAddByTorusCenterPoint(InvFace face, bool construction)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance.AddByTorusCenterPoint(face?.FaceInstance, construction));
        }

        private InvWorkPoint InternalAddByTwoLines(object line1, object line2, bool construction)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance.AddByTwoLines(line1, line2, construction));
        }

        private InvWorkPoint InternalAddFixed(InvPoint point, bool construction)
        {
            return InvWorkPoint.ByInvWorkPoint(WorkPointsInstance.AddFixed(point?.PointInstance, construction));
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.WorkPoints WorkPointsInstance
        {
            get { return InternalWorkPoints; }
            set { InternalWorkPoints = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvWorkPoint Item(object index)
        {
            return InternalItem(index);
        }

        public InvComponentDefinition Parent
        {
            get { return InternalParent; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvWorkPoints ByInvWorkPoints(InvWorkPoints invWorkPoints)
        {
            return invWorkPoints == null ? null : new InvWorkPoints(invWorkPoints);
        }

        [SupressImportIntoVM]
        public static InvWorkPoints ByInvWorkPoints(Inventor.WorkPoints invWorkPoints)
        {
            return invWorkPoints == null ? null : new InvWorkPoints(invWorkPoints);
        }
        #endregion

        #region Public methods
        public InvWorkPoint AddAtCentroid(object entities, bool construction)
        {
            return InternalAddAtCentroid(entities, construction);
        }

        public InvWorkPoint AddByCurveAndEntity(object curve, object entity, object proximityPoint, bool construction)
        {
            return InternalAddByCurveAndEntity(curve, entity, proximityPoint, construction);
        }

        public InvWorkPoint AddByMidPoint(InvEdge edge, bool construction)
        {
            return InternalAddByMidPoint(edge, construction);
        }

        public InvWorkPoint AddByPoint(object point, bool construction)
        {
            return InternalAddByPoint(point, construction);
        }

        public InvWorkPoint AddBySphereCenterPoint(InvFace face, bool construction)
        {
            return InternalAddBySphereCenterPoint(face, construction);
        }

        public InvWorkPoint AddByThreePlanes(object plane1, object plane2, object plane3, bool construction)
        {
            return InternalAddByThreePlanes(plane1, plane2, plane3, construction);
        }

        public InvWorkPoint AddByTorusCenterPoint(InvFace face, bool construction)
        {
            return InternalAddByTorusCenterPoint(face, construction);
        }

        public InvWorkPoint AddByTwoLines(object line1, object line2, bool construction)
        {
            return InternalAddByTwoLines(line1, line2, construction);
        }

        public InvWorkPoint AddFixed(InvPoint point, bool construction)
        {
            return InternalAddFixed(point, construction);
        }

        #endregion
    }
}
