// <auto-generated>
//     Generated by DynamoInventor.Generator from Autodesk.Inventor.Interop 31.10.27000.1
//     for Inventor.WorkPlanes. Do not edit; put additions in InvWorkPlanes.Custom.cs.
// </auto-generated>
using System;
using System.Collections.Generic;
using Autodesk.DesignScript.Runtime;

namespace InventorLibrary.API
{
    [IsVisibleInDynamoLibrary(false)]
    public partial class InvWorkPlanes
    {
        #region Internal properties
        internal Inventor.WorkPlanes InternalWorkPlanes { get; set; }

        internal object InternalApplication
        {
            get { return WorkPlanesInstance.Application; }
        }

        internal int InternalCount
        {
            get { return WorkPlanesInstance.Count; }
        }

        internal InvWorkPlane InternalItem(object index)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance[index]);
        }

        internal InvComponentDefinition InternalParent
        {
            get { return InvComponentDefinition.ByInvComponentDefinition(WorkPlanesInstance.Parent); }
        }

        internal InvObjectTypeEnum InternalType
        {
            get { return (InvObjectTypeEnum)WorkPlanesInstance.Type; }
        }

        #endregion

        #region Private constructors
        private InvWorkPlanes(InvWorkPlanes invWorkPlanes)
        {
            InternalWorkPlanes = invWorkPlanes.InternalWorkPlanes;
        }

        private InvWorkPlanes(Inventor.WorkPlanes invWorkPlanes)
        {
            InternalWorkPlanes = invWorkPlanes;
        }
        #endregion

        #region Private methods
        private InvWorkPlane InternalAddByLineAndPoint(object line, object point, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByLineAndPoint(line, point, construction));
        }

        private InvWorkPlane InternalAddByLineAndTangent(object line, InvFace face, InvPoint proximityPoint, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByLineAndTangent(line, face?.FaceInstance, proximityPoint?.PointInstance, construction));
        }

        private InvWorkPlane InternalAddByLinePlaneAndAngle(object line, object plane, object angle, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByLinePlaneAndAngle(line, plane, angle, construction));
        }

        private InvWorkPlane InternalAddByNormalToCurve(object curveEntity, object point, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByNormalToCurve(curveEntity, point, construction));
        }

        private InvWorkPlane InternalAddByPlaneAndOffset(object plane, object offset, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByPlaneAndOffset(plane, offset, construction));
        }

        private InvWorkPlane InternalAddByPlaneAndPoint(object plane, object point, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByPlaneAndPoint(plane, point, construction));
        }

        private InvWorkPlane InternalAddByPlaneAndTangent(object plane, InvFace face, InvPoint proximityPoint, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByPlaneAndTangent(plane, face?.FaceInstance, proximityPoint?.PointInstance, construction));
        }

        private InvWorkPlane InternalAddByPointAndTangent(object point, InvFace face, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByPointAndTangent(point, face?.FaceInstance, construction));
        }

        private InvWorkPlane InternalAddByThreePoints(object point1, object point2, object point3, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByThreePoints(point1, point2, point3, construction));
        }

        private InvWorkPlane InternalAddByTorusMidPlane(InvFace face, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByTorusMidPlane(face?.FaceInstance, construction));
        }

        private InvWorkPlane InternalAddByTwoLines(object line1, object line2, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByTwoLines(line1, line2, construction));
        }

        private InvWorkPlane InternalAddByTwoPlanes(object plane1, object plane2, object quadrantPoint, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddByTwoPlanes(plane1, plane2, quadrantPoint, construction));
        }

        private InvWorkPlane InternalAddFixed(InvPoint originPoint, InvUnitVector xAxis, InvUnitVector yAxis, bool construction)
        {
            return InvWorkPlane.ByInvWorkPlane(WorkPlanesInstance.AddFixed(originPoint?.PointInstance, xAxis?.UnitVectorInstance, yAxis?.UnitVectorInstance, construction));
        }

        // skipped: GetEnumerator(): returns System.Collections.IEnumerator, not wrapped
        #endregion

        #region Public properties
        /// <summary>The wrapped Inventor COM object. Not imported into the Dynamo VM.</summary>
        [SupressImportIntoVM]
        public Inventor.WorkPlanes WorkPlanesInstance
        {
            get { return InternalWorkPlanes; }
            set { InternalWorkPlanes = value; }
        }

        public object Application
        {
            get { return InternalApplication; }
        }

        public int Count
        {
            get { return InternalCount; }
        }

        public InvWorkPlane Item(object index)
        {
            return InternalItem(index);
        }

        public InvComponentDefinition Parent
        {
            get { return InternalParent; }
        }

        public InvObjectTypeEnum Type
        {
            get { return InternalType; }
        }

        #endregion

        #region Public static constructors
        public static InvWorkPlanes ByInvWorkPlanes(InvWorkPlanes invWorkPlanes)
        {
            return invWorkPlanes == null ? null : new InvWorkPlanes(invWorkPlanes);
        }

        [SupressImportIntoVM]
        public static InvWorkPlanes ByInvWorkPlanes(Inventor.WorkPlanes invWorkPlanes)
        {
            return invWorkPlanes == null ? null : new InvWorkPlanes(invWorkPlanes);
        }
        #endregion

        #region Public methods
        public InvWorkPlane AddByLineAndPoint(object line, object point, bool construction)
        {
            return InternalAddByLineAndPoint(line, point, construction);
        }

        public InvWorkPlane AddByLineAndTangent(object line, InvFace face, InvPoint proximityPoint, bool construction)
        {
            return InternalAddByLineAndTangent(line, face, proximityPoint, construction);
        }

        public InvWorkPlane AddByLinePlaneAndAngle(object line, object plane, object angle, bool construction)
        {
            return InternalAddByLinePlaneAndAngle(line, plane, angle, construction);
        }

        public InvWorkPlane AddByNormalToCurve(object curveEntity, object point, bool construction)
        {
            return InternalAddByNormalToCurve(curveEntity, point, construction);
        }

        public InvWorkPlane AddByPlaneAndOffset(object plane, object offset, bool construction)
        {
            return InternalAddByPlaneAndOffset(plane, offset, construction);
        }

        public InvWorkPlane AddByPlaneAndPoint(object plane, object point, bool construction)
        {
            return InternalAddByPlaneAndPoint(plane, point, construction);
        }

        public InvWorkPlane AddByPlaneAndTangent(object plane, InvFace face, InvPoint proximityPoint, bool construction)
        {
            return InternalAddByPlaneAndTangent(plane, face, proximityPoint, construction);
        }

        public InvWorkPlane AddByPointAndTangent(object point, InvFace face, bool construction)
        {
            return InternalAddByPointAndTangent(point, face, construction);
        }

        public InvWorkPlane AddByThreePoints(object point1, object point2, object point3, bool construction)
        {
            return InternalAddByThreePoints(point1, point2, point3, construction);
        }

        public InvWorkPlane AddByTorusMidPlane(InvFace face, bool construction)
        {
            return InternalAddByTorusMidPlane(face, construction);
        }

        public InvWorkPlane AddByTwoLines(object line1, object line2, bool construction)
        {
            return InternalAddByTwoLines(line1, line2, construction);
        }

        public InvWorkPlane AddByTwoPlanes(object plane1, object plane2, object quadrantPoint, bool construction)
        {
            return InternalAddByTwoPlanes(plane1, plane2, quadrantPoint, construction);
        }

        public InvWorkPlane AddFixed(InvPoint originPoint, InvUnitVector xAxis, InvUnitVector yAxis, bool construction)
        {
            return InternalAddFixed(originPoint, xAxis, yAxis, construction);
        }

        #endregion
    }
}
