//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamoInventor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Run Dynamo")]
        public string ButtonNameDynamo {
            get {
                return ((string)(this["ButtonNameDynamo"]));
            }
            set {
                this["ButtonNameDynamo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RunDynamo")]
        public string ButtonInternalNameDynamo {
            get {
                return ((string)(this["ButtonInternalNameDynamo"]));
            }
            set {
                this["ButtonInternalNameDynamo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Click this to run Dynamo in Inventor")]
        public string ButtonDescrDynamo {
            get {
                return ((string)(this["ButtonDescrDynamo"]));
            }
            set {
                this["ButtonDescrDynamo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Click this to run Dynamo in Inventor")]
        public string ButtonTooltipDynamo {
            get {
                return ((string)(this["ButtonTooltipDynamo"]));
            }
            set {
                this["ButtonTooltipDynamo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DynamoInventor.logo_square_32x32.ico")]
        public string ButtonIconDynamo32x32 {
            get {
                return ((string)(this["ButtonIconDynamo32x32"]));
            }
            set {
                this["ButtonIconDynamo32x32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DynamoInventor.logo_square_32x32.ico")]
        public string ButtonIconDynamo64x64 {
            get {
                return ((string)(this["ButtonIconDynamo64x64"]));
            }
            set {
                this["ButtonIconDynamo64x64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dynamo")]
        public string ribbonPanelDisplayNameDynamo {
            get {
                return ((string)(this["ribbonPanelDisplayNameDynamo"]));
            }
            set {
                this["ribbonPanelDisplayNameDynamo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dynamo:InventorDynamo:DynamoRibbonPanel")]
        public string ribbonPanelInternalName {
            get {
                return ((string)(this["ribbonPanelInternalName"]));
            }
            set {
                this["ribbonPanelInternalName"] = value;
            }
        }
    }
}
